CREATE TABLE users (
    id        bigint NOT NULL,
    tenant_id bigint NOT NULL,
    name      text NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (tenant_id, id)
);

-- A nullable foreign key nobody mapped: inserts still work, so this is a
-- warning about a read-only relationship, not an error.
CREATE TABLE posts (
    id        bigint PRIMARY KEY,
    author_id bigint REFERENCES users(id),
    title     text NOT NULL
);

-- A mandatory foreign key nobody mapped: no row can be inserted at all.
CREATE TABLE docs (
    id       bigint PRIMARY KEY,
    owner_id bigint NOT NULL REFERENCES users(id),
    title    text NOT NULL
);

-- A composite key with one column mapped and one not.
CREATE TABLE comments (
    id        bigint PRIMARY KEY,
    tenant_id bigint NOT NULL,
    author_id bigint,
    body      text NOT NULL,
    CONSTRAINT comments_author_fkey FOREIGN KEY (tenant_id, author_id) REFERENCES users(tenant_id, id)
);

-- An entity that never reads its own identity back.
CREATE TABLE notes (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body text NOT NULL
);
