// Code generated by orm. DO NOT EDIT.

package domain

import (
	"github.com/AlexAli29/orm"
)

// orderMeta describes how Order is read from public.orders.
var orderMeta = orm.EntityMeta[Order]{
	Table:  orm.TableID{Schema: "public", Name: "orders"},
	Source: ordersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "user_id", Field: "UserID", NotNull: true},
		{Name: "label", Field: "Label", NotNull: true},
		{Name: "optional_id", Field: "OptionalID"},
	},
	Dest:  orderDest,
	Value: orderValue,
}

// orderDest returns a pointer to the field holding column idx of public.orders.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func orderDest(e *Order, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.UserID
	case 2:
		return &e.Label
	case 3:
		return &e.OptionalID
	default:
		return nil
	}
}

// orderValue returns the value of the field holding column idx of public.orders.
//
// It is the counterpart of orderDest and is written the same way, so an
// insert reads the entity without reflection either.
func orderValue(e *Order, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.UserID
	case 2:
		return e.Label
	case 3:
		return e.OptionalID
	default:
		return nil
	}
}

// tokenMeta describes how Token is read from public.tokens.
var tokenMeta = orm.EntityMeta[Token]{
	Table:  orm.TableID{Schema: "public", Name: "tokens"},
	Source: tokensSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "tenant_id", Field: "TenantID", NotNull: true},
		{Name: "value", Field: "Value", NotNull: true, HasDefault: true},
	},
	Dest:  tokenDest,
	Value: tokenValue,
}

// tokenDest returns a pointer to the field holding column idx of public.tokens.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func tokenDest(e *Token, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.TenantID
	case 2:
		return &e.Value
	default:
		return nil
	}
}

// tokenValue returns the value of the field holding column idx of public.tokens.
//
// It is the counterpart of tokenDest and is written the same way, so an
// insert reads the entity without reflection either.
func tokenValue(e *Token, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.TenantID
	case 2:
		return e.Value
	default:
		return nil
	}
}

// userMeta describes how User is read from public.users.
var userMeta = orm.EntityMeta[User]{
	Table:  orm.TableID{Schema: "public", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "external_id", Field: "ExternalID", NotNull: true},
		{Name: "optional_id", Field: "OptionalID"},
		{Name: "tags", Field: "Tags", NotNull: true},
	},
	Dest:  userDest,
	Value: userValue,
}

// userDest returns a pointer to the field holding column idx of public.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userDest(e *User, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.ExternalID
	case 3:
		return &e.OptionalID
	case 4:
		return &e.Tags
	default:
		return nil
	}
}

// userValue returns the value of the field holding column idx of public.users.
//
// It is the counterpart of userDest and is written the same way, so an
// insert reads the entity without reflection either.
func userValue(e *User, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.ExternalID
	case 3:
		return e.OptionalID
	case 4:
		return e.Tags
	default:
		return nil
	}
}

// userOrderMeta describes how UserOrder is read from public.user_orders.
var userOrderMeta = orm.EntityMeta[UserOrder]{
	Table:  orm.TableID{Schema: "public", Name: "user_orders"},
	Source: userOrdersSource,
	Columns: []orm.ColumnMeta{
		{Name: "user_id", Field: "UserID"},
		{Name: "order_id", Field: "OrderID"},
		{Name: "label", Field: "Label"},
	},
	Dest:  userOrderDest,
	Value: userOrderValue,
}

// userOrderDest returns a pointer to the field holding column idx of public.user_orders.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userOrderDest(e *UserOrder, idx int) any {
	switch idx {
	case 0:
		return &e.UserID
	case 1:
		return &e.OrderID
	case 2:
		return &e.Label
	default:
		return nil
	}
}

// userOrderValue returns the value of the field holding column idx of public.user_orders.
//
// It is the counterpart of userOrderDest and is written the same way, so an
// insert reads the entity without reflection either.
func userOrderValue(e *UserOrder, idx int) any {
	switch idx {
	case 0:
		return e.UserID
	case 1:
		return e.OrderID
	case 2:
		return e.Label
	default:
		return nil
	}
}

// userSummaryMeta describes how UserSummary is read from public.user_summaries.
var userSummaryMeta = orm.EntityMeta[UserSummary]{
	Table:  orm.TableID{Schema: "public", Name: "user_summaries"},
	Source: userSummariesSource,
	Columns: []orm.ColumnMeta{
		{Name: "user_id", Field: "UserID"},
		{Name: "label", Field: "Label"},
		{Name: "orders", Field: "Orders"},
	},
	Dest:  userSummaryDest,
	Value: userSummaryValue,
}

// userSummaryDest returns a pointer to the field holding column idx of public.user_summaries.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userSummaryDest(e *UserSummary, idx int) any {
	switch idx {
	case 0:
		return &e.UserID
	case 1:
		return &e.Label
	case 2:
		return &e.Orders
	default:
		return nil
	}
}

// userSummaryValue returns the value of the field holding column idx of public.user_summaries.
//
// It is the counterpart of userSummaryDest and is written the same way, so an
// insert reads the entity without reflection either.
func userSummaryValue(e *UserSummary, idx int) any {
	switch idx {
	case 0:
		return e.UserID
	case 1:
		return e.Label
	case 2:
		return e.Orders
	default:
		return nil
	}
}
