// Code generated by orm. DO NOT EDIT.

package domain

import (
	"github.com/AlexAli29/orm"
	"github.com/google/uuid"
)

// ordersSource is the occurrence of public.orders that Orders reads from.
var ordersSource = orm.NewSource("public", "orders")

// orderTable holds one typed descriptor per mapped column of public.orders, and one
// per relation reconciliation proved.
type orderTable struct {
	src        *orm.Source
	ID         orm.OrdCol[Order, uuid.UUID]
	UserID     orm.OrdCol[Order, uuid.UUID]
	Label      orm.TextCol[Order]
	OptionalID orm.NullOrdCol[Order, uuid.UUID]
	User       orm.Rel[Order, User]
}

// newOrderTable builds the descriptors for one occurrence of public.orders.
func newOrderTable(src *orm.Source) orderTable {
	return orderTable{
		src:        src,
		ID:         orm.NewOrdCol[Order, uuid.UUID](src, "id"),
		UserID:     orm.NewOrdCol[Order, uuid.UUID](src, "user_id"),
		Label:      orm.NewTextCol[Order](src, "label"),
		OptionalID: orm.NewNullOrdCol[Order, uuid.UUID](src, "optional_id"),
		User: orm.NewOneRel(orm.OneRelSpec[Order, User]{
			Name:        "User",
			Parent:      src,
			Target:      usersSource,
			Keys:        orderUserKeys,
			Columns:     orderUserColumns,
			Bind:        orderUserBind,
			ExtractKeys: orderUserLoadKeys,
			Dest:        userRelDest,
			Attach:      orderUserAttach,
			Refs:        orderUserRefs,
		}),
	}
}

// Orders addresses the columns of public.orders.
var Orders = newOrderTable(ordersSource)

// As returns descriptors for a second occurrence of public.orders under
// alias, leaving Orders untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t orderTable) As(alias string) orderTable { return newOrderTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t orderTable) Source() *orm.Source { return t.src }

// tokensSource is the occurrence of public.tokens that Tokens reads from.
var tokensSource = orm.NewSource("public", "tokens")

// tokenTable holds one typed descriptor per mapped column of public.tokens.
type tokenTable struct {
	src      *orm.Source
	ID       orm.OrdCol[Token, uuid.UUID]
	TenantID orm.OrdCol[Token, uuid.UUID]
	Value    orm.OrdCol[Token, uuid.UUID]
}

// newTokenTable builds the descriptors for one occurrence of public.tokens.
func newTokenTable(src *orm.Source) tokenTable {
	return tokenTable{
		src:      src,
		ID:       orm.NewOrdCol[Token, uuid.UUID](src, "id"),
		TenantID: orm.NewOrdCol[Token, uuid.UUID](src, "tenant_id"),
		Value:    orm.NewOrdCol[Token, uuid.UUID](src, "value"),
	}
}

// Tokens addresses the columns of public.tokens.
var Tokens = newTokenTable(tokensSource)

// As returns descriptors for a second occurrence of public.tokens under
// alias, leaving Tokens untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t tokenTable) As(alias string) tokenTable { return newTokenTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t tokenTable) Source() *orm.Source { return t.src }

// usersSource is the occurrence of public.users that Users reads from.
var usersSource = orm.NewSource("public", "users")

// userTable holds one typed descriptor per mapped column of public.users, and one
// per relation reconciliation proved.
type userTable struct {
	src        *orm.Source
	ID         orm.OrdCol[User, uuid.UUID]
	Email      orm.TextCol[User]
	ExternalID orm.OrdCol[User, uuid.UUID]
	OptionalID orm.NullOrdCol[User, uuid.UUID]
	Tags       orm.Col[User, []uuid.UUID]
	Orders     orm.Rel[User, Order]
}

// newUserTable builds the descriptors for one occurrence of public.users.
func newUserTable(src *orm.Source) userTable {
	return userTable{
		src:        src,
		ID:         orm.NewOrdCol[User, uuid.UUID](src, "id"),
		Email:      orm.NewTextCol[User](src, "email"),
		ExternalID: orm.NewOrdCol[User, uuid.UUID](src, "external_id"),
		OptionalID: orm.NewNullOrdCol[User, uuid.UUID](src, "optional_id"),
		Tags:       orm.NewCol[User, []uuid.UUID](src, "tags"),
		Orders: orm.NewManyRel(orm.ManyRelSpec[User, Order]{
			Name:        "Orders",
			Parent:      src,
			Target:      ordersSource,
			Keys:        userOrdersKeys,
			Columns:     userOrdersColumns,
			ExtractKeys: userOrdersLoadKeys,
			Dest:        orderRelDest,
			Attach:      userOrdersAttach,
			Refs:        userOrdersRefs,
		}),
	}
}

// Users addresses the columns of public.users.
var Users = newUserTable(usersSource)

// As returns descriptors for a second occurrence of public.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userTable) As(alias string) userTable { return newUserTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userTable) Source() *orm.Source { return t.src }

// userOrdersSource is the occurrence of public.user_orders that UserOrders reads from.
var userOrdersSource = orm.NewSource("public", "user_orders")

// userOrderTable holds one typed descriptor per mapped column of public.user_orders.
type userOrderTable struct {
	src     *orm.Source
	UserID  orm.NullOrdCol[UserOrder, uuid.UUID]
	OrderID orm.NullOrdCol[UserOrder, uuid.UUID]
	Label   orm.NullTextCol[UserOrder]
}

// newUserOrderTable builds the descriptors for one occurrence of public.user_orders.
func newUserOrderTable(src *orm.Source) userOrderTable {
	return userOrderTable{
		src:     src,
		UserID:  orm.NewNullOrdCol[UserOrder, uuid.UUID](src, "user_id"),
		OrderID: orm.NewNullOrdCol[UserOrder, uuid.UUID](src, "order_id"),
		Label:   orm.NewNullTextCol[UserOrder](src, "label"),
	}
}

// UserOrders addresses the columns of public.user_orders.
var UserOrders = newUserOrderTable(userOrdersSource)

// As returns descriptors for a second occurrence of public.user_orders under
// alias, leaving UserOrders untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userOrderTable) As(alias string) userOrderTable { return newUserOrderTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userOrderTable) Source() *orm.Source { return t.src }

// userSummariesSource is the occurrence of public.user_summaries that UserSummaries reads from.
var userSummariesSource = orm.NewSource("public", "user_summaries")

// userSummaryTable holds one typed descriptor per mapped column of public.user_summaries.
type userSummaryTable struct {
	src    *orm.Source
	UserID orm.NullOrdCol[UserSummary, uuid.UUID]
	Label  orm.NullTextCol[UserSummary]
	Orders orm.NullOrdCol[UserSummary, int64]
}

// newUserSummaryTable builds the descriptors for one occurrence of public.user_summaries.
func newUserSummaryTable(src *orm.Source) userSummaryTable {
	return userSummaryTable{
		src:    src,
		UserID: orm.NewNullOrdCol[UserSummary, uuid.UUID](src, "user_id"),
		Label:  orm.NewNullTextCol[UserSummary](src, "label"),
		Orders: orm.NewNullOrdCol[UserSummary, int64](src, "orders"),
	}
}

// UserSummaries addresses the columns of public.user_summaries.
var UserSummaries = newUserSummaryTable(userSummariesSource)

// As returns descriptors for a second occurrence of public.user_summaries under
// alias, leaving UserSummaries untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userSummaryTable) As(alias string) userSummaryTable {
	return newUserSummaryTable(t.src.As(alias))
}

// Source returns the occurrence these descriptors qualify against.
func (t userSummaryTable) Source() *orm.Source { return t.src }
