// Code generated by orm. DO NOT EDIT.

package domain

import (
	"github.com/AlexAli29/orm"
	"github.com/google/uuid"
)

// userNulls mirrors User with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into User would fail on those rather than report an absent
// relation, so the row lands here first.
type userNulls struct {
	ID         *uuid.UUID
	Email      *string
	ExternalID *uuid.UUID
	OptionalID *uuid.UUID
	Tags       []uuid.UUID
}

// userNullDest returns scan destinations for every column of public.users.
func userNullDest(n *userNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.ExternalID,
		&n.OptionalID,
		&n.Tags,
	}
}

// userFromNulls rebuilds User from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func userFromNulls(n *userNulls) (User, bool) {
	if n.ID == nil {
		return User{}, false
	}
	return User{
		ID:         *n.ID,
		Email:      *n.Email,
		ExternalID: *n.ExternalID,
		OptionalID: n.OptionalID,
		Tags:       n.Tags,
	}, true
}

// orderRelDest returns scan destinations for a Order loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func orderRelDest(t *Order) []any {
	dest := make([]any, 4)
	for i := range dest {
		dest[i] = orderDest(t, i)
	}
	return dest
}

// userRelDest returns scan destinations for a User loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func userRelDest(t *User) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = userDest(t, i)
	}
	return dest
}

// orderUserColumns are the columns of public.users that Order.User reads.
var orderUserColumns = []string{
	"id",
	"email",
	"external_id",
	"optional_id",
	"tags",
}

// orderUserKeys pairs the columns User matches on, in the order user_id declares them.
var orderUserKeys = []orm.RelKey{
	{Parent: "user_id", Target: "id", Type: "uuid"},
}

// orderUserBind allocates one row's worth of storage for Order.User and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func orderUserBind() ([]any, func(*Order)) {
	var n userNulls
	return userNullDest(&n), func(e *Order) {
		if v, ok := userFromNulls(&n); ok {
			e.User = orm.NewOne(&v)
			return
		}
		e.User = orm.Absent[User]()
	}
}

// orderUserAttach sets Order.User from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func orderUserAttach(e *Order, t *User) {
	if t == nil {
		e.User = orm.Absent[User]()
		return
	}
	e.User = orm.NewOne(t)
}

// orderUserRefs appends pointers to the rows Order.User loaded, which is what a
// relation of User is loaded against.
func orderUserRefs(e *Order, out []*User) []*User {
	if v, ok := e.User.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// orderUserLoadKeys reads the keys of Order.User from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func orderUserLoadKeys(parents []*Order) ([]any, error) {
	k0 := make([]uuid.UUID, len(parents))
	for i, p := range parents {
		k0[i] = p.UserID
	}
	return []any{
		k0,
	}, nil
}

// userOrdersColumns are the columns of public.orders that User.Orders reads.
var userOrdersColumns = []string{
	"id",
	"user_id",
	"label",
	"optional_id",
}

// userOrdersKeys pairs the columns Orders matches on, in the order user_id declares them.
var userOrdersKeys = []orm.RelKey{
	{Parent: "id", Target: "user_id", Type: "uuid"},
}

// userOrdersAttach sets User.Orders from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userOrdersAttach(e *User, rows []Order) { e.Orders = orm.NewManyFrom(rows) }

// userOrdersRefs appends pointers to the rows User.Orders loaded, which is what a
// relation of Order is loaded against.
func userOrdersRefs(e *User, out []*Order) []*Order {
	rows, ok := e.Orders.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userOrdersLoadKeys reads the keys of User.Orders from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userOrdersLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]uuid.UUID, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
