package main

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/AlexAli29/orm/internal/testdb"
)

// M16.5 compatibility: what a materialized view's columns say about NULL.
//
// PostgreSQL records no NOT NULL for a view or materialized-view column, because
// it cannot say whether an expression yields NULL — an aggregate over no rows, a
// CASE with no ELSE, the right-hand side of a LEFT JOIN. Introspection therefore
// reads every such column as nullable, which the code calls the honest answer
// rather than a guess in either direction.
//
// That is the frozen rule, and what is proven here is the rule rather than a
// wish. It has one consequence worth stating plainly: the declaration decides
// what the generated Go says, the catalog cannot contradict it, and a column that
// really can be NULL must be declared as a pointer by the person who wrote the
// query. Inferring it would mean parsing SQL, which nothing in this project does.

// nullDDL builds a schema whose materialized view exercises every shape that
// makes a column's nullability undecidable from the catalog.
const nullDDL = `
CREATE TABLE public.owners (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
CREATE TABLE public.items (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id bigint,
    label    text NOT NULL,
    note     text
);

CREATE MATERIALIZED VIEW public.owner_rollups AS
    SELECT o.id                                        AS id,          -- NOT NULL base column
           o.name                                      AS name,        -- NOT NULL base column
           i.note                                      AS note,        -- nullable base column
           i.label                                     AS join_label,  -- NOT NULL, but LEFT JOINed
           count(i.id)                                 AS item_count,  -- aggregate
           CASE WHEN o.id > 0 THEN o.name END          AS cased        -- CASE with no ELSE
      FROM public.owners o
      LEFT JOIN public.items i ON i.owner_id = o.id
     GROUP BY o.id, o.name, i.note, i.label;

CREATE UNIQUE INDEX owner_rollup_key ON public.owner_rollups (id, join_label);
`

// The catalog's answer, and the project's, agree: every column is nullable.
func TestCompatNull_everyMaterializedViewColumnIsNullableInTheCatalog(t *testing.T) {
	dsn := testdb.Create(t, nullDDL)
	p := newProject(t, "package domain\n")
	p.DSN = dsn
	writeFile(t, p.Conf, "version: 1\n\nschema:\n  dsn: \""+dsn+"\"\n"+
		"  search_path:\n    - public\n\npackages:\n  - path: ./domain\n    output: same\n")

	notnull := p.Query(`SELECT a.attname || '=' || a.attnotnull::text
	                      FROM pg_attribute a
	                     WHERE a.attrelid = 'public.owner_rollups'::regclass AND a.attnum > 0
	                     ORDER BY a.attnum`)
	if len(notnull) != 6 {
		t.Fatalf("the materialized view has %d columns: %v", len(notnull), notnull)
	}
	for _, c := range notnull {
		if !strings.HasSuffix(c, "=false") {
			t.Errorf("%s: PostgreSQL records NOT NULL on a materialized-view column, which "+
				"this project's introspection assumes it never does", c)
		}
	}
	// Including the two that a reader would expect to be NOT NULL: they come
	// from NOT NULL base columns, and the catalog still says nothing.
	if !strings.Contains(strings.Join(notnull, " "), "name=false") {
		t.Error("the column derived from a NOT NULL base column is not reported nullable")
	}
}

// The declaration decides, and either spelling is accepted.
//
// This is the conservative behaviour rather than an inference: the catalog cannot
// contradict a declaration it has no opinion about, so a developer who knows the
// query says non-null gets non-null, and one who declares a pointer gets a
// pointer. Both must reconcile clean, or the rule would be an inference wearing a
// refusal's clothes.
func TestCompatNull_theDeclarationDecidesAndBothSpellingsReconcile(t *testing.T) {
	for _, c := range []struct{ what, note, joinLabel, cased string }{
		{"every derived column declared nullable", "*string", "*string", "*string"},
		{"every derived column declared non-null", "string", "string", "string"},
	} {
		t.Run(c.what, func(t *testing.T) {
			dsn := testdb.Create(t, nullDDL)
			src := `package domain

//orm:table public.owners
type Owner struct {
	ID   int64 ` + "`orm:\"pk,identity\"`" + `
	Name string
}

//orm:table public.items
type Item struct {
	ID      int64 ` + "`orm:\"pk,identity\"`" + `
	OwnerID *int64
	Label   string
	Note    *string
}

//orm:materialized-view public.owner_rollups
type OwnerRollup struct {
	ID         int64
	Name       string
	Note       ` + c.note + `
	JoinLabel  ` + c.joinLabel + ` ` + "`orm:\"column:join_label\"`" + `
	ItemCount  int64 ` + "`orm:\"column:item_count\"`" + `
	Cased      ` + c.cased + `
}
`
			p := newProject(t, src)
			p.DSN = dsn
			writeFile(t, p.Conf, "version: 1\n\nschema:\n  dsn: \""+dsn+"\"\n"+
				"  search_path:\n    - public\n\npackages:\n  - path: ./domain\n    output: same\n")
			p.MustRun("check")
			p.MustRun("generate")
			p.MustRun("check", "--generated")
		})
	}
}

// A table's nullability is still enforced, so the rule above is about views
// rather than about nullability having been abandoned.
func TestCompatNull_tableNullabilityIsStillEnforced(t *testing.T) {
	dsn := testdb.Create(t, nullDDL)
	// items.note is nullable in the catalog and declared non-null here.
	src := `package domain

//orm:table public.items
type Item struct {
	ID      int64 ` + "`orm:\"pk,identity\"`" + `
	OwnerID *int64
	Label   string
	Note    string
}
`
	p := newProject(t, src)
	p.DSN = dsn
	writeFile(t, p.Conf, "version: 1\n\nschema:\n  dsn: \""+dsn+"\"\n"+
		"  search_path:\n    - public\n\npackages:\n  - path: ./domain\n    output: same\n")
	code, stdout, stderr := p.Run("check")
	out := stdout + stderr
	if code == exitClean {
		t.Fatalf("a nullable table column declared non-null reconciled clean, so the "+
			"view rule has been applied to tables too:\n%s", out)
	}
	if !strings.Contains(strings.ToLower(out), "null") {
		t.Errorf("the finding does not mention nullability:\n%s", out)
	}
}

// And a NULL really arrives, through the generated API, in a pointer field.
//
// The catalog says nothing and the declaration says pointer; this is the half
// that proves the declaration was right — an owner with no items produces NULLs
// from the LEFT JOIN and the CASE, and they scan.
func TestCompatNull_nullsFromAJoinScanThroughTheGeneratedAPI(t *testing.T) {
	dsn := testdb.Create(t, nullDDL)
	src := `package domain

//orm:table public.owners
type Owner struct {
	ID   int64 ` + "`orm:\"pk,identity\"`" + `
	Name string
}

//orm:materialized-view public.owner_rollups
type OwnerRollup struct {
	ID        int64
	Name      string
	Note      *string
	JoinLabel *string ` + "`orm:\"column:join_label\"`" + `
	ItemCount int64   ` + "`orm:\"column:item_count\"`" + `
	Cased     *string
}
`
	p := newProject(t, src)
	p.DSN = dsn
	writeFile(t, p.Conf, "version: 1\n\nschema:\n  dsn: \""+dsn+"\"\n"+
		"  search_path:\n    - public\n\npackages:\n  - path: ./domain\n    output: same\n")
	p.MustRun("check")
	p.MustRun("generate")

	writeFile(t, filepath.Join(p.Dir, "main.go"), `package main

import (
	"context"
	"fmt"
	"os"

	"example.com/managed/domain"
	"github.com/jackc/pgx/v5/pgxpool"
)

func main() {
	ctx := context.Background()
	pool, err := pgxpool.New(ctx, os.Getenv("DSN"))
	if err != nil {
		panic(err)
	}
	defer pool.Close()
	if _, err := pool.Exec(ctx, "INSERT INTO owners (name) VALUES ('lonely')"); err != nil {
		panic(err)
	}
	if _, err := pool.Exec(ctx, "REFRESH MATERIALIZED VIEW public.owner_rollups"); err != nil {
		panic(err)
	}
	rows, err := domain.New(pool).OwnerRollups.Query().All(ctx)
	if err != nil {
		panic("query: " + err.Error())
	}
	if len(rows) != 1 {
		panic(fmt.Sprintf("want one row, got %d", len(rows)))
	}
	r := rows[0]
	fmt.Printf("name=%s count=%d join_null=%t note_null=%t cased_present=%t\n",
		r.Name, r.ItemCount, r.JoinLabel == nil, r.Note == nil, r.Cased != nil)
}
`)
	got := runProgram(t, p)
	for _, want := range []string{
		"name=lonely",
		"count=0",        // an aggregate over no matching rows
		"join_null=true", // the LEFT JOIN produced no right-hand row
		"note_null=true",
		"cased_present=true", // the CASE matched, so this one is not NULL
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the generated API did not produce %q:\n%s", want, got)
		}
	}
}
