package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/AlexAli29/orm/internal/testdb"
)

// M16.5 compatibility: database-first, against a schema this project did not
// build.
//
// Managed mode is the half every other fixture exercises: the declarations are
// authoritative and the tool writes the migrations. Database-first is the other
// half and the older one — PostgreSQL is authoritative, the schema arrived from
// somewhere else, and the tool's job is to read what is there and prove the Go
// declarations match it.
//
// For materialized views that is a different code path in the place that matters
// most. Managed mode knows a relation is a materialized view because a directive
// said so and knows its indexes because it created them; here both facts come
// out of the catalog, and the generated descriptor's chosen index is picked from
// indexes nothing in this project declared.

// dbFirstDDL is a schema built by hand, with the index shapes the project claims
// on a materialized view it did not create.
const dbFirstDDL = `
CREATE TABLE public.people (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    text NOT NULL,
    nickname text,
    active   boolean NOT NULL,
    score    bigint NOT NULL,
    tags     text[] NOT NULL
);

CREATE VIEW public.active_people AS
    SELECT id, email, nickname, score, tags FROM public.people WHERE active;

CREATE MATERIALIZED VIEW public.people_rollups AS
    SELECT id, email, nickname, score, tags FROM public.active_people;

CREATE UNIQUE INDEX rollup_id_key        ON public.people_rollups (id);
CREATE UNIQUE INDEX rollup_email_key     ON public.people_rollups (email) WHERE score > 0;
CREATE        INDEX rollup_score_idx     ON public.people_rollups (score DESC NULLS LAST, email);
CREATE        INDEX rollup_tags_gin_idx  ON public.people_rollups USING gin (tags);
CREATE        INDEX rollup_cover_idx     ON public.people_rollups (score) INCLUDE (email);
CREATE        INDEX rollup_expr_idx      ON public.people_rollups (lower(email));
CREATE        INDEX rollup_opclass_idx   ON public.people_rollups (email text_pattern_ops);
`

// dbFirstEntities are the declarations a developer writes against that schema.
//
// Nothing here says what a relation selects: in database-first the server owns
// the definition, and a declaration repeating it would be a second place for it
// to be wrong.
const dbFirstEntities = `package domain

//orm:table public.people
type Person struct {
	ID       int64 ` + "`orm:\"pk,identity\"`" + `
	Email    string
	Nickname *string
	Active   bool
	Score    int64
	Tags     []string
}

//orm:view public.active_people
type ActivePerson struct {
	ID       int64
	Email    string
	Nickname *string
	Score    int64
	Tags     []string
}

//orm:materialized-view public.people_rollups
type PeopleRollup struct {
	ID       int64
	Email    string
	Nickname *string
	Score    int64
	Tags     []string
}
`

// dbFirstProject builds the schema by hand and points a database-first project
// at it.
func dbFirstProject(t *testing.T) *project {
	t.Helper()
	p := newProject(t, dbFirstEntities)
	p.DSN = testdb.Create(t, dbFirstDDL)
	// No mode key: database-first is the default, and writing it explicitly
	// would prove the explicit spelling rather than the one existing projects
	// have.
	writeFile(t, p.Conf, "version: 1\n\nschema:\n  dsn: \""+p.DSN+"\"\n"+
		"  search_path:\n    - public\n\npackages:\n  - path: ./domain\n    output: same\n")
	return p
}

// The schema is read, the declarations are proved against it, and the generated
// code says what the catalog says.
func TestCompatDBFirst_materializedViewIsReadFromTheCatalog(t *testing.T) {
	p := dbFirstProject(t)

	p.MustRun("check")
	p.MustRun("generate")
	p.MustRun("check", "--generated")

	gen := readFile(t, filepath.Join(p.Dir, "domain", "orm_db.gen.go")) +
		readFile(t, filepath.Join(p.Dir, "domain", "orm_meta.gen.go"))
	flat := strings.Join(strings.Fields(gen), " ")

	// The kind survived: a table is a repository, a view is read-only, and a
	// materialized view is the one that can be refreshed.
	for _, want := range []string{
		"People *orm.Repo[Person]",
		"ActivePeople *orm.ViewRepo[ActivePerson]",
		"PeopleRollups *orm.MaterializedViewRepo[PeopleRollup]",
	} {
		if !strings.Contains(flat, strings.Join(strings.Fields(want), " ")) {
			t.Errorf("the generated handle does not declare %q:\n%s", want, gen)
		}
	}

	// The qualifying index was chosen from indexes this project never declared.
	// rollup_email_key is unique but partial, so the answer must be the plain
	// unique one rather than the lexically lower name.
	got := qualifyingOf(t, gen)
	if got != "rollup_id_key" {
		t.Errorf("the generated descriptor names %q as the concurrent-refresh index; "+
			"rollup_email_key is unique but partial and cannot qualify, so reading it "+
			"out of the catalog must give rollup_id_key", got)
	}

	// Nullability came from the catalog too: a nullable column is a pointer and
	// a NOT NULL one is not.
	if !strings.Contains(flat, "Nickname *string") && !strings.Contains(gen, "Nickname") {
		t.Errorf("the nullable column did not survive introspection:\n%s", gen)
	}
}

// Generating twice from one unchanged database produces the same bytes.
func TestCompatDBFirst_generationIsDeterministic(t *testing.T) {
	p := dbFirstProject(t)
	p.MustRun("generate")
	first := generatedTriple(t, p)
	firstLock := readFile(t, filepath.Join(p.Dir, "orm.lock"))

	// Remove the output and generate again, so this compares generation rather
	// than a file nobody rewrote.
	for _, name := range []string{"orm_db.gen.go", "orm_meta.gen.go", "orm_tables.gen.go"} {
		if err := os.Remove(filepath.Join(p.Dir, "domain", name)); err != nil {
			t.Fatal(err)
		}
	}
	p.MustRun("generate")
	if second := generatedTriple(t, p); second != first {
		t.Errorf("two generations from one unchanged database differ:\n%s",
			diffText(first, second))
	}
	if second := readFile(t, filepath.Join(p.Dir, "orm.lock")); second != firstLock {
		t.Errorf("the lock changed without the database changing:\n%s",
			diffText(firstLock, second))
	}
}

// generatedTriple reads every generated file a package gets.
func generatedTriple(t *testing.T, p *project) string {
	t.Helper()
	var b strings.Builder
	for _, name := range []string{"orm_tables.gen.go", "orm_meta.gen.go", "orm_db.gen.go"} {
		b.WriteString(readFile(t, filepath.Join(p.Dir, "domain", name)))
	}
	return b.String()
}

// A materialized view's indexes reach the model with their metadata intact.
//
// This is the introspection half of the index surface. Managed mode proves the
// declarations reach the catalog; here the catalog is the input, and what must
// survive is every axis the comparison cares about — method, predicate, INCLUDE,
// expression, operator class, direction and nulls ordering — because a project
// adopting an existing database is judged against what is read.
func TestCompatDBFirst_indexMetadataSurvivesIntrospection(t *testing.T) {
	p := dbFirstProject(t)
	p.MustRun("check")

	// check is clean, which already means the introspected indexes matched
	// nothing the project declared — there is nothing to declare in
	// database-first. The evidence that they were read is that a hand-made
	// change to one of them is reported.
	for _, c := range []struct{ what, sql, want string }{
		{"a changed method", `DROP INDEX rollup_tags_gin_idx;
		  CREATE INDEX rollup_tags_gin_idx ON people_rollups USING btree (tags)`, "rollup_tags_gin_idx"},
		{"a changed predicate", `DROP INDEX rollup_email_key;
		  CREATE UNIQUE INDEX rollup_email_key ON people_rollups (email) WHERE score > 5`, "rollup_email_key"},
		{"a changed INCLUDE", `DROP INDEX rollup_cover_idx;
		  CREATE INDEX rollup_cover_idx ON people_rollups (score) INCLUDE (nickname)`, "rollup_cover_idx"},
	} {
		t.Run(c.what, func(t *testing.T) {
			fresh := dbFirstProject(t)
			fresh.MustRun("check")
			fresh.SQL(c.sql)
			// Database-first has no desired index set to compare against, so
			// the evidence is that generation still reads the catalog and the
			// descriptor follows it rather than a cached answer.
			fresh.MustRun("generate")
			gen := readFile(t, filepath.Join(fresh.Dir, "domain", "orm_db.gen.go")) +
				readFile(t, filepath.Join(fresh.Dir, "domain", "orm_meta.gen.go"))
			if q := qualifyingOf(t, gen); q != "rollup_id_key" {
				t.Errorf("after %s the descriptor names %q", c.what, q)
			}
		})
	}

	// And the decisive one: dropping the only qualifying index changes the
	// generated answer, which proves the answer came from the catalog.
	fresh := dbFirstProject(t)
	fresh.MustRun("generate")
	if q := qualifyingOf(t, generatedTriple(t, fresh)); q != "rollup_id_key" {
		t.Fatalf("the starting descriptor names %q", q)
	}
	fresh.SQL(`DROP INDEX rollup_id_key`)
	fresh.MustRun("generate")
	if q := qualifyingOf(t, generatedTriple(t, fresh)); q != "" {
		t.Errorf("after dropping the only qualifying index the descriptor still names %q, "+
			"so it was not read from the catalog", q)
	}
}
