package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
)

// The M16 audit: the destructive-ambiguity guard, end to end.
//
// Two entities describing one table is the highest-severity mistake this
// generator can be handed. The desired schema built from the narrower of the
// two looks exactly like a schema whose extra columns were deliberately
// removed, so the migration written from it drops them — and the data in them.
// Nothing about the source says which entity was meant to win.
//
// desired.Build refuses, and that refusal is unit-tested. What is tested here is
// the thing that actually protects a database: that the refusal survives the
// whole command. A guard that holds in a package and is bypassed, swallowed or
// downgraded by the time makemigrations has run is a guard that does not exist.
//
// So these assert the three facts an operator depends on: the command fails,
// nothing destructive was written to disk, and the database still has its
// columns and its rows.

// The table the ambiguity is about. It has the things worth losing: a unique
// index, a foreign key, and rows.
const dataLossSchema = `
CREATE TABLE customers (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email text NOT NULL UNIQUE
);
CREATE TABLE products (
	id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sku         text NOT NULL,
	name        text NOT NULL,
	created_at  timestamptz NOT NULL DEFAULT now(),
	customer_id bigint NOT NULL REFERENCES customers(id)
);
CREATE UNIQUE INDEX products_sku_key ON products (sku);
INSERT INTO customers (email) VALUES ('buyer@example.com');
INSERT INTO products (sku, name, customer_id) VALUES ('SKU-1', 'First', 1);
`

// The two entities. The second describes the same table with fewer columns,
// which is what makes the ambiguity destructive rather than merely confusing.
const wideEntity = `
//orm:table products
type Product struct {
	ID         int64     ` + "`orm:\"pk,identity\"`" + `
	SKU        string    ` + "`orm:\"unique\"`" + `
	Name       string
	CreatedAt  time.Time ` + "`orm:\"column:created_at\"`" + `
	CustomerID int64     ` + "`orm:\"column:customer_id\"`" + `
}
`

const narrowEntity = `
//orm:table products
type ProductView struct {
	ID  int64  ` + "`orm:\"pk,identity\"`" + `
	SKU string
}
`

// The columns the narrow entity does not mention. If a migration is ever written
// from it, these are what it drops.
var dataLossColumns = []string{"created_at", "customer_id", "name"}

func TestDataLoss_makemigrationsRefusesAmbiguousTables(t *testing.T) {
	for _, c := range []struct {
		what   string
		layout func(p *project)
	}{
		{
			// One file, both entities: the ordinary mistake.
			"one package, wide entity first",
			func(p *project) { p.Entities(domainFile(wideEntity + narrowEntity)) },
		},
		{
			// Reversed. Whichever the scanner reaches first, the answer is the
			// same refusal — an order-dependent guard would be a guard that
			// depends on a filename.
			"one package, narrow entity first",
			func(p *project) { p.Entities(domainFile(narrowEntity + wideEntity)) },
		},
		{
			// Two files in one package. The scanner reads them in name order, so
			// this puts the narrow one first on disk.
			"one package, two files",
			func(p *project) {
				p.Entities(domainFile(wideEntity))
				writeFile(t, filepath.Join(p.Dir, "domain", "aa_view.go"), domainFile(narrowEntity))
			},
		},
		{
			// Two packages. This is the layout that makes the mistake easy:
			// neither package can see the other's //orm:table directive, so
			// nothing but this check stands between them and a dropped column.
			"two packages",
			func(p *project) {
				p.Entities(domainFile(wideEntity))
				if err := os.MkdirAll(filepath.Join(p.Dir, "reporting"), 0o755); err != nil {
					t.Fatal(err)
				}
				writeFile(t, filepath.Join(p.Dir, "reporting", "entities.go"),
					strings.Replace(domainFile(narrowEntity), "package domain", "package reporting", 1))
				writeFile(t, p.Conf, strings.Replace(readFile(t, p.Conf),
					"packages:\n  - path: ./domain\n    output: same\n",
					"packages:\n  - path: ./domain\n    output: same\n  - path: ./reporting\n    output: same\n", 1))
			},
		},
	} {
		t.Run(c.what, func(t *testing.T) {
			p := newProject(t, domainFile(wideEntity))
			seed(t, p.DSN, dataLossSchema)
			c.layout(p)

			code, stdout, stderr := p.Run("makemigrations", "--name", "ambiguous")
			out := stdout + stderr

			if code == exitClean {
				t.Fatalf("makemigrations succeeded on two entities over one table; "+
					"the migration it wrote would have dropped %s and the rows in them\n%s",
					strings.Join(dataLossColumns, ", "), out)
			}
			// The message has to name both sides and the table. "duplicate
			// table" leaves the reader grepping for which two.
			for _, want := range []string{"Product", "ProductView", "products"} {
				if !strings.Contains(out, want) {
					t.Errorf("the refusal does not mention %q:\n%s", want, out)
				}
			}

			assertNoDestructiveMigration(t, filepath.Join(p.Dir, "migrations"))
			assertTableIntact(t, p.DSN)
		})
	}
}

// assertNoDestructiveMigration fails if anything on disk would drop a column.
//
// The refusal is only worth having if it happens before the file is written. A
// migration left behind by a failed run is one somebody applies later, and by
// then nothing remembers that the command exited non-zero.
func assertNoDestructiveMigration(t *testing.T, dir string) {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return // Nothing was written at all, which is the best outcome.
		}
		t.Fatalf("reading the migrations directory: %v", err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		body := readFile(t, filepath.Join(dir, e.Name()))
		upper := strings.ToUpper(body)
		for _, destructive := range []string{"DROP COLUMN", "DROP TABLE", "DROP CONSTRAINT", "DROP INDEX"} {
			if strings.Contains(upper, destructive) {
				t.Errorf("a refused run left %s containing %s:\n%s", e.Name(), destructive, body)
			}
		}
	}
}

// assertTableIntact fails if the database lost a column or a row.
func assertTableIntact(t *testing.T, dsn string) {
	t.Helper()
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	defer func() { _ = conn.Close(t.Context()) }()

	rows, err := conn.Query(t.Context(),
		`SELECT column_name FROM information_schema.columns
		 WHERE table_schema = 'public' AND table_name = 'products'`)
	if err != nil {
		t.Fatalf("reading the columns: %v", err)
	}
	var have []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatal(err)
		}
		have = append(have, name)
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	sort.Strings(have)
	for _, want := range dataLossColumns {
		if sort.SearchStrings(have, want) >= len(have) || have[sort.SearchStrings(have, want)] != want {
			t.Errorf("the column %q is gone; the database has %v", want, have)
		}
	}

	var n int64
	if err := conn.QueryRow(t.Context(), `SELECT count(*) FROM products`).Scan(&n); err != nil {
		t.Fatalf("counting: %v", err)
	}
	if n != 1 {
		t.Errorf("products has %d rows, want 1", n)
	}

	// The unique index and the foreign key are what a careless migration takes
	// with the columns.
	var idx, fk int64
	if err := conn.QueryRow(t.Context(),
		`SELECT count(*) FROM pg_indexes WHERE tablename = 'products' AND indexname = 'products_sku_key'`).Scan(&idx); err != nil {
		t.Fatal(err)
	}
	if idx != 1 {
		t.Error("the unique index on products.sku is gone")
	}
	if err := conn.QueryRow(t.Context(),
		`SELECT count(*) FROM pg_constraint WHERE conrelid = 'products'::regclass AND contype = 'f'`).Scan(&fk); err != nil {
		t.Fatal(err)
	}
	if fk != 1 {
		t.Error("the foreign key on products.customer_id is gone")
	}
}

func domainFile(body string) string {
	return "package domain\n\nimport \"time\"\n\nvar _ = time.Now\n" + body
}

func seed(t *testing.T, dsn, ddl string) {
	t.Helper()
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	defer func() { _ = conn.Close(t.Context()) }()
	if _, err := conn.Exec(t.Context(), ddl); err != nil {
		t.Fatalf("seeding: %v", err)
	}
}
