package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Scenario A — a new project, from nothing to a proven mapping.
//
// This is the workflow the README promises, run end to end against a real
// server: declare the models, write the migration, read the SQL it would run,
// run it, check the four states agree, generate. Nothing is stubbed and nothing
// is asserted about intermediate representations — what is asserted is that the
// commands compose.
func TestScenarioA_newProject(t *testing.T) {
	p := newProject(t, blogEntities)

	// makemigrations, from an empty history.
	out := p.MustRun("makemigrations", "--name", "initial")
	contains(t, out, "Migration 0001_initial", "the summary")
	contains(t, out, "enum public.post_status", "the summary")
	contains(t, out, "posts_feed_idx", "the summary")
	contains(t, out, "wrote migrations/0001_initial.json", "the summary")
	if files := p.Migrations(); len(files) != 1 || files[0] != "0001_initial.json" {
		t.Fatalf("the migrations directory holds %v", files)
	}

	// Running it again finds nothing, which is the property that makes the
	// command safe to run out of habit.
	contains(t, p.MustRun("makemigrations"), "No schema changes detected.", "a second run")

	// The SQL is reviewable before anything runs.
	sql := p.MustRun("sqlmigrate", "0001_initial")
	contains(t, sql, "CREATE TYPE \"public\".\"post_status\" AS ENUM ('draft', 'published', 'archived')", "the SQL")
	contains(t, sql, "CREATE TABLE \"public\".\"users\"", "the SQL")
	contains(t, sql, "GENERATED BY DEFAULT AS IDENTITY", "the SQL")
	contains(t, sql, "REFERENCES", "the SQL")
	contains(t, sql, "runs in one transaction", "the SQL header")

	// The plan says what would happen, and changes nothing.
	plan := p.MustRun("migrate", "--plan")
	contains(t, plan, "0001_initial [atomic]", "the plan")
	contains(t, plan, "current: nothing applied", "the plan")
	if tables := p.Query(`SELECT table_name::text FROM information_schema.tables WHERE table_schema = 'public'`); len(tables) != 0 {
		t.Errorf("--plan is read-only and created %v", tables)
	}

	// migrate.
	applied := p.MustRun("migrate")
	contains(t, applied, "Applying 0001_initial ... OK", "the run")
	contains(t, applied, "1 migration(s) applied.", "the run")

	// showmigrations.
	contains(t, p.MustRun("showmigrations"), "[X] 0001_initial", "the listing")

	// check, before anything is generated, reports the states apart. Having
	// never generated is reported and does not fail, because the workflow this
	// tool recommends runs check before the first generate.
	out = p.MustRun("check")
	contains(t, out, "Models       match the latest migration", "the check")
	contains(t, out, "Migrations   1 applied, none pending", "the check")
	contains(t, out, "Database     fully migrated, no drift", "the check")
	contains(t, out, "Mapping      valid", "the check")
	contains(t, out, "Generated    never written", "the check")

	// generate, and then everything agrees.
	contains(t, p.MustRun("generate"), "wrote", "generation")
	out = p.MustRun("check")
	contains(t, out, "Generated    current", "the check after generating")
	contains(t, out, "Database     fully migrated, no drift", "the check after generating")

	// The database really has what the models asked for, including the parts a
	// column-only model could not express.
	idx := p.Query(`SELECT indexdef FROM pg_indexes WHERE indexname = 'posts_feed_idx'`)
	if len(idx) != 1 {
		t.Fatalf("posts_feed_idx = %v", idx)
	}
	for _, want := range []string{"created_at DESC", "INCLUDE (title)", "WHERE"} {
		contains(t, idx[0], want, "the feed index")
	}
	labels := p.Query(`SELECT unnest(enum_range(NULL::public.post_status))::text`)
	if strings.Join(labels, ",") != "draft,published,archived" {
		t.Errorf("enum labels = %v", labels)
	}
}

// Scenario B — evolving a schema, including a rename.
//
// The rename is the part that cannot be computed. The engine reports a
// candidate, the command asks, and the answer decides whether the column's data
// survives — so the test answers yes and then checks the data is still there,
// which is the only assertion that distinguishes a rename from a drop and an
// add that happens to leave the same shape behind.
func TestScenarioB_renameAndAdd(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))

	p.MustRun("makemigrations", "--name", "initial")
	p.MustRun("migrate")
	p.SQL(`INSERT INTO users (email) VALUES ('someone@example.com')`)

	// The model renames the column and adds another.
	p.Entities(usersEntities("EmailAddress string `orm:\"unique\"`\n\tStatus       string `orm:\"default:'pending'\"`"))

	// Without an answer there is nobody to ask, and the command says so rather
	// than guessing.
	code, _, stderr := p.Run("makemigrations", "--no-input")
	if code != exitFailure {
		t.Errorf("--no-input exit = %d, want %d", code, exitFailure)
	}
	contains(t, stderr, "could be renames or could be a drop and an add", "the refusal")
	contains(t, stderr, "--rename users.email=email_address", "the refusal")
	if files := p.Migrations(); len(files) != 1 {
		t.Fatalf("a refused makemigrations wrote %v", files)
	}

	// Answering the question produces a rename.
	code, out, stderr := p.RunInput("y\n", "makemigrations", "--name", "rename_email_add_status")
	if code != exitClean {
		t.Fatalf("makemigrations: exit %d\n%s%s", code, out, stderr)
	}
	contains(t, out, "Did you rename users.email to email_address?", "the prompt")
	contains(t, out, "~ rename email -> email_address", "the summary")
	contains(t, out, "+ status text", "the summary")
	absent(t, out, "drop column email", "the summary")

	p.MustRun("migrate")

	// The data survived, which is what a rename means.
	got := p.Query(`SELECT email_address FROM users`)
	if len(got) != 1 || got[0] != "someone@example.com" {
		t.Errorf("after the rename the rows are %v", got)
	}
	contains(t, p.MustRun("makemigrations"), "No schema changes detected.", "the follow-up")
}

// Scenario B, the other answer: saying no is a drop and an add, and says so.
func TestScenarioB_renameDeclined(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))
	p.MustRun("makemigrations", "--name", "initial")

	p.Entities(usersEntities("EmailAddress string `orm:\"unique\"`"))
	_, out, _ := p.RunInput("n\n", "makemigrations", "--name", "email_address")
	contains(t, out, "- drop column email", "the summary")
	contains(t, out, "+ email_address text", "the summary")
	contains(t, out, "W202", "the warnings")
}

// Scenario B in CI: --check reports that a migration is needed, writes nothing,
// and never asks anything.
func TestScenarioB_check(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))

	code, out, _ := p.Run("makemigrations", "--check")
	if code != exitFindings {
		t.Errorf("--check exit = %d, want %d when a migration is needed", code, exitFindings)
	}
	contains(t, out, "The models describe schema changes no migration does.", "the report")
	contains(t, out, "orm makemigrations", "the report")
	if files := p.Migrations(); len(files) != 0 {
		t.Errorf("--check wrote %v", files)
	}

	p.MustRun("makemigrations", "--name", "initial")
	code, out, _ = p.Run("makemigrations", "--check")
	if code != exitClean {
		t.Errorf("--check exit = %d, want %d when nothing is needed", code, exitClean)
	}
	contains(t, out, "No schema changes detected.", "the report")
}

// --dry-run shows the migration and writes nothing, and shows the same thing
// every time it is asked.
func TestMakemigrations_dryRun(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))

	first := p.MustRun("makemigrations", "--dry-run", "--name", "initial")
	contains(t, first, "Would write migration 0001_initial", "the dry run")
	contains(t, first, "was not written", "the dry run")
	if files := p.Migrations(); len(files) != 0 {
		t.Fatalf("--dry-run wrote %v", files)
	}
	for range 3 {
		if again := p.MustRun("makemigrations", "--dry-run", "--name", "initial"); again != first {
			t.Fatalf("two dry runs over one state differ:\n%s\n---\n%s", first, again)
		}
	}
	contains(t, p.MustRun("makemigrations", "--dry-run", "--sql", "--name", "initial"), "CREATE TABLE", "--sql")
}

// usersEntities builds a one-table model with the given extra fields.
func usersEntities(fields string) string {
	return `package domain

//orm:table users
type User struct {
	ID int64 ` + "`orm:\"pk,identity\"`" + `
	` + fields + `
}
`
}

// A machine-readable report stays machine-readable: the state block is for a
// person and must not turn the document into something no parser accepts.
func TestCheck_jsonStaysValid(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))
	p.MustRun("makemigrations", "--name", "initial")
	p.MustRun("migrate")

	_, stdout, stderr := p.Run("check", "--format", "json")
	var doc any
	if err := json.Unmarshal([]byte(stdout), &doc); err != nil {
		t.Errorf("--format json produced something that is not JSON: %v\n%s", err, stdout)
	}
	contains(t, stderr, "Models       match the latest migration", "the state block")
}

// An empty migration is the affordance for everything the schema diff cannot
// see: a backfill, a seed, a correction. Without it the only way to run data
// SQL through the migration engine was to hand-write an artifact from nothing,
// inventing the ID, the dependency and the JSON shape — which is a lot to ask
// for an INSERT.
func TestMakemigrations_empty(t *testing.T) {
	p := newProject(t, usersEntities("Email string `orm:\"unique\"`"))
	p.MustRun("makemigrations", "--name", "initial")

	// The models have not moved, so an ordinary run has nothing to write.
	contains(t, p.MustRun("makemigrations"), "No schema changes detected", "an unchanged model")

	// --empty writes one anyway, because it was asked for rather than derived.
	out := p.MustRun("makemigrations", "--empty", "--name", "seed_tags")
	contains(t, out, "0002_seed_tags", "--empty")
	contains(t, out, "Fill in Up", "--empty")

	files := p.Migrations()
	if len(files) != 2 {
		t.Fatalf("migrations = %v, want the initial one and the empty one", files)
	}

	body, err := os.ReadFile(filepath.Join(p.Dir, "migrations", "0002_seed_tags.json"))
	if err != nil {
		t.Fatalf("reading the empty migration: %v", err)
	}
	var doc struct {
		DependsOn  []string `json:"dependsOn"`
		Operations []struct {
			Op   string          `json:"op"`
			Args json.RawMessage `json:"args"`
		} `json:"operations"`
	}
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatalf("the empty migration is not valid JSON: %v\n%s", err, body)
	}
	if len(doc.Operations) != 1 || doc.Operations[0].Op != "raw_sql" {
		t.Errorf("operations = %+v, want one raw_sql to fill in", doc.Operations)
	}
	if len(doc.DependsOn) != 1 || doc.DependsOn[0] != "0001_initial" {
		t.Errorf("depends_on = %v, want the migration before it", doc.DependsOn)
	}

	// And it does not disturb the diff: the models still match.
	contains(t, p.MustRun("makemigrations"), "No schema changes detected", "after an empty migration")

	// Without a name it is called what it is for, not "auto" — nothing was
	// derived, so a derived-sounding name would be a lie.
	contains(t, p.MustRun("makemigrations", "--empty"), "0003_data", "an unnamed empty migration")
}

// The referential action reaches the database, which is the only place it
// counts. Everything before this is a claim about a string.
func TestMakemigrations_referentialActions(t *testing.T) {
	p := newProject(t, `package domain

import "github.com/AlexAli29/orm"

//orm:table users
type User struct {
	ID int64 `+"`orm:\"pk,identity\"`"+`
}

//orm:table posts
type Post struct {
	ID       int64 `+"`orm:\"pk,identity\"`"+`
	AuthorID int64

	Author orm.One[User] `+"`orm:\"side:local,ondelete:cascade\"`"+`
}
`)
	p.MustRun("makemigrations", "--name", "initial")
	p.MustRun("migrate")

	got := p.Query(`SELECT confdeltype::text FROM pg_constraint WHERE conname = 'posts_author_id_fkey'`)
	if len(got) != 1 || got[0] != "c" {
		t.Fatalf("confdeltype = %v, want [c] for ON DELETE CASCADE", got)
	}

	// And the mapping is clean afterwards: the declaration and the database
	// agree about the action, so nothing plans to change it back.
	contains(t, p.MustRun("makemigrations"), "No schema changes detected", "after a cascade was created")
}
