package main

import (
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
)

// M16.5 F.3: every view check is reachable through the command a user runs.
//
// These do not call reconciliation helpers. They build a managed project, apply
// a view the way a migration does, run `orm check`, and read what it printed.
// A comparison that is correct internally and unreachable from the CLI is a
// comparison nobody benefits from, so the test that proves the wiring has to go
// through the wiring.

const viewCheckProject = `package domain

//orm:table public.users
type User struct {
	ID     int64 ` + "`orm:\"pk,identity\"`" + `
	Email  string
	Active bool
}

//orm:table public.accounts
type Account struct {
	ID     int64 ` + "`orm:\"pk,identity\"`" + `
	UserID int64 ` + "`orm:\"column:user_id\"`" + `
}

//orm:view public.active_users
//orm:definition ` + "`SELECT id, email FROM users WHERE active`" + `
//orm:depends-on public.users
type ActiveUser struct {
	ID    int64
	Email string
}

//orm:materialized-view public.totals
//orm:definition ` + "`SELECT id AS user_id, email FROM users`" + `
//orm:depends-on public.users
//orm:index totals_user_id_key (UserID) unique
type Total struct {
	UserID int64 ` + "`orm:\"column:user_id\"`" + `
	Email  string
}
`

// managedViewProject builds the database by hand — the planner does not exist — and
// records provenance the way a migration would.
func managedViewProject(t *testing.T) *project {
	t.Helper()
	p := newProject(t, viewCheckProject)
	runSQL(t, p, `
		CREATE TABLE users    (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL, active boolean NOT NULL);
		CREATE TABLE accounts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL);
		CREATE VIEW active_users AS SELECT id, email FROM users WHERE active;
		CREATE MATERIALIZED VIEW totals AS SELECT id AS user_id, email FROM users WITH DATA;
		CREATE UNIQUE INDEX totals_user_id_key ON totals (user_id);
		CREATE TABLE public.orm_schema_views (
			schema_name text NOT NULL, relation_name text NOT NULL, kind text NOT NULL,
			source_identity text NOT NULL, canonical text NOT NULL,
			recorded_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (schema_name, relation_name));
		INSERT INTO public.orm_schema_views (schema_name, relation_name, kind, source_identity, canonical)
		SELECT 'public', 'active_users', 'view', 'v1:x', pg_get_viewdef('public.active_users'::regclass, true);
		INSERT INTO public.orm_schema_views (schema_name, relation_name, kind, source_identity, canonical)
		SELECT 'public', 'totals', 'materialized view', 'v1:y', pg_get_viewdef('public.totals'::regclass, true);
	`)
	return p
}

func runSQL(t *testing.T, p *project, sql string) {
	t.Helper()
	conn, err := pgx.Connect(t.Context(), p.DSN)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	defer func() { _ = conn.Close(t.Context()) }()
	if _, err := conn.Exec(t.Context(), sql); err != nil {
		t.Fatalf("running setup SQL: %v", err)
	}
}

// The baseline must be clean, or every test below proves nothing.
func TestViewCheck_cleanProject(t *testing.T) {
	p := managedViewProject(t)
	// The reconciliation result is what these tests are about. The overall exit
	// code also carries migration-state drift, and this project's tables were
	// created by hand because the view planner does not exist yet — so the
	// command reports schema changes no migration describes, correctly, and
	// that is a different signal from the one under test.
	_, stdout, stderr := p.Run("check")
	out := stdout + stderr
	if !strings.Contains(out, "reconciliation clean") {
		t.Fatalf("a project matching its database does not reconcile clean:\n%s", out)
	}
}

// Each drift, introduced one at a time, must reach the command's output.
func TestViewCheck_driftReachesTheCLI(t *testing.T) {
	for _, c := range []struct {
		what string
		sql  string
		code string
	}{
		{
			"a relation reading something no declaration mentions",
			`CREATE OR REPLACE VIEW active_users AS
			   SELECT u.id, u.email FROM users u LEFT JOIN accounts a ON a.user_id = u.id WHERE u.active`,
			"E033",
		},
		{
			"a manual body edit with the same columns",
			`CREATE OR REPLACE VIEW active_users AS SELECT id, email FROM users WHERE NOT active`,
			"E032",
		},
		{
			"a security option managed mode cannot express",
			`ALTER VIEW active_users SET (security_barrier = true)`,
			"W035",
		},
		{"a missing materialized-view index", `DROP INDEX totals_user_id_key`, "E036"},
		{
			"a unique index that stopped being unique",
			`DROP INDEX totals_user_id_key; CREATE INDEX totals_user_id_key ON totals (user_id)`,
			"E036",
		},
		{
			"an index whose key order changed",
			`DROP INDEX totals_user_id_key; CREATE UNIQUE INDEX totals_user_id_key ON totals (email, user_id)`,
			"E036",
		},
		{
			"an index that became partial",
			`DROP INDEX totals_user_id_key; CREATE UNIQUE INDEX totals_user_id_key ON totals (user_id) WHERE user_id > 0`,
			"E036",
		},
		{
			"an index that became an expression",
			`DROP INDEX totals_user_id_key; CREATE UNIQUE INDEX totals_user_id_key ON totals (lower(email))`,
			"E036",
		},
		{
			"an index that gained an INCLUDE",
			`DROP INDEX totals_user_id_key; CREATE UNIQUE INDEX totals_user_id_key ON totals (user_id) INCLUDE (email)`,
			"E036",
		},
		{
			"an index whose operator class changed",
			`DROP INDEX totals_user_id_key; CREATE UNIQUE INDEX totals_user_id_key ON totals (email text_pattern_ops)`,
			"E036",
		},
		{
			"an index whose method changed",
			`DROP INDEX totals_user_id_key; CREATE INDEX totals_user_id_key ON totals USING hash (user_id)`,
			"E036",
		},
		{
			"a relation that is now the wrong kind",
			`DROP VIEW active_users; CREATE TABLE active_users (id bigint, email text)`,
			"E030",
		},
		{
			"a relation with no recorded provenance",
			`DELETE FROM public.orm_schema_views WHERE relation_name = 'active_users'`,
			"W031",
		},
	} {
		t.Run(c.what, func(t *testing.T) {
			p := managedViewProject(t)
			if _, base, baseErr := p.Run("check"); !strings.Contains(base+baseErr, "reconciliation clean") {
				t.Fatalf("the baseline does not reconcile clean:\n%s%s", base, baseErr)
			}
			runSQL(t, p, c.sql)

			_, stdout, stderr := p.Run("check")
			out := stdout + stderr
			if strings.Contains(out, "reconciliation clean") {
				t.Fatalf("%s left reconciliation green. An internal comparison nobody can reach "+
					"through the command is a comparison nobody benefits from:\n%s", c.what, out)
			}
			if !strings.Contains(out, c.code) {
				t.Errorf("%s did not produce %s:\n%s", c.what, c.code, out)
			}
			// One finding per fact: wiring several passes must not report the
			// same thing twice.
			if n := strings.Count(out, c.code+":"); n > 1 {
				t.Errorf("%s produced %s %d times:\n%s", c.what, c.code, n, out)
			}
		})
	}
}

// A declared dependency the relation does not have.
func TestViewCheck_staleDeclaredDependencyReachesTheCLI(t *testing.T) {
	p := newProject(t, strings.Replace(viewCheckProject,
		"//orm:depends-on public.users\ntype ActiveUser",
		"//orm:depends-on public.users, public.accounts\ntype ActiveUser", 1))
	runSQL(t, p, `
		CREATE TABLE users    (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL, active boolean NOT NULL);
		CREATE TABLE accounts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL);
		CREATE VIEW active_users AS SELECT id, email FROM users WHERE active;
		CREATE MATERIALIZED VIEW totals AS SELECT id AS user_id, email FROM users WITH DATA;
		CREATE UNIQUE INDEX totals_user_id_key ON totals (user_id);
	`)
	_, stdout, stderr := p.Run("check")
	out := stdout + stderr
	if strings.Contains(out, "reconciliation clean") {
		t.Fatalf("a declared dependency the view does not have left reconciliation green:\n%s", out)
	}
	if !strings.Contains(out, "E034") {
		t.Errorf("no E034:\n%s", out)
	}
}

// Wiring the view checks must not have made the check write anything, and
// makemigrations must still refuse.
func TestViewCheck_stillReadOnlyAndStillRefusesToPlan(t *testing.T) {
	p := managedViewProject(t)
	code, stdout, stderr := p.Run("makemigrations", "--name", "x")
	out := stdout + stderr
	if code == exitClean {
		t.Fatalf("makemigrations planned a view:\n%s", out)
	}
	// The reason moved on: materialized views are planned now, and what stops
	// this project is that the relations already exist in the database and no
	// migration of this project created them. What must not move is that the
	// command refuses and writes nothing.
	if !strings.Contains(out, "already exists in the database") {
		t.Errorf("the refusal changed:\n%s", out)
	}
	for _, ddl := range []string{"CREATE VIEW", "CREATE MATERIALIZED VIEW", "DROP VIEW"} {
		if strings.Contains(out, ddl) {
			t.Errorf("makemigrations emitted %s:\n%s", ddl, out)
		}
	}
}
