package uuidcompat_test

import (
	"reflect"
	"testing"

	"example.com/uuidcompat/domain"
	"github.com/AlexAli29/orm"
	"github.com/google/uuid"
)

// The uuid chain: table, then a view over it, then a materialized view over the
// view.
//
//	users.id ──▶ user_orders.user_id ──▶ user_summaries.user_id
//
// Each arrow is a place the type could be lost, and each layer is generated by
// a different path: a table's columns come from pg_attribute on a table, a
// view's from pg_attribute on a view whose definition the server reconstructed,
// and a materialized view's from a relation that also carries indexes and a
// refresh. The claim is that the Go type at the far end is the same Go type as
// at the near end — not a compatible one, the same one.

// The declared Go type is uuid.UUID at every layer, and this asks the reflect
// package rather than trusting that the file above compiled.
func TestUUID_goTypeIsIdenticalThroughTheChain(t *testing.T) {
	want := reflect.TypeFor[uuid.UUID]()

	layers := []struct {
		name string
		got  reflect.Type
	}{
		{"users.id", reflect.TypeOf(domain.User{}.ID)},
		{"user_orders.user_id", reflect.TypeOf(domain.UserOrder{}.UserID)},
		{"user_summaries.user_id", reflect.TypeOf(domain.UserSummary{}.UserID)},
	}
	for _, l := range layers {
		if l.got != want {
			t.Errorf("%s is %v, want %v", l.name, l.got, want)
		}
		// Named types that merely have the same underlying representation are
		// not the same type, and a mapping that produced one would still scan.
		if l.got.PkgPath() != want.PkgPath() {
			t.Errorf("%s comes from %q, want %q", l.name, l.got.PkgPath(), want.PkgPath())
		}
	}
}

// PostgreSQL's account of the same three columns.
func TestUUID_catalogTypeIsUUIDThroughTheChain(t *testing.T) {
	pool, _ := open(t)

	for _, c := range []struct{ rel, col string }{
		{"users", "id"},
		{"user_orders", "user_id"},
		{"user_summaries", "user_id"},
	} {
		var got string
		err := pool.QueryRow(t.Context(),
			`SELECT format_type(a.atttypid, a.atttypmod)
			   FROM pg_attribute a
			  WHERE a.attrelid = ('public.'||$1)::regclass AND a.attname = $2`,
			c.rel, c.col).Scan(&got)
		if err != nil {
			t.Fatalf("reading %s.%s: %v", c.rel, c.col, err)
		}
		if got != "uuid" {
			t.Errorf("%s.%s is %s, want uuid: a view or a materialized view must not "+
				"widen the type of the column it republishes", c.rel, c.col, got)
		}
	}
}

// The value written into the table is the value read out of all three layers,
// and each layer answers a typed uuid predicate.
func TestUUID_valueAndPredicateSurviveTheChain(t *testing.T) {
	pool, db := open(t)
	reset(t, pool)

	userID, orderID := uuid.New(), uuid.New()
	if _, err := db.Users.Insert(t.Context(), domain.User{
		ID: userID, Email: "chain@example.com", Tags: []uuid.UUID{},
	}); err != nil {
		t.Fatalf("inserting user: %v", err)
	}
	if _, err := db.Orders.Insert(t.Context(), domain.Order{
		ID: orderID, UserID: userID, Label: "chain",
	}); err != nil {
		t.Fatalf("inserting order: %v", err)
	}
	if err := db.UserSummaries.Refresh(t.Context()); err != nil {
		t.Fatalf("refreshing: %v", err)
	}

	// Layer 1: the table.
	u, err := db.Users.Query().Where(domain.Users.ID.Eq(userID)).One(t.Context())
	if err != nil {
		t.Fatalf("reading the table: %v", err)
	}
	if u.ID != userID {
		t.Errorf("the table read %v, want %v", u.ID, userID)
	}

	// Layer 2: the view. Its uuid column is nullable in the descriptor because
	// a view's output nullability is not provable, so the predicate is the
	// nullable column's Eq and the value is still a bare uuid.UUID.
	vs, err := db.UserOrders.Query().Where(domain.UserOrders.UserID.Eq(userID)).All(t.Context())
	if err != nil {
		t.Fatalf("reading the view: %v", err)
	}
	if len(vs) != 1 || vs[0].UserID != userID || vs[0].OrderID != orderID {
		t.Fatalf("the view read %+v, want one row carrying %v and %v", vs, userID, orderID)
	}

	// Layer 3: the materialized view.
	ms, err := db.UserSummaries.Query().Where(domain.UserSummaries.UserID.Eq(userID)).All(t.Context())
	if err != nil {
		t.Fatalf("reading the materialized view: %v", err)
	}
	if len(ms) != 1 || ms[0].UserID != userID {
		t.Fatalf("the materialized view read %+v, want one row carrying %v", ms, userID)
	}
}

// Ordering by the uuid column works at every layer, and it is PostgreSQL's
// ordering rather than Go's.
func TestUUID_orderingWorksAtEveryLayer(t *testing.T) {
	pool, db := open(t)
	reset(t, pool)

	for i := range 4 {
		id := uuid.New()
		if _, err := db.Users.Insert(t.Context(), domain.User{
			ID: id, Email: string(rune('a'+i)) + "@example.com", Tags: []uuid.UUID{},
		}); err != nil {
			t.Fatalf("inserting user: %v", err)
		}
		if _, err := db.Orders.Insert(t.Context(), domain.Order{
			ID: uuid.New(), UserID: id, Label: "x",
		}); err != nil {
			t.Fatalf("inserting order: %v", err)
		}
	}
	if err := db.UserSummaries.Refresh(t.Context()); err != nil {
		t.Fatalf("refreshing: %v", err)
	}

	us, err := db.Users.Query().OrderBy(domain.Users.ID.Asc()).All(t.Context())
	if err != nil {
		t.Fatalf("ordering the table: %v", err)
	}
	vs, err := db.UserOrders.Query().OrderBy(domain.UserOrders.UserID.Asc()).All(t.Context())
	if err != nil {
		t.Fatalf("ordering the view: %v", err)
	}
	ms, err := db.UserSummaries.Query().OrderBy(domain.UserSummaries.UserID.Asc()).All(t.Context())
	if err != nil {
		t.Fatalf("ordering the materialized view: %v", err)
	}
	tableIDs := mapIDs(us, func(u domain.User) uuid.UUID { return u.ID })
	viewIDs := mapIDs(vs, func(v domain.UserOrder) uuid.UUID { return v.UserID })
	mvIDs := mapIDs(ms, func(m domain.UserSummary) uuid.UUID { return m.UserID })

	// All three layers order the same set of uuids the same way. If any layer
	// compared a rendered spelling rather than the uuid, the orders would part
	// company on some run rather than every run — so the check is the agreement
	// between layers, not a hardcoded order.
	if len(tableIDs) != 4 || len(viewIDs) != 4 || len(mvIDs) != 4 {
		t.Fatalf("row counts differ across layers: %d, %d, %d",
			len(tableIDs), len(viewIDs), len(mvIDs))
	}
	for i := range tableIDs {
		if tableIDs[i] != viewIDs[i] || tableIDs[i] != mvIDs[i] {
			t.Errorf("position %d is %v in the table, %v in the view and %v in the "+
				"materialized view", i, tableIDs[i], viewIDs[i], mvIDs[i])
		}
	}
}

// Refresh runs against the materialized view at the end of the chain, in both
// forms, and the concurrent one uses the unique uuid index.
func TestUUID_refreshAtTheEndOfTheChain(t *testing.T) {
	pool, db := open(t)
	reset(t, pool)

	id := uuid.New()
	if _, err := db.Users.Insert(t.Context(), domain.User{
		ID: id, Email: "refresh@example.com", Tags: []uuid.UUID{},
	}); err != nil {
		t.Fatalf("inserting user: %v", err)
	}
	if _, err := db.Orders.Insert(t.Context(), domain.Order{
		ID: uuid.New(), UserID: id, Label: "refresh",
	}); err != nil {
		t.Fatalf("inserting order: %v", err)
	}

	if err := db.UserSummaries.Refresh(t.Context()); err != nil {
		t.Fatalf("refreshing: %v", err)
	}
	// Concurrently needs a unique index over a non-partial set of plain
	// columns, and the only one here is over a uuid.
	if err := db.UserSummaries.Refresh(t.Context(), orm.Concurrently()); err != nil {
		t.Fatalf("refreshing concurrently: %v", err)
	}

	rows, err := db.UserSummaries.Query().All(t.Context())
	if err != nil {
		t.Fatalf("reading: %v", err)
	}
	if len(rows) != 1 || rows[0].UserID != id {
		t.Fatalf("after a concurrent refresh the view holds %+v, want one row for %v", rows, id)
	}
}

func mapIDs[E any](es []E, f func(E) uuid.UUID) []uuid.UUID {
	out := make([]uuid.UUID, 0, len(es))
	for _, e := range es {
		out = append(out, f(e))
	}
	return out
}
