package gendemo_test

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/AlexAli29/orm"
	"github.com/AlexAli29/orm/internal/gendemo"
	"github.com/AlexAli29/orm/internal/testdb"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// The M10 audit.
//
// These are the tests that try to break the projection, aggregate and write
// expression layers rather than to demonstrate them. The three things they are
// looking for, in order: a NULL that became a Go zero value, a type this
// package claims that PostgreSQL does not agree with, and a mutation that
// touched rows the caller did not describe.

// ------------------------------------------------ PostgreSQL is the authority

// Every result type M10 states statically is checked against pg_typeof.
//
// A table of promotions written from memory is a table of beliefs. This asks
// the server what each expression actually returns, so a wrong entry fails here
// rather than as a scan error in somebody's application.
func TestAudit_expressionTypesMatchPostgres(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, `
		CREATE TABLE nums (
		    id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		    a2  smallint NOT NULL,
		    a4  integer NOT NULL,
		    a8  bigint NOT NULL,
		    f4  real NOT NULL,
		    f8  double precision NOT NULL,
		    n   numeric NOT NULL,
		    ts  timestamptz NOT NULL,
		    txt text NOT NULL
		);
		INSERT INTO nums (a2, a4, a8, f4, f8, n, ts, txt) VALUES
		  (1, 1, 1, 1.5, 1.5, 1.5, '2024-01-01T00:00:00Z', 'a'),
		  (2, 2, 2, 2.5, 2.5, 2.5, '2024-02-01T00:00:00Z', 'b');`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })

	typeOf := func(sqlExpr string) string {
		t.Helper()
		var name string
		if err := conn.QueryRow(t.Context(),
			"SELECT pg_typeof("+sqlExpr+")::text FROM nums LIMIT 1").Scan(&name); err != nil {
			t.Fatalf("pg_typeof(%s): %v", sqlExpr, err)
		}
		return name
	}
	grouped := func(sqlExpr string) string {
		t.Helper()
		var name string
		if err := conn.QueryRow(t.Context(),
			"SELECT pg_typeof("+sqlExpr+")::text FROM nums").Scan(&name); err != nil {
			t.Fatalf("pg_typeof(%s): %v", sqlExpr, err)
		}
		return name
	}

	// What this package claims, expression by expression. The Go type is the
	// one the constructor's signature produces; the SQL type is what the
	// server must agree it is.
	for _, tt := range []struct {
		what   string
		sql    string
		wantPG string
		// aggregate marks the ones that need no GROUP BY and collapse the rows.
		aggregate bool
	}{
		{"sum(smallint)", "sum(a2)", "bigint", true},
		{"sum(integer)", "sum(a4)", "bigint", true},
		{"sum(bigint)", "sum(a8)", "numeric", true},
		{"sum(real)", "sum(f4)", "real", true},
		{"sum(double precision)", "sum(f8)", "double precision", true},
		{"sum(numeric)", "sum(n)", "numeric", true},
		{"avg(smallint)", "avg(a2)", "numeric", true},
		{"avg(integer)", "avg(a4)", "numeric", true},
		{"avg(bigint)", "avg(a8)", "numeric", true},
		{"avg(real)", "avg(f4)", "double precision", true},
		{"avg(double precision)", "avg(f8)", "double precision", true},
		{"avg(numeric)", "avg(n)", "numeric", true},
		{"count(*)", "count(*)", "bigint", true},
		{"count(expr)", "count(a4)", "bigint", true},
		{"min(integer)", "min(a4)", "integer", true},
		{"max(integer)", "max(a4)", "integer", true},
		{"min(timestamptz)", "min(ts)", "timestamp with time zone", true},
		{"max(text)", "max(txt)", "text", true},
		// The arithmetic this package builds, which is always between two
		// values of one type.
		{"smallint + smallint", "a2 + a2", "smallint", false},
		{"integer + integer", "a4 + a4", "integer", false},
		{"bigint + bigint", "a8 + a8", "bigint", false},
		{"real + real", "f4 + f4", "real", false},
		{"double + double", "f8 + f8", "double precision", false},
		{"numeric + numeric", "n + n", "numeric", false},
		{"integer / integer", "a4 / a4", "integer", false},
		{"smallint * smallint", "a2 * a2", "smallint", false},
	} {
		got := typeOf(tt.sql)
		if tt.aggregate {
			got = grouped(tt.sql)
		}
		if got != tt.wantPG {
			t.Errorf("%s: PostgreSQL returns %s, this package is written for %s",
				tt.what, got, tt.wantPG)
		}
	}
}

// ----------------------------------------------------------- NULL, everywhere

// nullDB has one row of values and one row of NULLs, where every value is the
// Go zero of its type. That is the shape that catches a NULL collapsing: if
// nullability were lost, the two rows would be indistinguishable.
func nullDB(t *testing.T) (*gendemo.DB, *pgx.Conn) {
	t.Helper()
	dsn := testdb.Create(t, schema(t)+`
		INSERT INTO users (id, email, age, active, state, nickname, score, tags, settings,
		                   avatar, manager_id, bio, visits, deleted_at, created_at) VALUES
		  (1, 'zero@example.com',  0, false, 'pending', '',   0,    '{}', '{}', '\x'::bytea, NULL, '',   0,    '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
		  (2, 'nulls@example.com', 0, false, 'pending', NULL, NULL, '{}', '{}', NULL,        NULL, NULL, NULL, NULL,                   '2024-01-01T00:00:00Z');
		SELECT setval(pg_get_serial_sequence('users','id'), 1000);`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })
	return gendemo.New(conn), conn
}

// A NULL never arrives as a zero value, for any nullable category the fixture
// maps — and the row beside it holds exactly that zero value, so a collapse
// would make the two rows equal.
func TestAudit_nullNeverBecomesZero(t *testing.T) {
	testdb.AdminDSN(t)
	db, conn := nullDB(t)

	type row struct {
		ID       int64
		Nickname *string
		Score    *float64
		Avatar   *[]byte
		Visits   *int64
		Deleted  *time.Time
	}
	shape := orm.Project6(
		gendemo.Users.ID, gendemo.Users.Nickname, gendemo.Users.Score,
		gendemo.Users.Avatar, gendemo.Users.Visits, gendemo.Users.DeletedAt,
		func(id int64, nick *string, score *float64, avatar *[]byte, visits *int64, del *time.Time) row {
			return row{id, nick, score, avatar, visits, del}
		},
	)
	got, err := orm.Select(db.Users, shape).OrderBy(gendemo.Users.ID.Asc()).All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("got %d rows", len(got))
	}

	// Row 1 holds the zero values, and every one of them is present.
	zero := got[0]
	if zero.Nickname == nil || *zero.Nickname != "" {
		t.Errorf("an empty string came back as %v", zero.Nickname)
	}
	if zero.Score == nil || *zero.Score != 0 {
		t.Errorf("a zero float came back as %v", zero.Score)
	}
	if zero.Avatar == nil || len(*zero.Avatar) != 0 {
		t.Errorf("an empty bytea came back as %v", zero.Avatar)
	}
	if zero.Visits == nil || *zero.Visits != 0 {
		t.Errorf("a zero bigint came back as %v", zero.Visits)
	}
	if zero.Deleted == nil {
		t.Error("a stored timestamp came back as NULL")
	}

	// Row 2 holds NULLs, and every one of them is absent.
	nulls := got[1]
	for name, present := range map[string]bool{
		"nickname": nulls.Nickname != nil, "score": nulls.Score != nil,
		"avatar": nulls.Avatar != nil, "visits": nulls.Visits != nil,
		"deleted_at": nulls.Deleted != nil,
	} {
		if present {
			t.Errorf("%s was NULL and came back present", name)
		}
	}

	// PostgreSQL agrees, asked directly.
	var pgNick *string
	if err := conn.QueryRow(t.Context(), "SELECT nickname FROM users WHERE id = 2").Scan(&pgNick); err != nil {
		t.Fatalf("handwritten: %v", err)
	}
	if pgNick != nil {
		t.Errorf("the fixture is wrong: nickname is not NULL")
	}
}

// Arithmetic propagates NULL, so an expression over a nullable column is
// nullable. This is the runtime half of the compile-time rule.
func TestAudit_arithmeticPropagatesNull(t *testing.T) {
	testdb.AdminDSN(t)
	db, conn := nullDB(t)

	shape := orm.Project1(
		gendemo.Users.Visits.Add(1),
		func(v *int64) *int64 { return v },
	)
	got, err := orm.Select(db.Users, shape).OrderBy(gendemo.Users.ID.Asc()).All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	if got[0] == nil || *got[0] != 1 {
		t.Errorf("0 + 1 = %v, want 1", got[0])
	}
	if got[1] != nil {
		t.Errorf("NULL + 1 = %v, want NULL", *got[1])
	}

	var want *int64
	if err := conn.QueryRow(t.Context(), "SELECT visits + 1 FROM users WHERE id = 2").Scan(&want); err != nil {
		t.Fatalf("handwritten: %v", err)
	}
	if want != nil {
		t.Fatal("the fixture is wrong: NULL + 1 is not NULL")
	}
}

// ------------------------------------------------------- positional binding

// The contract is positional, so two expressions of one Go type must not be
// silently interchangeable. This is the test that would fail if the select list
// and the scanner ever drifted apart.
func TestAudit_projectionIsPositional(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, `
		CREATE TABLE pairs (a text NOT NULL, b text NOT NULL, m bigint NOT NULL, n bigint NOT NULL);
		INSERT INTO pairs VALUES ('first', 'second', 10, 20);`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })

	src := orm.NewSource("public", "pairs")
	type pairs struct{}
	meta := orm.EntityMeta[pairs]{
		Table:   orm.TableID{Schema: "public", Name: "pairs"},
		Source:  src,
		Columns: []orm.ColumnMeta{{Name: "a", Field: "A"}},
		Dest:    func(*pairs, int) any { return new(string) },
	}
	repo := orm.NewRepo(conn, &meta)
	a := orm.NewTextCol[pairs](src, "a")
	b := orm.NewTextCol[pairs](src, "b")
	m := orm.NewOrdCol[pairs, int64](src, "m")
	n := orm.NewOrdCol[pairs, int64](src, "n")

	type out struct {
		A, B string
		M, N int64
	}
	got, err := orm.Select(repo, orm.Project4(a, b, m, n,
		func(a, b string, m, n int64) out { return out{a, b, m, n} })).One(t.Context())
	if err != nil {
		t.Fatalf("One: %v", err)
	}
	if got.A != "first" || got.B != "second" || got.M != 10 || got.N != 20 {
		t.Fatalf("positions were not preserved: %+v", got)
	}

	// Swapping the expressions swaps the values, which proves the binding is
	// positional rather than by name or by luck.
	swapped, err := orm.Select(repo, orm.Project4(b, a, n, m,
		func(a, b string, m, n int64) out { return out{a, b, m, n} })).One(t.Context())
	if err != nil {
		t.Fatalf("One: %v", err)
	}
	if swapped.A != "second" || swapped.B != "first" || swapped.M != 20 || swapped.N != 10 {
		t.Fatalf("swapping the expressions did not swap the values: %+v", swapped)
	}
}

// A result alias names a column of the result and nothing else. Awkward ones
// have to survive quoting.
func TestAudit_aliasQuoting(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	for _, alias := range []string{
		"select", "GROUP", "a b", `a"b`, "Ünïcödé", strings.Repeat("x", 63),
		"MixedCase", "mixedcase",
	} {
		shape := orm.Project1(gendemo.Users.Email.As(alias), func(s string) string { return s })
		sql, _, err := orm.Select(db.Users, shape).SQL()
		if err != nil {
			t.Errorf("alias %q: SQL: %v", alias, err)
			continue
		}
		if !strings.Contains(sql, `"`+strings.ReplaceAll(alias, `"`, `""`)+`"`) {
			t.Errorf("alias %q was not quoted: %s", alias, sql)
		}
		if _, err := orm.Select(db.Users, shape).All(t.Context()); err != nil {
			t.Errorf("alias %q: All: %v", alias, err)
		}
	}

	// Two results cannot claim one name.
	dup := orm.Project2(
		gendemo.Users.ID.As("x"), gendemo.Users.Email.As("x"),
		func(id int64, s string) string { return s },
	)
	if _, _, err := orm.Select(db.Users, dup).SQL(); err == nil {
		t.Error("two results named x were accepted")
	} else if !strings.Contains(err.Error(), "identifies one column") {
		t.Errorf("err = %v", err)
	}

	// Aliases differing only in case are two names, as PostgreSQL quotes them.
	mixed := orm.Project2(
		gendemo.Users.ID.As("X"), gendemo.Users.Email.As("x"),
		func(id int64, s string) string { return s },
	)
	if _, _, err := orm.Select(db.Users, mixed).SQL(); err != nil {
		t.Errorf("quoted aliases differing in case were refused: %v", err)
	}
}

// ------------------------------------------------------- expression immutability

// Every expression this package hands out is a value. Reusing one must not
// change what another query compiles to, and nothing may reach back into a
// generated descriptor.
func TestAudit_expressionsAreImmutable(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	// One aggregate, three different filters. Each must see only its own.
	base := orm.Count[gendemo.User]()
	active := base.Filter(gendemo.Users.Active.Eq(true))
	banned := base.Filter(gendemo.Users.State.Eq(gendemo.UserStateBanned))
	distinct := base.Distinct()

	shape := orm.Project4(base, active, banned, distinct,
		func(all, a, b, d int64) [4]int64 { return [4]int64{all, a, b, d} })
	sql, _, err := orm.Select(db.Users, shape).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if strings.Count(sql, "FILTER") != 2 {
		t.Errorf("filters leaked between aggregates: %s", sql)
	}
	if !strings.HasPrefix(sql, "SELECT count(*), count(*) FILTER") {
		t.Errorf("the unfiltered aggregate inherited a filter: %s", sql)
	}

	got, err := orm.Select(db.Users, shape).One(t.Context())
	if err != nil {
		t.Fatalf("One: %v", err)
	}
	if got[0] != 3 || got[1] != 2 || got[2] != 1 {
		t.Errorf("counts = %v, want [3 2 1 ...]", got)
	}

	// The same value expression in two clauses, and in two queries.
	shared := gendemo.Users.Age.Add(1)
	one := orm.Select(db.Users, orm.Project1(shared, func(v int32) int32 { return v }))
	two := orm.Select(db.Users, orm.Project1(shared, func(v int32) int32 { return v })).
		Where(gendemo.Users.ID.Gt(1))
	sqlOne, _, err := one.SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if _, _, err := two.SQL(); err != nil {
		t.Fatalf("SQL: %v", err)
	}
	sqlAgain, _, err := one.SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if sqlOne != sqlAgain {
		t.Errorf("building a second query changed the first:\n  %s\n  %s", sqlOne, sqlAgain)
	}

	// An assignment expression reused across two updates.
	inc := gendemo.Users.Age.Add(1)
	a, _, err := db.Users.Update().Set(gendemo.Users.Age.SetExpr(inc)).Where(gendemo.Users.ID.Eq(1)).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	b, _, err := db.Users.Update().Set(gendemo.Users.Age.SetExpr(inc)).Where(gendemo.Users.ID.Eq(2)).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if strings.Replace(a, "= $2", "", 1) != strings.Replace(b, "= $2", "", 1) {
		t.Errorf("a reused assignment differs between builders:\n  %s\n  %s", a, b)
	}
}

// The same expressions, built from many goroutines at once.
func TestAudit_expressionsAreRaceFree(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	shape := orm.Project2(gendemo.Users.ID, gendemo.Users.Email,
		func(id int64, email string) UserSummary { return UserSummary{id, email} })

	var wg sync.WaitGroup
	for range 32 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_ = orm.Count[gendemo.User]().Filter(gendemo.Users.Active.Eq(true)).Distinct().As("n")
			_ = gendemo.Users.Age.Add(1)
			_ = gendemo.Users.Email.As("addr")
			_ = orm.Excluded(gendemo.Users.Nickname)
			q := orm.Select(db.Users, shape).
				Where(gendemo.Users.Active.Eq(true)).
				GroupBy(gendemo.Users.ID, gendemo.Users.Email).
				Having(orm.Count[gendemo.User]().Gt(0)).
				Distinct()
			if _, _, err := q.Clone().SQL(); err != nil {
				t.Errorf("SQL: %v", err)
			}
			_, _, _ = orm.UpdateReturning(
				db.Users.Update().Set(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))).
					Where(gendemo.Users.ID.Eq(1)), shape).SQL()
		}()
	}
	wg.Wait()

	sql, _, err := orm.Select(db.Users, shape).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if strings.Contains(sql, "addr") || strings.Contains(sql, "DISTINCT") ||
		strings.Contains(sql, "GROUP BY") {
		t.Errorf("a per-query option reached the shared shape: %s", sql)
	}
}

// ------------------------------------------------------------ the mutations

// A write is exactly the write the builder described. One reports afterwards
// and never narrows it, and there is no statement before or after.
func TestAudit_writeAffectsTheDescribedRowset(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schema(t)+`
		INSERT INTO users (id, email, age, tags, settings)
		  SELECT g, 'u'||g||'@example.com', 10, '{}', '{}' FROM generate_series(1, 5) g;
		SELECT setval(pg_get_serial_sequence('users','id'), 1000);`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })
	ex := &countingExecutor{Executor: conn}
	db := gendemo.New(ex)

	ex.reset()
	_, err = orm.UpdateReturning(
		db.Users.Update().Set(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))).All(),
		userSummaries,
	).One(t.Context())
	if !errors.Is(err, orm.ErrMultipleRows) {
		t.Fatalf("One = %v, want ErrMultipleRows", err)
	}
	// One statement, and all five rows changed.
	if ex.n != 1 {
		t.Errorf("the write ran %d statements, want 1", ex.n)
	}
	var changed int
	if err := conn.QueryRow(t.Context(), "SELECT count(*) FROM users WHERE age = 11").Scan(&changed); err != nil {
		t.Fatalf("counting: %v", err)
	}
	if changed != 5 {
		t.Errorf("%d rows changed; One must not narrow the mutation", changed)
	}
	// And the statement carries no LIMIT.
	sql, _, err := orm.UpdateReturning(
		db.Users.Update().Set(gendemo.Users.Age.Set(1)).All(), userSummaries).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if strings.Contains(strings.ToUpper(sql), "LIMIT") {
		t.Errorf("the write carries a LIMIT: %s", sql)
	}

	// A delete returns the rows as they were, in one statement, with nothing
	// selected before or after.
	ex.reset()
	gone, err := orm.DeleteReturning(
		db.Users.Delete().Where(gendemo.Users.ID.Lte(2)), userSummaries).All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	if len(gone) != 2 {
		t.Fatalf("deleted %v", gone)
	}
	if ex.n != 1 {
		t.Errorf("the delete ran %d statements, want 1", ex.n)
	}
	var left int
	if err := conn.QueryRow(t.Context(), "SELECT count(*) FROM users").Scan(&left); err != nil {
		t.Fatalf("counting: %v", err)
	}
	if left != 3 {
		t.Errorf("%d rows remain, want 3", left)
	}
}

// An expression assignment is computed by PostgreSQL, not by Go. Two concurrent
// increments therefore both land.
func TestAudit_noReadModifyWrite(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schema(t)+`
		INSERT INTO users (id, email, age, tags, settings)
		  VALUES (1, 'c@example.com', 0, '{}', '{}');`)
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("parsing the DSN: %v", err)
	}
	cfg.AfterConnect = gendemo.RegisterTypes
	pool, err := pgxpool.NewWithConfig(t.Context(), cfg)
	if err != nil {
		t.Fatalf("opening a pool: %v", err)
	}
	defer pool.Close()
	db := gendemo.New(pool)

	const n = 50
	var wg sync.WaitGroup
	for range n {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if _, err := db.Users.Update().
				Set(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))).
				Where(gendemo.Users.ID.Eq(1)).Exec(t.Context()); err != nil {
				t.Errorf("Exec: %v", err)
			}
		}()
	}
	wg.Wait()

	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	defer func() { _ = conn.Close(context.WithoutCancel(t.Context())) }()
	var age int32
	if err := conn.QueryRow(t.Context(), "SELECT age FROM users WHERE id = 1").Scan(&age); err != nil {
		t.Fatalf("reading back: %v", err)
	}
	// A read-modify-write in Go would lose updates; PostgreSQL's own
	// arithmetic under row locks does not.
	if age != n {
		t.Errorf("age = %d after %d concurrent increments; increments were lost", age, n)
	}
}

// A conflict WHERE restricts the update, not the insert.
func TestAudit_conflictWhereLocality(t *testing.T) {
	testdb.AdminDSN(t)
	db := emptyDB(t)

	first := newUser("c@example.com")
	first.Age = 10
	if _, err := db.Users.Insert(t.Context(), first); err != nil {
		t.Fatalf("Insert: %v", err)
	}

	// The condition holds, so the update runs.
	again := newUser("c@example.com")
	again.Age = 99
	got, err := db.Users.Insert(t.Context(), again,
		orm.OnConflict(gendemo.Users.Email).
			Where(gendemo.Users.Age.Lt(50)).
			DoUpdateSet(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))),
	)
	if err != nil {
		t.Fatalf("Insert: %v", err)
	}
	if got.Age != 11 {
		t.Errorf("age = %d, want 11", got.Age)
	}

	// Now it does not, so PostgreSQL updates nothing and returns no row. The
	// insert still ran and still conflicted — the condition governs the update.
	if _, err := db.Users.Insert(t.Context(), again,
		orm.OnConflict(gendemo.Users.Email).
			Where(gendemo.Users.Age.Gt(1000)).
			DoUpdateSet(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))),
	); !errors.Is(err, orm.ErrConflictIgnored) {
		t.Errorf("Insert = %v, want ErrConflictIgnored", err)
	}
	// And exactly one row exists: the conflict was not turned into an insert.
	n, err := db.Users.Query().Count(t.Context())
	if err != nil {
		t.Fatalf("Count: %v", err)
	}
	if n != 1 {
		t.Errorf("%d rows, want 1", n)
	}

	sql, _, err := db.Users.InsertSQL([]gendemo.User{again},
		orm.OnConflict(gendemo.Users.Email).
			Where(gendemo.Users.Age.Lt(50)).
			DoUpdateSet(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(1))),
	)
	if err != nil {
		t.Fatalf("InsertSQL: %v", err)
	}
	// The WHERE belongs to the DO UPDATE, and there is no other one.
	if !strings.Contains(sql, `DO UPDATE SET "age" = "users"."age" + $`) ||
		!strings.Contains(sql, `WHERE "users"."age" < $`) {
		t.Errorf("SQL = %s", sql)
	}
	if strings.Count(strings.ToUpper(sql), " WHERE ") != 1 {
		t.Errorf("the conflict condition leaked into another clause: %s", sql)
	}
}

// ------------------------------------------------------------- raw expressions

// A raw typed expression is a trust boundary: the caller states the result
// type and this package believes them. What is required is that a wrong
// statement fails cleanly.
func TestAudit_rawValueIsATrustBoundary(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	// Declared non-null, returns NULL: a scan error, not a zero value.
	lying := orm.Project1(
		orm.RawValue[gendemo.User, string]("NULL::text"),
		func(s string) string { return s },
	)
	_, err := orm.Select(db.Users, lying).All(t.Context())
	if err == nil {
		t.Error("a NULL scanned into a non-nullable destination without complaint")
	}

	// Declared nullable, returns NULL: the honest form works.
	honest := orm.Project1(
		orm.RawValue[gendemo.User, *string]("NULL::text"),
		func(s *string) *string { return s },
	)
	got, err := orm.Select(db.Users, honest).Limit(1).All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	if len(got) != 1 || got[0] != nil {
		t.Errorf("got %v, want one NULL", got)
	}

	// Declared as the wrong type: a scan error rather than a wrong value.
	wrong := orm.Project1(
		orm.RawValue[gendemo.User, int64]("'not a number'::text"),
		func(n int64) int64 { return n },
	)
	if _, err := orm.Select(db.Users, wrong).All(t.Context()); err == nil {
		t.Error("text scanned into int64 without complaint")
	}

	// Its own placeholders are renumbered into the statement.
	args := orm.Project2(
		orm.RawValue[gendemo.User, string]("upper($1)", "shout"),
		gendemo.Users.Email,
		func(a, b string) string { return a },
	)
	sql, params, err := orm.Select(db.Users, args).Where(gendemo.Users.ID.Eq(1)).SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if !strings.Contains(sql, "upper($1)") || fmt.Sprint(params) != "[shout 1]" {
		t.Errorf("SQL = %s, args = %v", sql, params)
	}
	out, err := orm.Select(db.Users, args).Where(gendemo.Users.ID.Eq(1)).One(t.Context())
	if err != nil {
		t.Fatalf("One: %v", err)
	}
	if out != "SHOUT" {
		t.Errorf("got %q", out)
	}
}

// ------------------------------------------------------------------ numerics

// A numeric result is never a float. The aggregate constructors that produce
// numeric take the Go type as a parameter, so the only thing to check is that
// nothing quietly widens or narrows on the way.
func TestAudit_numericIsNeverAFloat(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, `
		CREATE TABLE money (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, amount numeric(20,4) NOT NULL);
		INSERT INTO money (amount) VALUES (0.1), (0.2), (12345678901234.5678);`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })

	src := orm.NewSource("public", "money")
	type money struct{}
	meta := orm.EntityMeta[money]{
		Table:   orm.TableID{Schema: "public", Name: "money"},
		Source:  src,
		Columns: []orm.ColumnMeta{{Name: "id", Field: "ID"}},
		Dest:    func(*money, int) any { return new(int64) },
	}
	repo := orm.NewRepo(conn, &meta)
	amount := orm.NewOrdCol[money, pgtype.Numeric](src, "amount")

	shape := orm.Project1(
		orm.SumNumeric[money, pgtype.Numeric](amount),
		func(v *pgtype.Numeric) *pgtype.Numeric { return v },
	)
	got, err := orm.Select(repo, shape).One(t.Context())
	if err != nil {
		t.Fatalf("One: %v", err)
	}
	if got == nil || !got.Valid {
		t.Fatalf("sum = %v", got)
	}
	var want pgtype.Numeric
	if err := conn.QueryRow(t.Context(), "SELECT sum(amount) FROM money").Scan(&want); err != nil {
		t.Fatalf("handwritten: %v", err)
	}
	a, _ := got.Value()
	b, _ := want.Value()
	if fmt.Sprint(a) != fmt.Sprint(b) {
		t.Errorf("sum = %v, PostgreSQL says %v", a, b)
	}
	// The exact digits survived: a float64 would have lost them.
	if !strings.Contains(fmt.Sprint(a), "12345678901234") {
		t.Errorf("precision was lost: %v", a)
	}
}

// ------------------------------------------------------------- scope and order

// Every clause M10 added validates its sources the way M3's did. An occurrence
// the statement does not select from is refused before PostgreSQL sees it.
func TestAudit_scopeIsCheckedInEveryNewClause(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schema(t)+seed)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })
	ex := &countingExecutor{Executor: conn}
	db := gendemo.New(ex)

	other := gendemo.Users.As("other")
	summaries := orm.Project1(gendemo.Users.ID, func(id int64) int64 { return id })

	for _, tt := range []struct {
		name string
		run  func() error
	}{
		{"an unattached occurrence in the select list", func() error {
			_, _, err := orm.Select(db.Users,
				orm.Project1(other.ID, func(id int64) int64 { return id })).SQL()
			return err
		}},
		{"an unattached occurrence in Where", func() error {
			_, _, err := orm.Select(db.Users, summaries).Where(other.Age.Gt(1)).SQL()
			return err
		}},
		{"an unattached occurrence in GroupBy", func() error {
			_, _, err := orm.Select(db.Users, summaries).GroupBy(other.ID).SQL()
			return err
		}},
		{"an unattached occurrence in Having", func() error {
			_, _, err := orm.Select(db.Users, summaries).
				GroupBy(gendemo.Users.ID).
				Having(orm.CountOf(other.ID).Gt(0)).SQL()
			return err
		}},
		{"an unattached occurrence in an aggregate filter", func() error {
			_, _, err := orm.Select(db.Users,
				orm.Project1(orm.Count[gendemo.User]().Filter(other.Age.Gt(1)),
					func(n int64) int64 { return n })).SQL()
			return err
		}},
		{"an unattached occurrence in a write expression", func() error {
			_, _, err := db.Users.Update().
				Set(gendemo.Users.Age.SetExpr(other.Age.Add(1))).
				Where(gendemo.Users.ID.Eq(1)).SQL()
			return err
		}},
		{"an unattached occurrence in a RETURNING list", func() error {
			_, _, err := orm.UpdateReturning(
				db.Users.Update().Set(gendemo.Users.Age.Set(1)).Where(gendemo.Users.ID.Eq(1)),
				orm.Project1(other.ID, func(id int64) int64 { return id }),
			).SQL()
			return err
		}},
	} {
		err := tt.run()
		if err == nil {
			t.Errorf("%s compiled", tt.name)
			continue
		}
		if !strings.Contains(err.Error(), "scope error") {
			t.Errorf("%s: err = %v, want a scope error", tt.name, err)
		}
	}
	if ex.n != 0 {
		t.Errorf("a refused statement reached the database %d times", ex.n)
	}
}

// One statement carrying an argument in every clause that can hold one, run for
// real: the numbering has to be the compiler's single sequence, in text order.
func TestAudit_placeholderOrderAcrossEveryClause(t *testing.T) {
	testdb.AdminDSN(t)
	db, conn := aggDB(t)

	shape := orm.Project2(
		orm.RawValue[gendemo.Post, string]("upper($1)", "first"),
		orm.Count[gendemo.Post]().Filter(gendemo.Posts.Published.Eq(true)),
		func(s string, n int64) string { return fmt.Sprintf("%s:%d", s, n) },
	)
	sql, args, err := orm.Select(db.Posts, shape).
		Where(gendemo.Posts.Score.Gt(0)).
		GroupBy(gendemo.Posts.AuthorID).
		Having(orm.Count[gendemo.Post]().Gt(0)).
		SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	// Select list, then FILTER, then WHERE, then HAVING.
	if fmt.Sprint(args) != "[first true 0 0]" {
		t.Errorf("args = %v", args)
	}
	for i, want := range []string{"upper($1)", "FILTER (WHERE \"posts\".\"published\" = $2", "> $3", "> $4"} {
		if !strings.Contains(sql, want) {
			t.Errorf("clause %d: %q missing from %s", i, want, sql)
		}
	}
	if _, err := orm.Select(db.Posts, shape).
		Where(gendemo.Posts.Score.Gt(0)).
		GroupBy(gendemo.Posts.AuthorID).
		Having(orm.Count[gendemo.Post]().Gt(0)).
		All(t.Context()); err != nil {
		t.Fatalf("All: %v", err)
	}

	// The write side, with an argument in every clause an insert can carry.
	one := newUser("ph@example.com")
	insertSQL, insertArgs, err := db.Users.InsertSQL([]gendemo.User{one},
		orm.OnConflict(gendemo.Users.Email).
			Where(gendemo.Users.Age.Lt(99)).
			DoUpdateSet(gendemo.Users.Age.SetExpr(gendemo.Users.Age.Add(7))),
	)
	if err != nil {
		t.Fatalf("InsertSQL: %v", err)
	}
	// The row's own values first, then the conflict assignment, then the
	// conflict condition — the order they appear in the statement.
	n := len(insertArgs)
	if fmt.Sprint(insertArgs[n-2]) != "7" || fmt.Sprint(insertArgs[n-1]) != "99" {
		t.Errorf("the last two args are %v, want the assignment then the condition", insertArgs[n-2:])
	}
	if strings.Index(insertSQL, fmt.Sprintf("$%d", n-1)) > strings.Index(insertSQL, fmt.Sprintf("$%d", n)) {
		t.Errorf("placeholders are out of text order: %s", insertSQL)
	}
	_ = conn
}

// Query.Count is the M0–M9 question and is untouched by anything M10 added.
func TestAudit_queryCountIsFrozen(t *testing.T) {
	testdb.AdminDSN(t)
	db, _ := aggDB(t)

	for _, tt := range []struct {
		name string
		q    *orm.Query[gendemo.Post]
		want int64
	}{
		{"everything", db.Posts.Query(), 5},
		{"filtered", db.Posts.Query().Where(gendemo.Posts.Published.Eq(true)), 3},
		{"limited", db.Posts.Query().Limit(2), 2},
		{"offset", db.Posts.Query().Offset(3), 2},
		{"limit and offset", db.Posts.Query().Limit(2).Offset(4), 1},
		{"ordering is not part of it", db.Posts.Query().OrderBy(gendemo.Posts.ID.Desc()), 5},
		{"a relation is not part of it", db.Posts.Query().With(gendemo.Posts.Comments), 5},
		{"a semi-join is", db.Posts.Query().Where(gendemo.Posts.Author.Any()), 4},
	} {
		got, err := tt.q.Count(t.Context())
		if err != nil {
			t.Fatalf("%s: Count: %v", tt.name, err)
		}
		if got != tt.want {
			t.Errorf("%s: Count = %d, want %d", tt.name, got, tt.want)
		}
	}
}

// DISTINCT is PostgreSQL's, not a pass over the rows in Go.
func TestAudit_distinctIsTheServers(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, `
		CREATE TABLE dups (a text, b bigint);
		INSERT INTO dups VALUES ('x', 1), ('x', 1), ('x', 2), (NULL, 1), (NULL, 1), (NULL, NULL);`)
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })

	src := orm.NewSource("public", "dups")
	type dups struct{}
	meta := orm.EntityMeta[dups]{
		Table:   orm.TableID{Schema: "public", Name: "dups"},
		Source:  src,
		Columns: []orm.ColumnMeta{{Name: "a", Field: "A"}},
		Dest:    func(*dups, int) any { return new(string) },
	}
	repo := orm.NewRepo(conn, &meta)
	a := orm.NewNullTextCol[dups](src, "a")
	b := orm.NewNullOrdCol[dups, int64](src, "b")

	shape := orm.Project2(a, b, func(a *string, b *int64) string {
		return fmt.Sprintf("%s/%v", text(a), b == nil)
	})
	got, err := orm.Select(repo, shape).Distinct().All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	var want int
	if err := conn.QueryRow(t.Context(), "SELECT count(*) FROM (SELECT DISTINCT a, b FROM dups) x").Scan(&want); err != nil {
		t.Fatalf("handwritten: %v", err)
	}
	// Four distinct rows: NULL is not distinct from NULL in DISTINCT.
	if len(got) != want {
		t.Errorf("DISTINCT returned %d rows, PostgreSQL says %d", len(got), want)
	}

	// Without it, every row comes back — nothing deduplicates in Go.
	all, err := orm.Select(repo, shape).All(t.Context())
	if err != nil {
		t.Fatalf("All: %v", err)
	}
	if len(all) != 6 {
		t.Errorf("without DISTINCT, %d rows came back, want 6", len(all))
	}
}

// A projection over SQL returning the wrong number of columns fails cleanly.
func TestAudit_columnCountMismatch(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	// One expression that yields two columns is not something the typed API can
	// build; the raw escape hatch can, and the failure has to be an error.
	tooMany := orm.Project1(
		orm.RawValue[gendemo.User, string]("id, email"),
		func(s string) string { return s },
	)
	if _, err := orm.Select(db.Users, tooMany).All(t.Context()); err == nil {
		t.Error("a raw expression yielding two columns was accepted")
	}
}

// Cloning isolates every slice the new builder owns.
func TestAudit_cloneIsDeep(t *testing.T) {
	testdb.AdminDSN(t)
	db := db(t)

	shape := orm.Project1(gendemo.Users.ID, func(id int64) int64 { return id })
	base := orm.Select(db.Users, shape).Where(gendemo.Users.Age.Gt(0))
	clone := base.Clone()

	base.GroupBy(gendemo.Users.ID).Having(orm.Count[gendemo.User]().Gt(0)).
		Distinct().Limit(1).Offset(1).OrderBy(gendemo.Users.ID.Desc())

	cloneSQL, _, err := clone.SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	for _, unwanted := range []string{"GROUP BY", "HAVING", "DISTINCT", "LIMIT", "OFFSET", "ORDER BY"} {
		if strings.Contains(cloneSQL, unwanted) {
			t.Errorf("the clone inherited %s: %s", unwanted, cloneSQL)
		}
	}
	baseSQL, _, err := base.SQL()
	if err != nil {
		t.Fatalf("SQL: %v", err)
	}
	if !strings.Contains(baseSQL, "GROUP BY") {
		t.Errorf("the original lost its own configuration: %s", baseSQL)
	}
}

// Several independent mistakes are reported together, and none reaches the
// database.
func TestAudit_builderErrorsAccumulate(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schema(t))
	conn, err := pgx.Connect(t.Context(), dsn)
	if err != nil {
		t.Fatalf("connecting: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close(context.WithoutCancel(t.Context())) })
	ex := &countingExecutor{Executor: conn}
	db := gendemo.New(ex)

	shape := orm.Project1(gendemo.Users.ID, func(id int64) int64 { return id })
	_, err = orm.Select(db.Users, shape).
		Limit(-1).
		Offset(-2).
		Where(orm.Count[gendemo.User]().Gt(1)).
		GroupBy(orm.RawValue[gendemo.User, int64]("1")).
		All(t.Context())
	if err == nil {
		t.Fatal("a builder with three mistakes ran")
	}
	for _, want := range []string{"limit", "offset", "belongs in Having"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the joined error is missing %q: %v", want, err)
		}
	}
	if ex.n != 0 {
		t.Errorf("a refused query reached the database %d times", ex.n)
	}
}

// A projection streams; nothing materialises an entity on the way.
func TestAudit_projectionStreamsLarge(t *testing.T) {
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schema(t)+`
		INSERT INTO users (id, email, age, tags, settings)
		  SELECT g, 'u'||g||'@example.com', 30, '{}', '{}' FROM generate_series(1, 50000) g;`)
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("parsing the DSN: %v", err)
	}
	cfg.MaxConns = 2
	cfg.AfterConnect = gendemo.RegisterTypes
	pool, err := pgxpool.NewWithConfig(t.Context(), cfg)
	if err != nil {
		t.Fatalf("opening a pool: %v", err)
	}
	defer pool.Close()
	db := gendemo.New(pool)

	shape := orm.Project1(gendemo.Users.ID, func(id int64) int64 { return id })
	n := 0
	for _, err := range orm.Select(db.Users, shape).Rows(t.Context()) {
		if err != nil {
			t.Fatalf("Rows: %v", err)
		}
		n++
	}
	if n != 50000 {
		t.Fatalf("streamed %d rows", n)
	}
	// Break in the middle, then cancel in the middle, then acquire both
	// connections to prove neither was left out.
	seen := 0
	for _, err := range orm.Select(db.Users, shape).Rows(t.Context()) {
		if err != nil {
			t.Fatalf("Rows: %v", err)
		}
		seen++
		if seen == 25000 {
			break
		}
	}
	ctx, cancel := context.WithCancel(t.Context())
	seen = 0
	for _, err := range orm.Select(db.Users, shape).Rows(ctx) {
		if err != nil {
			break
		}
		seen++
		if seen == 100 {
			cancel()
		}
	}
	cancel()

	acquire, stop := context.WithTimeout(t.Context(), 10*time.Second)
	defer stop()
	conns := make([]*pgxpool.Conn, 0, 2)
	for range 2 {
		c, err := pool.Acquire(acquire)
		if err != nil {
			t.Fatalf("the pool never recovered: %v", err)
		}
		conns = append(conns, c)
	}
	for _, c := range conns {
		c.Release()
	}
	if used := pool.Stat().AcquiredConns(); used != 0 {
		t.Errorf("%d connections are still checked out", used)
	}
}
