// Code generated by orm. DO NOT EDIT.

package gendemo

import (
	"github.com/AlexAli29/orm"
)

// articleMeta describes how Article is read from public.articles.
var articleMeta = orm.EntityMeta[Article]{
	Table:  orm.TableID{Schema: "public", Name: "articles"},
	Source: articlesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "body", Field: "Body", NotNull: true},
		{Name: "search", Field: "Search", Generated: true},
	},
	Dest:  articleDest,
	Value: articleValue,
}

// articleDest returns a pointer to the field holding column idx of public.articles.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func articleDest(e *Article, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Title
	case 2:
		return &e.Body
	case 3:
		return &e.Search
	default:
		return nil
	}
}

// articleValue returns the value of the field holding column idx of public.articles.
//
// It is the counterpart of articleDest and is written the same way, so an
// insert reads the entity without reflection either.
func articleValue(e *Article, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Title
	case 2:
		return e.Body
	case 3:
		return e.Search
	default:
		return nil
	}
}

// avatarMeta describes how Avatar is read from public.avatars.
var avatarMeta = orm.EntityMeta[Avatar]{
	Table:  orm.TableID{Schema: "public", Name: "avatars"},
	Source: avatarsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "url", Field: "URL", NotNull: true},
	},
	Dest:  avatarDest,
	Value: avatarValue,
}

// avatarDest returns a pointer to the field holding column idx of public.avatars.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func avatarDest(e *Avatar, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.URL
	default:
		return nil
	}
}

// avatarValue returns the value of the field holding column idx of public.avatars.
//
// It is the counterpart of avatarDest and is written the same way, so an
// insert reads the entity without reflection either.
func avatarValue(e *Avatar, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.URL
	default:
		return nil
	}
}

// bookingMeta describes how Booking is read from public.bookings.
var bookingMeta = orm.EntityMeta[Booking]{
	Table:  orm.TableID{Schema: "public", Name: "bookings"},
	Source: bookingsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "room", Field: "Room", NotNull: true},
		{Name: "starts_at", Field: "StartsAt", NotNull: true},
		{Name: "period", Field: "Period", NotNull: true},
		{Name: "stay", Field: "Stay", NotNull: true},
		{Name: "shift", Field: "Shift", NotNull: true},
		{Name: "quota", Field: "Quota", NotNull: true},
		{Name: "span", Field: "Span", NotNull: true},
		{Name: "revised", Field: "Revised"},
		{Name: "lease", Field: "Lease", NotNull: true},
		{Name: "grace", Field: "Grace"},
		{Name: "holds", Field: "Holds", NotNull: true},
		{Name: "slots", Field: "Slots"},
	},
	Dest:  bookingDest,
	Value: bookingValue,
}

// bookingDest returns a pointer to the field holding column idx of public.bookings.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func bookingDest(e *Booking, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Room
	case 2:
		return &e.StartsAt
	case 3:
		return &e.Period
	case 4:
		return &e.Stay
	case 5:
		return &e.Shift
	case 6:
		return &e.Quota
	case 7:
		return &e.Span
	case 8:
		return &e.Revised
	case 9:
		return &e.Lease
	case 10:
		return &e.Grace
	case 11:
		return &e.Holds
	case 12:
		return &e.Slots
	default:
		return nil
	}
}

// bookingValue returns the value of the field holding column idx of public.bookings.
//
// It is the counterpart of bookingDest and is written the same way, so an
// insert reads the entity without reflection either.
func bookingValue(e *Booking, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Room
	case 2:
		return e.StartsAt
	case 3:
		return e.Period
	case 4:
		return e.Stay
	case 5:
		return e.Shift
	case 6:
		return e.Quota
	case 7:
		return e.Span
	case 8:
		return e.Revised
	case 9:
		return e.Lease
	case 10:
		return e.Grace
	case 11:
		return e.Holds
	case 12:
		return e.Slots
	default:
		return nil
	}
}

// branchMeta describes how Branch is read from public.branches.
var branchMeta = orm.EntityMeta[Branch]{
	Table:  orm.TableID{Schema: "public", Name: "branches"},
	Source: branchesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "label", Field: "Label", NotNull: true},
		{Name: "branch_code", Field: "Code", NotNull: true},
		{Name: "branch_region", Field: "Region", NotNull: true},
	},
	Dest:  branchDest,
	Value: branchValue,
}

// branchDest returns a pointer to the field holding column idx of public.branches.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func branchDest(e *Branch, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Label
	case 2:
		return &e.Code
	case 3:
		return &e.Region
	default:
		return nil
	}
}

// branchValue returns the value of the field holding column idx of public.branches.
//
// It is the counterpart of branchDest and is written the same way, so an
// insert reads the entity without reflection either.
func branchValue(e *Branch, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Label
	case 2:
		return e.Code
	case 3:
		return e.Region
	default:
		return nil
	}
}

// branchEventMeta describes how BranchEvent is read from public.branch_events.
var branchEventMeta = orm.EntityMeta[BranchEvent]{
	Table:  orm.TableID{Schema: "public", Name: "branch_events"},
	Source: branchEventsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "label", Field: "Label", NotNull: true},
		{Name: "event_code", Field: "Code", NotNull: true},
		{Name: "event_region", Field: "Region", NotNull: true},
	},
	Dest:  branchEventDest,
	Value: branchEventValue,
}

// branchEventDest returns a pointer to the field holding column idx of public.branch_events.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func branchEventDest(e *BranchEvent, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Label
	case 2:
		return &e.Code
	case 3:
		return &e.Region
	default:
		return nil
	}
}

// branchEventValue returns the value of the field holding column idx of public.branch_events.
//
// It is the counterpart of branchEventDest and is written the same way, so an
// insert reads the entity without reflection either.
func branchEventValue(e *BranchEvent, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Label
	case 2:
		return e.Code
	case 3:
		return e.Region
	default:
		return nil
	}
}

// categoryMeta describes how Category is read from public.categories.
var categoryMeta = orm.EntityMeta[Category]{
	Table:  orm.TableID{Schema: "public", Name: "categories"},
	Source: categoriesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "name", Field: "Name", NotNull: true},
	},
	Dest:  categoryDest,
	Value: categoryValue,
}

// categoryDest returns a pointer to the field holding column idx of public.categories.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func categoryDest(e *Category, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Name
	default:
		return nil
	}
}

// categoryValue returns the value of the field holding column idx of public.categories.
//
// It is the counterpart of categoryDest and is written the same way, so an
// insert reads the entity without reflection either.
func categoryValue(e *Category, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Name
	default:
		return nil
	}
}

// commentMeta describes how Comment is read from public.comments.
var commentMeta = orm.EntityMeta[Comment]{
	Table:  orm.TableID{Schema: "public", Name: "comments"},
	Source: commentsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "body", Field: "Body", NotNull: true},
		{Name: "visible", Field: "Visible", NotNull: true, HasDefault: true},
		{Name: "score", Field: "Score", NotNull: true, HasDefault: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  commentDest,
	Value: commentValue,
}

// commentDest returns a pointer to the field holding column idx of public.comments.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func commentDest(e *Comment, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Body
	case 2:
		return &e.Visible
	case 3:
		return &e.Score
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// commentValue returns the value of the field holding column idx of public.comments.
//
// It is the counterpart of commentDest and is written the same way, so an
// insert reads the entity without reflection either.
func commentValue(e *Comment, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Body
	case 2:
		return e.Visible
	case 3:
		return e.Score
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}

// documentMeta describes how Document is read from public.documents.
var documentMeta = orm.EntityMeta[Document]{
	Table:  orm.TableID{Schema: "public", Name: "documents"},
	Source: documentsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "creator_id", Field: "CreatorID", NotNull: true},
	},
	Dest:  documentDest,
	Value: documentValue,
}

// documentDest returns a pointer to the field holding column idx of public.documents.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func documentDest(e *Document, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Title
	case 2:
		return &e.CreatorID
	default:
		return nil
	}
}

// documentValue returns the value of the field holding column idx of public.documents.
//
// It is the counterpart of documentDest and is written the same way, so an
// insert reads the entity without reflection either.
func documentValue(e *Document, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Title
	case 2:
		return e.CreatorID
	default:
		return nil
	}
}

// memberMeta describes how Member is read from public.members.
var memberMeta = orm.EntityMeta[Member]{
	Table:  orm.TableID{Schema: "public", Name: "members"},
	Source: membersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "team_slug", Field: "TeamSlug", NotNull: true},
		{Name: "nickname", Field: "Nickname", NotNull: true},
	},
	Dest:  memberDest,
	Value: memberValue,
}

// memberDest returns a pointer to the field holding column idx of public.members.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func memberDest(e *Member, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.TeamSlug
	case 2:
		return &e.Nickname
	default:
		return nil
	}
}

// memberValue returns the value of the field holding column idx of public.members.
//
// It is the counterpart of memberDest and is written the same way, so an
// insert reads the entity without reflection either.
func memberValue(e *Member, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.TeamSlug
	case 2:
		return e.Nickname
	default:
		return nil
	}
}

// networkMeta describes how Network is read from public.networks.
var networkMeta = orm.EntityMeta[Network]{
	Table:  orm.TableID{Schema: "public", Name: "networks"},
	Source: networksSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "label", Field: "Label", NotNull: true},
		{Name: "subnet", Field: "Subnet", NotNull: true},
		{Name: "host", Field: "Host", NotNull: true},
		{Name: "fallback", Field: "Fallback"},
		{Name: "hardware", Field: "Hardware", NotNull: true},
	},
	Dest:  networkDest,
	Value: networkValue,
}

// networkDest returns a pointer to the field holding column idx of public.networks.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func networkDest(e *Network, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Label
	case 2:
		return &e.Subnet
	case 3:
		return &e.Host
	case 4:
		return &e.Fallback
	case 5:
		return &e.Hardware
	default:
		return nil
	}
}

// networkValue returns the value of the field holding column idx of public.networks.
//
// It is the counterpart of networkDest and is written the same way, so an
// insert reads the entity without reflection either.
func networkValue(e *Network, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Label
	case 2:
		return e.Subnet
	case 3:
		return e.Host
	case 4:
		return e.Fallback
	case 5:
		return e.Hardware
	default:
		return nil
	}
}

// postMeta describes how Post is read from public.posts.
var postMeta = orm.EntityMeta[Post]{
	Table:  orm.TableID{Schema: "public", Name: "posts"},
	Source: postsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "author_id", Field: "AuthorID"},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "published", Field: "Published", NotNull: true, HasDefault: true},
		{Name: "score", Field: "Score", NotNull: true, HasDefault: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  postDest,
	Value: postValue,
}

// postDest returns a pointer to the field holding column idx of public.posts.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func postDest(e *Post, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.AuthorID
	case 2:
		return &e.Title
	case 3:
		return &e.Published
	case 4:
		return &e.Score
	case 5:
		return &e.CreatedAt
	default:
		return nil
	}
}

// postValue returns the value of the field holding column idx of public.posts.
//
// It is the counterpart of postDest and is written the same way, so an
// insert reads the entity without reflection either.
func postValue(e *Post, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.AuthorID
	case 2:
		return e.Title
	case 3:
		return e.Published
	case 4:
		return e.Score
	case 5:
		return e.CreatedAt
	default:
		return nil
	}
}

// profileMeta describes how Profile is read from public.profiles.
var profileMeta = orm.EntityMeta[Profile]{
	Table:  orm.TableID{Schema: "public", Name: "profiles"},
	Source: profilesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "user_id", Field: "UserID", NotNull: true},
		{Name: "bio", Field: "Bio"},
	},
	Dest:  profileDest,
	Value: profileValue,
}

// profileDest returns a pointer to the field holding column idx of public.profiles.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func profileDest(e *Profile, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.UserID
	case 2:
		return &e.Bio
	default:
		return nil
	}
}

// profileValue returns the value of the field holding column idx of public.profiles.
//
// It is the counterpart of profileDest and is written the same way, so an
// insert reads the entity without reflection either.
func profileValue(e *Profile, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.UserID
	case 2:
		return e.Bio
	default:
		return nil
	}
}

// reactionMeta describes how Reaction is read from public.reactions.
var reactionMeta = orm.EntityMeta[Reaction]{
	Table:  orm.TableID{Schema: "public", Name: "reactions"},
	Source: reactionsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "kind", Field: "Kind", NotNull: true},
	},
	Dest:  reactionDest,
	Value: reactionValue,
}

// reactionDest returns a pointer to the field holding column idx of public.reactions.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func reactionDest(e *Reaction, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Kind
	default:
		return nil
	}
}

// reactionValue returns the value of the field holding column idx of public.reactions.
//
// It is the counterpart of reactionDest and is written the same way, so an
// insert reads the entity without reflection either.
func reactionValue(e *Reaction, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Kind
	default:
		return nil
	}
}

// teamMeta describes how Team is read from public.teams.
var teamMeta = orm.EntityMeta[Team]{
	Table:  orm.TableID{Schema: "public", Name: "teams"},
	Source: teamsSource,
	Columns: []orm.ColumnMeta{
		{Name: "slug", Field: "Slug", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
	},
	Dest:  teamDest,
	Value: teamValue,
}

// teamDest returns a pointer to the field holding column idx of public.teams.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func teamDest(e *Team, idx int) any {
	switch idx {
	case 0:
		return &e.Slug
	case 1:
		return &e.Name
	default:
		return nil
	}
}

// teamValue returns the value of the field holding column idx of public.teams.
//
// It is the counterpart of teamDest and is written the same way, so an
// insert reads the entity without reflection either.
func teamValue(e *Team, idx int) any {
	switch idx {
	case 0:
		return e.Slug
	case 1:
		return e.Name
	default:
		return nil
	}
}

// tenantMeta describes how Tenant is read from public.tenants.
var tenantMeta = orm.EntityMeta[Tenant]{
	Table:  orm.TableID{Schema: "public", Name: "tenants"},
	Source: tenantsSource,
	Columns: []orm.ColumnMeta{
		{Name: "code", Field: "Code", NotNull: true},
		{Name: "region", Field: "Region", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
	},
	Dest:  tenantDest,
	Value: tenantValue,
}

// tenantDest returns a pointer to the field holding column idx of public.tenants.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func tenantDest(e *Tenant, idx int) any {
	switch idx {
	case 0:
		return &e.Code
	case 1:
		return &e.Region
	case 2:
		return &e.Name
	default:
		return nil
	}
}

// tenantValue returns the value of the field holding column idx of public.tenants.
//
// It is the counterpart of tenantDest and is written the same way, so an
// insert reads the entity without reflection either.
func tenantValue(e *Tenant, idx int) any {
	switch idx {
	case 0:
		return e.Code
	case 1:
		return e.Region
	case 2:
		return e.Name
	default:
		return nil
	}
}

// userMeta describes how User is read from public.users.
var userMeta = orm.EntityMeta[User]{
	Table:  orm.TableID{Schema: "public", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "age", Field: "Age", NotNull: true},
		{Name: "active", Field: "Active", NotNull: true, HasDefault: true},
		{Name: "state", Field: "State", NotNull: true, HasDefault: true},
		{Name: "nickname", Field: "Nickname"},
		{Name: "score", Field: "Score"},
		{Name: "tags", Field: "Tags", NotNull: true, HasDefault: true},
		{Name: "settings", Field: "Settings", NotNull: true, HasDefault: true},
		{Name: "avatar", Field: "Avatar"},
		{Name: "manager_id", Field: "ManagerID"},
		{Name: "bio", Field: "Bio"},
		{Name: "visits", Field: "Visits"},
		{Name: "deleted_at", Field: "DeletedAt"},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
		{Name: "slug", Field: "Slug", Generated: true},
		{Name: "metadata", Field: "Metadata"},
	},
	Dest:  userDest,
	Value: userValue,
}

// userDest returns a pointer to the field holding column idx of public.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userDest(e *User, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.Age
	case 3:
		return &e.Active
	case 4:
		return &e.State
	case 5:
		return &e.Nickname
	case 6:
		return &e.Score
	case 7:
		return &e.Tags
	case 8:
		return &e.Settings
	case 9:
		return &e.Avatar
	case 10:
		return &e.ManagerID
	case 11:
		return &e.Bio
	case 12:
		return &e.Visits
	case 13:
		return &e.DeletedAt
	case 14:
		return &e.CreatedAt
	case 15:
		return &e.Slug
	case 16:
		return &e.Metadata
	default:
		return nil
	}
}

// userValue returns the value of the field holding column idx of public.users.
//
// It is the counterpart of userDest and is written the same way, so an
// insert reads the entity without reflection either.
func userValue(e *User, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.Age
	case 3:
		return e.Active
	case 4:
		return e.State
	case 5:
		return e.Nickname
	case 6:
		return e.Score
	case 7:
		return e.Tags
	case 8:
		return e.Settings
	case 9:
		return e.Avatar
	case 10:
		return e.ManagerID
	case 11:
		return e.Bio
	case 12:
		return e.Visits
	case 13:
		return e.DeletedAt
	case 14:
		return e.CreatedAt
	case 15:
		return e.Slug
	case 16:
		return e.Metadata
	default:
		return nil
	}
}
