// Code generated by orm. DO NOT EDIT.

package gendemo

import (
	"net"
	"net/netip"
	"time"

	"github.com/AlexAli29/orm"
)

// articlesSource is the occurrence of public.articles that Articles reads from.
var articlesSource = orm.NewSource("public", "articles")

// articleTable holds one typed descriptor per mapped column of public.articles.
type articleTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Article, int64]
	Title  orm.TextCol[Article]
	Body   orm.TextCol[Article]
	Search orm.NullCol[Article, orm.TSVector]
}

// newArticleTable builds the descriptors for one occurrence of public.articles.
func newArticleTable(src *orm.Source) articleTable {
	return articleTable{
		src:    src,
		ID:     orm.NewOrdCol[Article, int64](src, "id"),
		Title:  orm.NewTextCol[Article](src, "title"),
		Body:   orm.NewTextCol[Article](src, "body"),
		Search: orm.NewNullCol[Article, orm.TSVector](src, "search"),
	}
}

// Articles addresses the columns of public.articles.
var Articles = newArticleTable(articlesSource)

// As returns descriptors for a second occurrence of public.articles under
// alias, leaving Articles untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t articleTable) As(alias string) articleTable { return newArticleTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t articleTable) Source() *orm.Source { return t.src }

// avatarsSource is the occurrence of public.avatars that Avatars reads from.
var avatarsSource = orm.NewSource("public", "avatars")

// avatarTable holds one typed descriptor per mapped column of public.avatars.
type avatarTable struct {
	src *orm.Source
	ID  orm.OrdCol[Avatar, int64]
	URL orm.TextCol[Avatar]
}

// newAvatarTable builds the descriptors for one occurrence of public.avatars.
func newAvatarTable(src *orm.Source) avatarTable {
	return avatarTable{
		src: src,
		ID:  orm.NewOrdCol[Avatar, int64](src, "id"),
		URL: orm.NewTextCol[Avatar](src, "url"),
	}
}

// Avatars addresses the columns of public.avatars.
var Avatars = newAvatarTable(avatarsSource)

// As returns descriptors for a second occurrence of public.avatars under
// alias, leaving Avatars untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t avatarTable) As(alias string) avatarTable { return newAvatarTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t avatarTable) Source() *orm.Source { return t.src }

// bookingsSource is the occurrence of public.bookings that Bookings reads from.
var bookingsSource = orm.NewSource("public", "bookings")

// bookingTable holds one typed descriptor per mapped column of public.bookings.
type bookingTable struct {
	src      *orm.Source
	ID       orm.OrdCol[Booking, int64]
	Room     orm.TextCol[Booking]
	StartsAt orm.OrdCol[Booking, time.Time]
	Period   orm.RangeCol[Booking, time.Time]
	Stay     orm.RangeCol[Booking, time.Time]
	Shift    orm.RangeCol[Booking, time.Time]
	Quota    orm.RangeCol[Booking, int32]
	Span     orm.RangeCol[Booking, int64]
	Revised  orm.NullRangeCol[Booking, time.Time]
	Lease    orm.OrdCol[Booking, orm.Interval]
	Grace    orm.NullOrdCol[Booking, orm.Interval]
	Holds    orm.MultirangeCol[Booking, time.Time]
	Slots    orm.NullMultirangeCol[Booking, int32]
}

// newBookingTable builds the descriptors for one occurrence of public.bookings.
func newBookingTable(src *orm.Source) bookingTable {
	return bookingTable{
		src:      src,
		ID:       orm.NewOrdCol[Booking, int64](src, "id"),
		Room:     orm.NewTextCol[Booking](src, "room"),
		StartsAt: orm.NewOrdCol[Booking, time.Time](src, "starts_at"),
		Period:   orm.NewRangeCol[Booking, time.Time](src, "period", "tstzrange", "timestamptz"),
		Stay:     orm.NewRangeCol[Booking, time.Time](src, "stay", "daterange", "date"),
		Shift:    orm.NewRangeCol[Booking, time.Time](src, "shift", "tsrange", "timestamp"),
		Quota:    orm.NewRangeCol[Booking, int32](src, "quota", "int4range", "int4"),
		Span:     orm.NewRangeCol[Booking, int64](src, "span", "int8range", "int8"),
		Revised:  orm.NewNullRangeCol[Booking, time.Time](src, "revised", "tstzrange", "timestamptz"),
		Lease:    orm.NewOrdCol[Booking, orm.Interval](src, "lease"),
		Grace:    orm.NewNullOrdCol[Booking, orm.Interval](src, "grace"),
		Holds:    orm.NewMultirangeCol[Booking, time.Time](src, "holds", "tstzmultirange", "tstzrange", "timestamptz"),
		Slots:    orm.NewNullMultirangeCol[Booking, int32](src, "slots", "int4multirange", "int4range", "int4"),
	}
}

// Bookings addresses the columns of public.bookings.
var Bookings = newBookingTable(bookingsSource)

// As returns descriptors for a second occurrence of public.bookings under
// alias, leaving Bookings untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t bookingTable) As(alias string) bookingTable { return newBookingTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t bookingTable) Source() *orm.Source { return t.src }

// branchesSource is the occurrence of public.branches that Branches reads from.
var branchesSource = orm.NewSource("public", "branches")

// branchTable holds one typed descriptor per mapped column of public.branches, and one
// per relation reconciliation proved.
type branchTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Branch, int64]
	Label  orm.TextCol[Branch]
	Code   orm.TextCol[Branch]
	Region orm.TextCol[Branch]
	Tenant orm.Rel[Branch, Tenant]
}

// newBranchTable builds the descriptors for one occurrence of public.branches.
func newBranchTable(src *orm.Source) branchTable {
	return branchTable{
		src:    src,
		ID:     orm.NewOrdCol[Branch, int64](src, "id"),
		Label:  orm.NewTextCol[Branch](src, "label"),
		Code:   orm.NewTextCol[Branch](src, "branch_code"),
		Region: orm.NewTextCol[Branch](src, "branch_region"),
		Tenant: orm.NewOneRel(orm.OneRelSpec[Branch, Tenant]{
			Name:        "Tenant",
			Parent:      src,
			Target:      tenantsSource,
			Keys:        branchTenantKeys,
			Columns:     branchTenantColumns,
			Bind:        branchTenantBind,
			ExtractKeys: branchTenantLoadKeys,
			Dest:        tenantRelDest,
			Attach:      branchTenantAttach,
			Refs:        branchTenantRefs,
		}),
	}
}

// Branches addresses the columns of public.branches.
var Branches = newBranchTable(branchesSource)

// As returns descriptors for a second occurrence of public.branches under
// alias, leaving Branches untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t branchTable) As(alias string) branchTable { return newBranchTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t branchTable) Source() *orm.Source { return t.src }

// branchEventsSource is the occurrence of public.branch_events that BranchEvents reads from.
var branchEventsSource = orm.NewSource("public", "branch_events")

// branchEventTable holds one typed descriptor per mapped column of public.branch_events.
type branchEventTable struct {
	src    *orm.Source
	ID     orm.OrdCol[BranchEvent, int64]
	Label  orm.TextCol[BranchEvent]
	Code   orm.TextCol[BranchEvent]
	Region orm.TextCol[BranchEvent]
}

// newBranchEventTable builds the descriptors for one occurrence of public.branch_events.
func newBranchEventTable(src *orm.Source) branchEventTable {
	return branchEventTable{
		src:    src,
		ID:     orm.NewOrdCol[BranchEvent, int64](src, "id"),
		Label:  orm.NewTextCol[BranchEvent](src, "label"),
		Code:   orm.NewTextCol[BranchEvent](src, "event_code"),
		Region: orm.NewTextCol[BranchEvent](src, "event_region"),
	}
}

// BranchEvents addresses the columns of public.branch_events.
var BranchEvents = newBranchEventTable(branchEventsSource)

// As returns descriptors for a second occurrence of public.branch_events under
// alias, leaving BranchEvents untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t branchEventTable) As(alias string) branchEventTable {
	return newBranchEventTable(t.src.As(alias))
}

// Source returns the occurrence these descriptors qualify against.
func (t branchEventTable) Source() *orm.Source { return t.src }

// categoriesSource is the occurrence of public.categories that Categories reads from.
var categoriesSource = orm.NewSource("public", "categories")

// categoryTable holds one typed descriptor per mapped column of public.categories.
type categoryTable struct {
	src  *orm.Source
	ID   orm.OrdCol[Category, int64]
	Name orm.TextCol[Category]
}

// newCategoryTable builds the descriptors for one occurrence of public.categories.
func newCategoryTable(src *orm.Source) categoryTable {
	return categoryTable{
		src:  src,
		ID:   orm.NewOrdCol[Category, int64](src, "id"),
		Name: orm.NewTextCol[Category](src, "name"),
	}
}

// Categories addresses the columns of public.categories.
var Categories = newCategoryTable(categoriesSource)

// As returns descriptors for a second occurrence of public.categories under
// alias, leaving Categories untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t categoryTable) As(alias string) categoryTable { return newCategoryTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t categoryTable) Source() *orm.Source { return t.src }

// commentsSource is the occurrence of public.comments that Comments reads from.
var commentsSource = orm.NewSource("public", "comments")

// commentTable holds one typed descriptor per mapped column of public.comments, and one
// per relation reconciliation proved.
type commentTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Comment, int64]
	Body      orm.TextCol[Comment]
	Visible   orm.Col[Comment, bool]
	Score     orm.OrdCol[Comment, int32]
	CreatedAt orm.OrdCol[Comment, time.Time]
	Author    orm.Rel[Comment, User]
	Reactions orm.Rel[Comment, Reaction]
}

// newCommentTable builds the descriptors for one occurrence of public.comments.
func newCommentTable(src *orm.Source) commentTable {
	return commentTable{
		src:       src,
		ID:        orm.NewOrdCol[Comment, int64](src, "id"),
		Body:      orm.NewTextCol[Comment](src, "body"),
		Visible:   orm.NewCol[Comment, bool](src, "visible"),
		Score:     orm.NewOrdCol[Comment, int32](src, "score"),
		CreatedAt: orm.NewOrdCol[Comment, time.Time](src, "created_at"),
		Author: orm.NewOneRel(orm.OneRelSpec[Comment, User]{
			Name:       "Author",
			Parent:     src,
			Target:     usersSource,
			Keys:       commentAuthorKeys,
			Columns:    commentAuthorColumns,
			Bind:       commentAuthorBind,
			AuxColumns: commentAuthorAuxColumns,
			NewAux:     newCommentAuthorAux,
			Dest:       userRelDest,
			Attach:     commentAuthorAttach,
			Refs:       commentAuthorRefs,
		}),
		Reactions: orm.NewManyRel(orm.ManyRelSpec[Comment, Reaction]{
			Name:        "Reactions",
			Parent:      src,
			Target:      reactionsSource,
			Keys:        commentReactionsKeys,
			Columns:     commentReactionsColumns,
			ExtractKeys: commentReactionsLoadKeys,
			Dest:        reactionRelDest,
			Attach:      commentReactionsAttach,
			Refs:        commentReactionsRefs,
		}),
	}
}

// Comments addresses the columns of public.comments.
var Comments = newCommentTable(commentsSource)

// As returns descriptors for a second occurrence of public.comments under
// alias, leaving Comments untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t commentTable) As(alias string) commentTable { return newCommentTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t commentTable) Source() *orm.Source { return t.src }

// documentsSource is the occurrence of public.documents that Documents reads from.
var documentsSource = orm.NewSource("public", "documents")

// documentTable holds one typed descriptor per mapped column of public.documents, and one
// per relation reconciliation proved.
type documentTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Document, int64]
	Title     orm.TextCol[Document]
	CreatorID orm.OrdCol[Document, int64]
	Creator   orm.Rel[Document, User]
	Editor    orm.Rel[Document, User]
}

// newDocumentTable builds the descriptors for one occurrence of public.documents.
func newDocumentTable(src *orm.Source) documentTable {
	return documentTable{
		src:       src,
		ID:        orm.NewOrdCol[Document, int64](src, "id"),
		Title:     orm.NewTextCol[Document](src, "title"),
		CreatorID: orm.NewOrdCol[Document, int64](src, "creator_id"),
		Creator: orm.NewOneRel(orm.OneRelSpec[Document, User]{
			Name:        "Creator",
			Parent:      src,
			Target:      usersSource,
			Keys:        documentCreatorKeys,
			Columns:     documentCreatorColumns,
			Bind:        documentCreatorBind,
			ExtractKeys: documentCreatorLoadKeys,
			Dest:        userRelDest,
			Attach:      documentCreatorAttach,
			Refs:        documentCreatorRefs,
		}),
		Editor: orm.NewOneRel(orm.OneRelSpec[Document, User]{
			Name:       "Editor",
			Parent:     src,
			Target:     usersSource,
			Keys:       documentEditorKeys,
			Columns:    documentEditorColumns,
			Bind:       documentEditorBind,
			AuxColumns: documentEditorAuxColumns,
			NewAux:     newDocumentEditorAux,
			Dest:       userRelDest,
			Attach:     documentEditorAttach,
			Refs:       documentEditorRefs,
		}),
	}
}

// Documents addresses the columns of public.documents.
var Documents = newDocumentTable(documentsSource)

// As returns descriptors for a second occurrence of public.documents under
// alias, leaving Documents untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t documentTable) As(alias string) documentTable { return newDocumentTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t documentTable) Source() *orm.Source { return t.src }

// membersSource is the occurrence of public.members that Members reads from.
var membersSource = orm.NewSource("public", "members")

// memberTable holds one typed descriptor per mapped column of public.members, and one
// per relation reconciliation proved.
type memberTable struct {
	src      *orm.Source
	ID       orm.OrdCol[Member, int64]
	TeamSlug orm.TextCol[Member]
	Nickname orm.TextCol[Member]
	Team     orm.Rel[Member, Team]
}

// newMemberTable builds the descriptors for one occurrence of public.members.
func newMemberTable(src *orm.Source) memberTable {
	return memberTable{
		src:      src,
		ID:       orm.NewOrdCol[Member, int64](src, "id"),
		TeamSlug: orm.NewTextCol[Member](src, "team_slug"),
		Nickname: orm.NewTextCol[Member](src, "nickname"),
		Team: orm.NewOneRel(orm.OneRelSpec[Member, Team]{
			Name:        "Team",
			Parent:      src,
			Target:      teamsSource,
			Keys:        memberTeamKeys,
			Columns:     memberTeamColumns,
			Bind:        memberTeamBind,
			ExtractKeys: memberTeamLoadKeys,
			Dest:        teamRelDest,
			Attach:      memberTeamAttach,
			Refs:        memberTeamRefs,
		}),
	}
}

// Members addresses the columns of public.members.
var Members = newMemberTable(membersSource)

// As returns descriptors for a second occurrence of public.members under
// alias, leaving Members untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t memberTable) As(alias string) memberTable { return newMemberTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t memberTable) Source() *orm.Source { return t.src }

// networksSource is the occurrence of public.networks that Networks reads from.
var networksSource = orm.NewSource("public", "networks")

// networkTable holds one typed descriptor per mapped column of public.networks.
type networkTable struct {
	src      *orm.Source
	ID       orm.OrdCol[Network, int64]
	Label    orm.TextCol[Network]
	Subnet   orm.OrdCol[Network, netip.Prefix]
	Host     orm.OrdCol[Network, netip.Prefix]
	Fallback orm.NullOrdCol[Network, netip.Prefix]
	Hardware orm.OrdCol[Network, net.HardwareAddr]
}

// newNetworkTable builds the descriptors for one occurrence of public.networks.
func newNetworkTable(src *orm.Source) networkTable {
	return networkTable{
		src:      src,
		ID:       orm.NewOrdCol[Network, int64](src, "id"),
		Label:    orm.NewTextCol[Network](src, "label"),
		Subnet:   orm.NewOrdCol[Network, netip.Prefix](src, "subnet"),
		Host:     orm.NewOrdCol[Network, netip.Prefix](src, "host"),
		Fallback: orm.NewNullOrdCol[Network, netip.Prefix](src, "fallback"),
		Hardware: orm.NewOrdCol[Network, net.HardwareAddr](src, "hardware"),
	}
}

// Networks addresses the columns of public.networks.
var Networks = newNetworkTable(networksSource)

// As returns descriptors for a second occurrence of public.networks under
// alias, leaving Networks untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t networkTable) As(alias string) networkTable { return newNetworkTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t networkTable) Source() *orm.Source { return t.src }

// postsSource is the occurrence of public.posts that Posts reads from.
var postsSource = orm.NewSource("public", "posts")

// postTable holds one typed descriptor per mapped column of public.posts, and one
// per relation reconciliation proved.
type postTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Post, int64]
	AuthorID  orm.NullOrdCol[Post, int64]
	Title     orm.TextCol[Post]
	Published orm.Col[Post, bool]
	Score     orm.OrdCol[Post, int32]
	CreatedAt orm.OrdCol[Post, time.Time]
	Author    orm.Rel[Post, User]
	Category  orm.Rel[Post, Category]
	Comments  orm.Rel[Post, Comment]
}

// newPostTable builds the descriptors for one occurrence of public.posts.
func newPostTable(src *orm.Source) postTable {
	return postTable{
		src:       src,
		ID:        orm.NewOrdCol[Post, int64](src, "id"),
		AuthorID:  orm.NewNullOrdCol[Post, int64](src, "author_id"),
		Title:     orm.NewTextCol[Post](src, "title"),
		Published: orm.NewCol[Post, bool](src, "published"),
		Score:     orm.NewOrdCol[Post, int32](src, "score"),
		CreatedAt: orm.NewOrdCol[Post, time.Time](src, "created_at"),
		Author: orm.NewOneRel(orm.OneRelSpec[Post, User]{
			Name:        "Author",
			Parent:      src,
			Target:      usersSource,
			Keys:        postAuthorKeys,
			Columns:     postAuthorColumns,
			Bind:        postAuthorBind,
			ExtractKeys: postAuthorLoadKeys,
			Dest:        userRelDest,
			Attach:      postAuthorAttach,
			Refs:        postAuthorRefs,
		}),
		Category: orm.NewOneRel(orm.OneRelSpec[Post, Category]{
			Name:       "Category",
			Parent:     src,
			Target:     categoriesSource,
			Keys:       postCategoryKeys,
			Columns:    postCategoryColumns,
			Bind:       postCategoryBind,
			AuxColumns: postCategoryAuxColumns,
			NewAux:     newPostCategoryAux,
			Dest:       categoryRelDest,
			Attach:     postCategoryAttach,
			Refs:       postCategoryRefs,
		}),
		Comments: orm.NewManyRel(orm.ManyRelSpec[Post, Comment]{
			Name:        "Comments",
			Parent:      src,
			Target:      commentsSource,
			Keys:        postCommentsKeys,
			Columns:     postCommentsColumns,
			ExtractKeys: postCommentsLoadKeys,
			Dest:        commentRelDest,
			Attach:      postCommentsAttach,
			Refs:        postCommentsRefs,
		}),
	}
}

// Posts addresses the columns of public.posts.
var Posts = newPostTable(postsSource)

// As returns descriptors for a second occurrence of public.posts under
// alias, leaving Posts untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t postTable) As(alias string) postTable { return newPostTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t postTable) Source() *orm.Source { return t.src }

// profilesSource is the occurrence of public.profiles that Profiles reads from.
var profilesSource = orm.NewSource("public", "profiles")

// profileTable holds one typed descriptor per mapped column of public.profiles, and one
// per relation reconciliation proved.
type profileTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Profile, int64]
	UserID orm.OrdCol[Profile, int64]
	Bio    orm.NullTextCol[Profile]
	Avatar orm.Rel[Profile, Avatar]
}

// newProfileTable builds the descriptors for one occurrence of public.profiles.
func newProfileTable(src *orm.Source) profileTable {
	return profileTable{
		src:    src,
		ID:     orm.NewOrdCol[Profile, int64](src, "id"),
		UserID: orm.NewOrdCol[Profile, int64](src, "user_id"),
		Bio:    orm.NewNullTextCol[Profile](src, "bio"),
		Avatar: orm.NewOneRel(orm.OneRelSpec[Profile, Avatar]{
			Name:       "Avatar",
			Parent:     src,
			Target:     avatarsSource,
			Keys:       profileAvatarKeys,
			Columns:    profileAvatarColumns,
			Bind:       profileAvatarBind,
			AuxColumns: profileAvatarAuxColumns,
			NewAux:     newProfileAvatarAux,
			Dest:       avatarRelDest,
			Attach:     profileAvatarAttach,
			Refs:       profileAvatarRefs,
		}),
	}
}

// Profiles addresses the columns of public.profiles.
var Profiles = newProfileTable(profilesSource)

// As returns descriptors for a second occurrence of public.profiles under
// alias, leaving Profiles untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t profileTable) As(alias string) profileTable { return newProfileTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t profileTable) Source() *orm.Source { return t.src }

// reactionsSource is the occurrence of public.reactions that Reactions reads from.
var reactionsSource = orm.NewSource("public", "reactions")

// reactionTable holds one typed descriptor per mapped column of public.reactions, and one
// per relation reconciliation proved.
type reactionTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Reaction, int64]
	Kind   orm.TextCol[Reaction]
	Author orm.Rel[Reaction, User]
}

// newReactionTable builds the descriptors for one occurrence of public.reactions.
func newReactionTable(src *orm.Source) reactionTable {
	return reactionTable{
		src:  src,
		ID:   orm.NewOrdCol[Reaction, int64](src, "id"),
		Kind: orm.NewTextCol[Reaction](src, "kind"),
		Author: orm.NewOneRel(orm.OneRelSpec[Reaction, User]{
			Name:       "Author",
			Parent:     src,
			Target:     usersSource,
			Keys:       reactionAuthorKeys,
			Columns:    reactionAuthorColumns,
			Bind:       reactionAuthorBind,
			AuxColumns: reactionAuthorAuxColumns,
			NewAux:     newReactionAuthorAux,
			Dest:       userRelDest,
			Attach:     reactionAuthorAttach,
			Refs:       reactionAuthorRefs,
		}),
	}
}

// Reactions addresses the columns of public.reactions.
var Reactions = newReactionTable(reactionsSource)

// As returns descriptors for a second occurrence of public.reactions under
// alias, leaving Reactions untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t reactionTable) As(alias string) reactionTable { return newReactionTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t reactionTable) Source() *orm.Source { return t.src }

// teamsSource is the occurrence of public.teams that Teams reads from.
var teamsSource = orm.NewSource("public", "teams")

// teamTable holds one typed descriptor per mapped column of public.teams, and one
// per relation reconciliation proved.
type teamTable struct {
	src     *orm.Source
	Slug    orm.TextCol[Team]
	Name    orm.TextCol[Team]
	Members orm.Rel[Team, Member]
}

// newTeamTable builds the descriptors for one occurrence of public.teams.
func newTeamTable(src *orm.Source) teamTable {
	return teamTable{
		src:  src,
		Slug: orm.NewTextCol[Team](src, "slug"),
		Name: orm.NewTextCol[Team](src, "name"),
		Members: orm.NewManyRel(orm.ManyRelSpec[Team, Member]{
			Name:        "Members",
			Parent:      src,
			Target:      membersSource,
			Keys:        teamMembersKeys,
			Columns:     teamMembersColumns,
			ExtractKeys: teamMembersLoadKeys,
			Dest:        memberRelDest,
			Attach:      teamMembersAttach,
			Refs:        teamMembersRefs,
		}),
	}
}

// Teams addresses the columns of public.teams.
var Teams = newTeamTable(teamsSource)

// As returns descriptors for a second occurrence of public.teams under
// alias, leaving Teams untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t teamTable) As(alias string) teamTable { return newTeamTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t teamTable) Source() *orm.Source { return t.src }

// tenantsSource is the occurrence of public.tenants that Tenants reads from.
var tenantsSource = orm.NewSource("public", "tenants")

// tenantTable holds one typed descriptor per mapped column of public.tenants, and one
// per relation reconciliation proved.
type tenantTable struct {
	src      *orm.Source
	Code     orm.TextCol[Tenant]
	Region   orm.TextCol[Tenant]
	Name     orm.TextCol[Tenant]
	Branches orm.Rel[Tenant, Branch]
	Events   orm.Rel[Tenant, BranchEvent]
}

// newTenantTable builds the descriptors for one occurrence of public.tenants.
func newTenantTable(src *orm.Source) tenantTable {
	return tenantTable{
		src:    src,
		Code:   orm.NewTextCol[Tenant](src, "code"),
		Region: orm.NewTextCol[Tenant](src, "region"),
		Name:   orm.NewTextCol[Tenant](src, "name"),
		Branches: orm.NewManyRel(orm.ManyRelSpec[Tenant, Branch]{
			Name:        "Branches",
			Parent:      src,
			Target:      branchesSource,
			Keys:        tenantBranchesKeys,
			Columns:     tenantBranchesColumns,
			ExtractKeys: tenantBranchesLoadKeys,
			Dest:        branchRelDest,
			Attach:      tenantBranchesAttach,
			Refs:        tenantBranchesRefs,
		}),
		Events: orm.NewManyRel(orm.ManyRelSpec[Tenant, BranchEvent]{
			Name:        "Events",
			Parent:      src,
			Target:      branchEventsSource,
			Keys:        tenantEventsKeys,
			Columns:     tenantEventsColumns,
			ExtractKeys: tenantEventsLoadKeys,
			Dest:        branchEventRelDest,
			Attach:      tenantEventsAttach,
			Refs:        tenantEventsRefs,
		}),
	}
}

// Tenants addresses the columns of public.tenants.
var Tenants = newTenantTable(tenantsSource)

// As returns descriptors for a second occurrence of public.tenants under
// alias, leaving Tenants untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t tenantTable) As(alias string) tenantTable { return newTenantTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t tenantTable) Source() *orm.Source { return t.src }

// usersSource is the occurrence of public.users that Users reads from.
var usersSource = orm.NewSource("public", "users")

// userTable holds one typed descriptor per mapped column of public.users, and one
// per relation reconciliation proved.
type userTable struct {
	src       *orm.Source
	ID        orm.OrdCol[User, int64]
	Email     orm.TextCol[User]
	Age       orm.OrdCol[User, int32]
	Active    orm.Col[User, bool]
	State     orm.OrdCol[User, UserState]
	Nickname  orm.NullTextCol[User]
	Score     orm.NullOrdCol[User, float64]
	Tags      orm.Col[User, []string]
	Settings  orm.Col[User, map[string]any]
	Avatar    orm.NullCol[User, []byte]
	ManagerID orm.NullOrdCol[User, int64]
	Bio       orm.NullTextCol[User]
	Visits    orm.NullOrdCol[User, int64]
	DeletedAt orm.NullOrdCol[User, time.Time]
	CreatedAt orm.OrdCol[User, time.Time]
	Slug      orm.NullTextCol[User]
	Metadata  orm.NullCol[User, map[string]any]
	Posts     orm.Rel[User, Post]
	Profile   orm.Rel[User, Profile]
	Manager   orm.Rel[User, User]
	Reports   orm.Rel[User, User]
}

// newUserTable builds the descriptors for one occurrence of public.users.
func newUserTable(src *orm.Source) userTable {
	return userTable{
		src:       src,
		ID:        orm.NewOrdCol[User, int64](src, "id"),
		Email:     orm.NewTextCol[User](src, "email"),
		Age:       orm.NewOrdCol[User, int32](src, "age"),
		Active:    orm.NewCol[User, bool](src, "active"),
		State:     orm.NewOrdCol[User, UserState](src, "state"),
		Nickname:  orm.NewNullTextCol[User](src, "nickname"),
		Score:     orm.NewNullOrdCol[User, float64](src, "score"),
		Tags:      orm.NewCol[User, []string](src, "tags"),
		Settings:  orm.NewCol[User, map[string]any](src, "settings"),
		Avatar:    orm.NewNullCol[User, []byte](src, "avatar"),
		ManagerID: orm.NewNullOrdCol[User, int64](src, "manager_id"),
		Bio:       orm.NewNullTextCol[User](src, "bio"),
		Visits:    orm.NewNullOrdCol[User, int64](src, "visits"),
		DeletedAt: orm.NewNullOrdCol[User, time.Time](src, "deleted_at"),
		CreatedAt: orm.NewOrdCol[User, time.Time](src, "created_at"),
		Slug:      orm.NewNullTextCol[User](src, "slug"),
		Metadata:  orm.NewNullCol[User, map[string]any](src, "metadata"),
		Posts: orm.NewManyRel(orm.ManyRelSpec[User, Post]{
			Name:        "Posts",
			Parent:      src,
			Target:      postsSource,
			Keys:        userPostsKeys,
			Columns:     userPostsColumns,
			ExtractKeys: userPostsLoadKeys,
			Dest:        postRelDest,
			Attach:      userPostsAttach,
			Refs:        userPostsRefs,
		}),
		Profile: orm.NewOneRel(orm.OneRelSpec[User, Profile]{
			Name:        "Profile",
			Parent:      src,
			Target:      profilesSource,
			Keys:        userProfileKeys,
			Columns:     userProfileColumns,
			Bind:        userProfileBind,
			ExtractKeys: userProfileLoadKeys,
			Dest:        profileRelDest,
			Attach:      userProfileAttach,
			Refs:        userProfileRefs,
		}),
		Manager: orm.NewOneRel(orm.OneRelSpec[User, User]{
			Name:        "Manager",
			Parent:      src,
			Target:      usersSource,
			Keys:        userManagerKeys,
			Columns:     userManagerColumns,
			Bind:        userManagerBind,
			ExtractKeys: userManagerLoadKeys,
			Dest:        userRelDest,
			Attach:      userManagerAttach,
			Refs:        userManagerRefs,
		}),
		Reports: orm.NewManyRel(orm.ManyRelSpec[User, User]{
			Name:        "Reports",
			Parent:      src,
			Target:      usersSource,
			Keys:        userReportsKeys,
			Columns:     userReportsColumns,
			ExtractKeys: userReportsLoadKeys,
			Dest:        userRelDest,
			Attach:      userReportsAttach,
			Refs:        userReportsRefs,
		}),
	}
}

// Users addresses the columns of public.users.
var Users = newUserTable(usersSource)

// As returns descriptors for a second occurrence of public.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userTable) As(alias string) userTable { return newUserTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userTable) Source() *orm.Source { return t.src }
