// Code generated by orm. DO NOT EDIT.

package gendemo

import (
	"database/sql"
	"time"

	"github.com/AlexAli29/orm"
)

// avatarNulls mirrors Avatar with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Avatar would fail on those rather than report an absent
// relation, so the row lands here first.
type avatarNulls struct {
	ID  *int64
	URL *string
}

// avatarNullDest returns scan destinations for every column of public.avatars.
func avatarNullDest(n *avatarNulls) []any {
	return []any{
		&n.ID,
		&n.URL,
	}
}

// avatarFromNulls rebuilds Avatar from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func avatarFromNulls(n *avatarNulls) (Avatar, bool) {
	if n.ID == nil {
		return Avatar{}, false
	}
	return Avatar{
		ID:  *n.ID,
		URL: *n.URL,
	}, true
}

// categoryNulls mirrors Category with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Category would fail on those rather than report an absent
// relation, so the row lands here first.
type categoryNulls struct {
	ID   *int64
	Name *string
}

// categoryNullDest returns scan destinations for every column of public.categories.
func categoryNullDest(n *categoryNulls) []any {
	return []any{
		&n.ID,
		&n.Name,
	}
}

// categoryFromNulls rebuilds Category from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func categoryFromNulls(n *categoryNulls) (Category, bool) {
	if n.ID == nil {
		return Category{}, false
	}
	return Category{
		ID:   *n.ID,
		Name: *n.Name,
	}, true
}

// profileNulls mirrors Profile with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Profile would fail on those rather than report an absent
// relation, so the row lands here first.
type profileNulls struct {
	ID     *int64
	UserID *int64
	Bio    *string
}

// profileNullDest returns scan destinations for every column of public.profiles.
func profileNullDest(n *profileNulls) []any {
	return []any{
		&n.ID,
		&n.UserID,
		&n.Bio,
	}
}

// profileFromNulls rebuilds Profile from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func profileFromNulls(n *profileNulls) (Profile, bool) {
	if n.ID == nil {
		return Profile{}, false
	}
	return Profile{
		ID:     *n.ID,
		UserID: *n.UserID,
		Bio:    n.Bio,
	}, true
}

// teamNulls mirrors Team with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Team would fail on those rather than report an absent
// relation, so the row lands here first.
type teamNulls struct {
	Slug *string
	Name *string
}

// teamNullDest returns scan destinations for every column of public.teams.
func teamNullDest(n *teamNulls) []any {
	return []any{
		&n.Slug,
		&n.Name,
	}
}

// teamFromNulls rebuilds Team from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func teamFromNulls(n *teamNulls) (Team, bool) {
	if n.Slug == nil {
		return Team{}, false
	}
	return Team{
		Slug: *n.Slug,
		Name: *n.Name,
	}, true
}

// tenantNulls mirrors Tenant with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Tenant would fail on those rather than report an absent
// relation, so the row lands here first.
type tenantNulls struct {
	Code   *string
	Region *string
	Name   *string
}

// tenantNullDest returns scan destinations for every column of public.tenants.
func tenantNullDest(n *tenantNulls) []any {
	return []any{
		&n.Code,
		&n.Region,
		&n.Name,
	}
}

// tenantFromNulls rebuilds Tenant from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func tenantFromNulls(n *tenantNulls) (Tenant, bool) {
	if n.Region == nil || n.Code == nil {
		return Tenant{}, false
	}
	return Tenant{
		Code:   *n.Code,
		Region: *n.Region,
		Name:   *n.Name,
	}, true
}

// userNulls mirrors User with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into User would fail on those rather than report an absent
// relation, so the row lands here first.
type userNulls struct {
	ID        *int64
	Email     *string
	Age       *int32
	Active    *bool
	State     *UserState
	Nickname  *string
	Score     *float64
	Tags      []string
	Settings  map[string]any
	Avatar    *[]byte
	ManagerID *int64
	Bio       sql.Null[string]
	Visits    sql.NullInt64
	DeletedAt *time.Time
	CreatedAt *time.Time
	Slug      *string
	Metadata  *map[string]any
}

// userNullDest returns scan destinations for every column of public.users.
func userNullDest(n *userNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.Age,
		&n.Active,
		&n.State,
		&n.Nickname,
		&n.Score,
		&n.Tags,
		&n.Settings,
		&n.Avatar,
		&n.ManagerID,
		&n.Bio,
		&n.Visits,
		&n.DeletedAt,
		&n.CreatedAt,
		&n.Slug,
		&n.Metadata,
	}
}

// userFromNulls rebuilds User from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func userFromNulls(n *userNulls) (User, bool) {
	if n.ID == nil {
		return User{}, false
	}
	return User{
		ID:        *n.ID,
		Email:     *n.Email,
		Age:       *n.Age,
		Active:    *n.Active,
		State:     *n.State,
		Nickname:  n.Nickname,
		Score:     n.Score,
		Tags:      n.Tags,
		Settings:  n.Settings,
		Avatar:    n.Avatar,
		ManagerID: n.ManagerID,
		Bio:       n.Bio,
		Visits:    n.Visits,
		DeletedAt: n.DeletedAt,
		CreatedAt: *n.CreatedAt,
		Slug:      n.Slug,
		Metadata:  n.Metadata,
	}, true
}

// avatarRelDest returns scan destinations for a Avatar loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func avatarRelDest(t *Avatar) []any {
	dest := make([]any, 2)
	for i := range dest {
		dest[i] = avatarDest(t, i)
	}
	return dest
}

// branchRelDest returns scan destinations for a Branch loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func branchRelDest(t *Branch) []any {
	dest := make([]any, 4)
	for i := range dest {
		dest[i] = branchDest(t, i)
	}
	return dest
}

// branchEventRelDest returns scan destinations for a BranchEvent loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func branchEventRelDest(t *BranchEvent) []any {
	dest := make([]any, 4)
	for i := range dest {
		dest[i] = branchEventDest(t, i)
	}
	return dest
}

// categoryRelDest returns scan destinations for a Category loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func categoryRelDest(t *Category) []any {
	dest := make([]any, 2)
	for i := range dest {
		dest[i] = categoryDest(t, i)
	}
	return dest
}

// commentRelDest returns scan destinations for a Comment loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func commentRelDest(t *Comment) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = commentDest(t, i)
	}
	return dest
}

// memberRelDest returns scan destinations for a Member loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func memberRelDest(t *Member) []any {
	dest := make([]any, 3)
	for i := range dest {
		dest[i] = memberDest(t, i)
	}
	return dest
}

// postRelDest returns scan destinations for a Post loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func postRelDest(t *Post) []any {
	dest := make([]any, 6)
	for i := range dest {
		dest[i] = postDest(t, i)
	}
	return dest
}

// profileRelDest returns scan destinations for a Profile loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func profileRelDest(t *Profile) []any {
	dest := make([]any, 3)
	for i := range dest {
		dest[i] = profileDest(t, i)
	}
	return dest
}

// reactionRelDest returns scan destinations for a Reaction loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func reactionRelDest(t *Reaction) []any {
	dest := make([]any, 2)
	for i := range dest {
		dest[i] = reactionDest(t, i)
	}
	return dest
}

// teamRelDest returns scan destinations for a Team loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func teamRelDest(t *Team) []any {
	dest := make([]any, 2)
	for i := range dest {
		dest[i] = teamDest(t, i)
	}
	return dest
}

// tenantRelDest returns scan destinations for a Tenant loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func tenantRelDest(t *Tenant) []any {
	dest := make([]any, 3)
	for i := range dest {
		dest[i] = tenantDest(t, i)
	}
	return dest
}

// userRelDest returns scan destinations for a User loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func userRelDest(t *User) []any {
	dest := make([]any, 17)
	for i := range dest {
		dest[i] = userDest(t, i)
	}
	return dest
}

// branchTenantColumns are the columns of public.tenants that Branch.Tenant reads.
var branchTenantColumns = []string{
	"code",
	"region",
	"name",
}

// branchTenantKeys pairs the columns Tenant matches on, in the order branches_tenant_fkey declares them.
var branchTenantKeys = []orm.RelKey{
	{Parent: "branch_region", Target: "region", Type: "text"},
	{Parent: "branch_code", Target: "code", Type: "text"},
}

// branchTenantBind allocates one row's worth of storage for Branch.Tenant and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func branchTenantBind() ([]any, func(*Branch)) {
	var n tenantNulls
	return tenantNullDest(&n), func(e *Branch) {
		if v, ok := tenantFromNulls(&n); ok {
			e.Tenant = orm.NewOne(&v)
			return
		}
		e.Tenant = orm.Absent[Tenant]()
	}
}

// branchTenantAttach sets Branch.Tenant from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func branchTenantAttach(e *Branch, t *Tenant) {
	if t == nil {
		e.Tenant = orm.Absent[Tenant]()
		return
	}
	e.Tenant = orm.NewOne(t)
}

// branchTenantRefs appends pointers to the rows Branch.Tenant loaded, which is what a
// relation of Tenant is loaded against.
func branchTenantRefs(e *Branch, out []*Tenant) []*Tenant {
	if v, ok := e.Tenant.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// branchTenantLoadKeys reads the keys of Branch.Tenant from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func branchTenantLoadKeys(parents []*Branch) ([]any, error) {
	k0 := make([]string, len(parents))
	k1 := make([]string, len(parents))
	for i, p := range parents {
		k0[i] = p.Region
		k1[i] = p.Code
	}
	return []any{
		k0,
		k1,
	}, nil
}

// commentAuthorColumns are the columns of public.users that Comment.Author reads.
var commentAuthorColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// commentAuthorKeys pairs the columns Author matches on, in the order comments_author_id_fkey declares them.
var commentAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// commentAuthorBind allocates one row's worth of storage for Comment.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func commentAuthorBind() ([]any, func(*Comment)) {
	var n userNulls
	return userNullDest(&n), func(e *Comment) {
		if v, ok := userFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[User]()
	}
}

// commentAuthorAttach sets Comment.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func commentAuthorAttach(e *Comment, t *User) {
	if t == nil {
		e.Author = orm.Absent[User]()
		return
	}
	e.Author = orm.NewOne(t)
}

// commentAuthorRefs appends pointers to the rows Comment.Author loaded, which is what a
// relation of User is loaded against.
func commentAuthorRefs(e *Comment, out []*User) []*User {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// commentAuthorAuxColumns are the columns Comment.Author matches on that Comment does not map.
//
// The statement that loads the Comment selects them as extra values, so that
// this relation has keys to load by without Comment having to carry a field it
// was never written with.
var commentAuthorAuxColumns = []string{
	"author_id",
}

// commentAuthorAux buffers those values for as long as Comment.Author needs them.
//
// A key may be NULL, which is a row with no related row rather than a fault,
// so every value is held as a pointer and travels to PostgreSQL as one.
type commentAuthorAux struct {
	k0 []*int64
}

func newCommentAuthorAux() orm.AuxKeys { return &commentAuthorAux{} }

// Next makes room for one more row and returns where to scan it.
func (a *commentAuthorAux) Next() []any {
	a.k0 = append(a.k0, nil)
	return []any{
		&a.k0[len(a.k0)-1],
	}
}

// Reorder puts the values in the order the rows were attached in.
func (a *commentAuthorAux) Reorder(order []int) {
	k0 := make([]*int64, len(order))
	for i, j := range order {
		k0[i] = a.k0[j]
	}
	a.k0 = k0
}

// Arrays returns one array per key column.
func (a *commentAuthorAux) Arrays() []any {
	return []any{
		a.k0,
	}
}

// commentReactionsColumns are the columns of public.reactions that Comment.Reactions reads.
var commentReactionsColumns = []string{
	"id",
	"kind",
}

// commentReactionsKeys pairs the columns Reactions matches on, in the order reactions_comment_id_fkey declares them.
var commentReactionsKeys = []orm.RelKey{
	{Parent: "id", Target: "comment_id", Type: "int8"},
}

// commentReactionsAttach sets Comment.Reactions from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func commentReactionsAttach(e *Comment, rows []Reaction) { e.Reactions = orm.NewManyFrom(rows) }

// commentReactionsRefs appends pointers to the rows Comment.Reactions loaded, which is what a
// relation of Reaction is loaded against.
func commentReactionsRefs(e *Comment, out []*Reaction) []*Reaction {
	rows, ok := e.Reactions.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// commentReactionsLoadKeys reads the keys of Comment.Reactions from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func commentReactionsLoadKeys(parents []*Comment) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// documentCreatorColumns are the columns of public.users that Document.Creator reads.
var documentCreatorColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// documentCreatorKeys pairs the columns Creator matches on, in the order documents_creator_id_fkey declares them.
var documentCreatorKeys = []orm.RelKey{
	{Parent: "creator_id", Target: "id", Type: "int8"},
}

// documentCreatorBind allocates one row's worth of storage for Document.Creator and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func documentCreatorBind() ([]any, func(*Document)) {
	var n userNulls
	return userNullDest(&n), func(e *Document) {
		if v, ok := userFromNulls(&n); ok {
			e.Creator = orm.NewOne(&v)
			return
		}
		e.Creator = orm.Absent[User]()
	}
}

// documentCreatorAttach sets Document.Creator from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func documentCreatorAttach(e *Document, t *User) {
	if t == nil {
		e.Creator = orm.Absent[User]()
		return
	}
	e.Creator = orm.NewOne(t)
}

// documentCreatorRefs appends pointers to the rows Document.Creator loaded, which is what a
// relation of User is loaded against.
func documentCreatorRefs(e *Document, out []*User) []*User {
	if v, ok := e.Creator.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// documentCreatorLoadKeys reads the keys of Document.Creator from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func documentCreatorLoadKeys(parents []*Document) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.CreatorID
	}
	return []any{
		k0,
	}, nil
}

// documentEditorColumns are the columns of public.users that Document.Editor reads.
var documentEditorColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// documentEditorKeys pairs the columns Editor matches on, in the order documents_editor_id_fkey declares them.
var documentEditorKeys = []orm.RelKey{
	{Parent: "editor_id", Target: "id", Type: "int8"},
}

// documentEditorBind allocates one row's worth of storage for Document.Editor and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func documentEditorBind() ([]any, func(*Document)) {
	var n userNulls
	return userNullDest(&n), func(e *Document) {
		if v, ok := userFromNulls(&n); ok {
			e.Editor = orm.NewOne(&v)
			return
		}
		e.Editor = orm.Absent[User]()
	}
}

// documentEditorAttach sets Document.Editor from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func documentEditorAttach(e *Document, t *User) {
	if t == nil {
		e.Editor = orm.Absent[User]()
		return
	}
	e.Editor = orm.NewOne(t)
}

// documentEditorRefs appends pointers to the rows Document.Editor loaded, which is what a
// relation of User is loaded against.
func documentEditorRefs(e *Document, out []*User) []*User {
	if v, ok := e.Editor.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// documentEditorAuxColumns are the columns Document.Editor matches on that Document does not map.
//
// The statement that loads the Document selects them as extra values, so that
// this relation has keys to load by without Document having to carry a field it
// was never written with.
var documentEditorAuxColumns = []string{
	"editor_id",
}

// documentEditorAux buffers those values for as long as Document.Editor needs them.
//
// A key may be NULL, which is a row with no related row rather than a fault,
// so every value is held as a pointer and travels to PostgreSQL as one.
type documentEditorAux struct {
	k0 []*int64
}

func newDocumentEditorAux() orm.AuxKeys { return &documentEditorAux{} }

// Next makes room for one more row and returns where to scan it.
func (a *documentEditorAux) Next() []any {
	a.k0 = append(a.k0, nil)
	return []any{
		&a.k0[len(a.k0)-1],
	}
}

// Reorder puts the values in the order the rows were attached in.
func (a *documentEditorAux) Reorder(order []int) {
	k0 := make([]*int64, len(order))
	for i, j := range order {
		k0[i] = a.k0[j]
	}
	a.k0 = k0
}

// Arrays returns one array per key column.
func (a *documentEditorAux) Arrays() []any {
	return []any{
		a.k0,
	}
}

// memberTeamColumns are the columns of public.teams that Member.Team reads.
var memberTeamColumns = []string{
	"slug",
	"name",
}

// memberTeamKeys pairs the columns Team matches on, in the order members_team_slug_fkey declares them.
var memberTeamKeys = []orm.RelKey{
	{Parent: "team_slug", Target: "slug", Type: "public.citext"},
}

// memberTeamBind allocates one row's worth of storage for Member.Team and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func memberTeamBind() ([]any, func(*Member)) {
	var n teamNulls
	return teamNullDest(&n), func(e *Member) {
		if v, ok := teamFromNulls(&n); ok {
			e.Team = orm.NewOne(&v)
			return
		}
		e.Team = orm.Absent[Team]()
	}
}

// memberTeamAttach sets Member.Team from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func memberTeamAttach(e *Member, t *Team) {
	if t == nil {
		e.Team = orm.Absent[Team]()
		return
	}
	e.Team = orm.NewOne(t)
}

// memberTeamRefs appends pointers to the rows Member.Team loaded, which is what a
// relation of Team is loaded against.
func memberTeamRefs(e *Member, out []*Team) []*Team {
	if v, ok := e.Team.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// memberTeamLoadKeys reads the keys of Member.Team from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func memberTeamLoadKeys(parents []*Member) ([]any, error) {
	k0 := make([]string, len(parents))
	for i, p := range parents {
		k0[i] = p.TeamSlug
	}
	return []any{
		k0,
	}, nil
}

// postAuthorColumns are the columns of public.users that Post.Author reads.
var postAuthorColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// postAuthorKeys pairs the columns Author matches on, in the order posts_author_id_fkey declares them.
var postAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// postAuthorBind allocates one row's worth of storage for Post.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func postAuthorBind() ([]any, func(*Post)) {
	var n userNulls
	return userNullDest(&n), func(e *Post) {
		if v, ok := userFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[User]()
	}
}

// postAuthorAttach sets Post.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postAuthorAttach(e *Post, t *User) {
	if t == nil {
		e.Author = orm.Absent[User]()
		return
	}
	e.Author = orm.NewOne(t)
}

// postAuthorRefs appends pointers to the rows Post.Author loaded, which is what a
// relation of User is loaded against.
func postAuthorRefs(e *Post, out []*User) []*User {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// postAuthorLoadKeys reads the keys of Post.Author from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func postAuthorLoadKeys(parents []*Post) ([]any, error) {
	k0 := make([]*int64, len(parents))
	for i, p := range parents {
		k0[i] = p.AuthorID
	}
	return []any{
		k0,
	}, nil
}

// postCategoryColumns are the columns of public.categories that Post.Category reads.
var postCategoryColumns = []string{
	"id",
	"name",
}

// postCategoryKeys pairs the columns Category matches on, in the order posts_category_id_fkey declares them.
var postCategoryKeys = []orm.RelKey{
	{Parent: "category_id", Target: "id", Type: "int8"},
}

// postCategoryBind allocates one row's worth of storage for Post.Category and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func postCategoryBind() ([]any, func(*Post)) {
	var n categoryNulls
	return categoryNullDest(&n), func(e *Post) {
		if v, ok := categoryFromNulls(&n); ok {
			e.Category = orm.NewOne(&v)
			return
		}
		e.Category = orm.Absent[Category]()
	}
}

// postCategoryAttach sets Post.Category from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postCategoryAttach(e *Post, t *Category) {
	if t == nil {
		e.Category = orm.Absent[Category]()
		return
	}
	e.Category = orm.NewOne(t)
}

// postCategoryRefs appends pointers to the rows Post.Category loaded, which is what a
// relation of Category is loaded against.
func postCategoryRefs(e *Post, out []*Category) []*Category {
	if v, ok := e.Category.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// postCategoryAuxColumns are the columns Post.Category matches on that Post does not map.
//
// The statement that loads the Post selects them as extra values, so that
// this relation has keys to load by without Post having to carry a field it
// was never written with.
var postCategoryAuxColumns = []string{
	"category_id",
}

// postCategoryAux buffers those values for as long as Post.Category needs them.
//
// A key may be NULL, which is a row with no related row rather than a fault,
// so every value is held as a pointer and travels to PostgreSQL as one.
type postCategoryAux struct {
	k0 []*int64
}

func newPostCategoryAux() orm.AuxKeys { return &postCategoryAux{} }

// Next makes room for one more row and returns where to scan it.
func (a *postCategoryAux) Next() []any {
	a.k0 = append(a.k0, nil)
	return []any{
		&a.k0[len(a.k0)-1],
	}
}

// Reorder puts the values in the order the rows were attached in.
func (a *postCategoryAux) Reorder(order []int) {
	k0 := make([]*int64, len(order))
	for i, j := range order {
		k0[i] = a.k0[j]
	}
	a.k0 = k0
}

// Arrays returns one array per key column.
func (a *postCategoryAux) Arrays() []any {
	return []any{
		a.k0,
	}
}

// postCommentsColumns are the columns of public.comments that Post.Comments reads.
var postCommentsColumns = []string{
	"id",
	"body",
	"visible",
	"score",
	"created_at",
}

// postCommentsKeys pairs the columns Comments matches on, in the order comments_post_id_fkey declares them.
var postCommentsKeys = []orm.RelKey{
	{Parent: "id", Target: "post_id", Type: "int8"},
}

// postCommentsAttach sets Post.Comments from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postCommentsAttach(e *Post, rows []Comment) { e.Comments = orm.NewManyFrom(rows) }

// postCommentsRefs appends pointers to the rows Post.Comments loaded, which is what a
// relation of Comment is loaded against.
func postCommentsRefs(e *Post, out []*Comment) []*Comment {
	rows, ok := e.Comments.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// postCommentsLoadKeys reads the keys of Post.Comments from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func postCommentsLoadKeys(parents []*Post) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// profileAvatarColumns are the columns of public.avatars that Profile.Avatar reads.
var profileAvatarColumns = []string{
	"id",
	"url",
}

// profileAvatarKeys pairs the columns Avatar matches on, in the order profiles_avatar_id_fkey declares them.
var profileAvatarKeys = []orm.RelKey{
	{Parent: "avatar_id", Target: "id", Type: "int8"},
}

// profileAvatarBind allocates one row's worth of storage for Profile.Avatar and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func profileAvatarBind() ([]any, func(*Profile)) {
	var n avatarNulls
	return avatarNullDest(&n), func(e *Profile) {
		if v, ok := avatarFromNulls(&n); ok {
			e.Avatar = orm.NewOne(&v)
			return
		}
		e.Avatar = orm.Absent[Avatar]()
	}
}

// profileAvatarAttach sets Profile.Avatar from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func profileAvatarAttach(e *Profile, t *Avatar) {
	if t == nil {
		e.Avatar = orm.Absent[Avatar]()
		return
	}
	e.Avatar = orm.NewOne(t)
}

// profileAvatarRefs appends pointers to the rows Profile.Avatar loaded, which is what a
// relation of Avatar is loaded against.
func profileAvatarRefs(e *Profile, out []*Avatar) []*Avatar {
	if v, ok := e.Avatar.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// profileAvatarAuxColumns are the columns Profile.Avatar matches on that Profile does not map.
//
// The statement that loads the Profile selects them as extra values, so that
// this relation has keys to load by without Profile having to carry a field it
// was never written with.
var profileAvatarAuxColumns = []string{
	"avatar_id",
}

// profileAvatarAux buffers those values for as long as Profile.Avatar needs them.
//
// A key may be NULL, which is a row with no related row rather than a fault,
// so every value is held as a pointer and travels to PostgreSQL as one.
type profileAvatarAux struct {
	k0 []*int64
}

func newProfileAvatarAux() orm.AuxKeys { return &profileAvatarAux{} }

// Next makes room for one more row and returns where to scan it.
func (a *profileAvatarAux) Next() []any {
	a.k0 = append(a.k0, nil)
	return []any{
		&a.k0[len(a.k0)-1],
	}
}

// Reorder puts the values in the order the rows were attached in.
func (a *profileAvatarAux) Reorder(order []int) {
	k0 := make([]*int64, len(order))
	for i, j := range order {
		k0[i] = a.k0[j]
	}
	a.k0 = k0
}

// Arrays returns one array per key column.
func (a *profileAvatarAux) Arrays() []any {
	return []any{
		a.k0,
	}
}

// reactionAuthorColumns are the columns of public.users that Reaction.Author reads.
var reactionAuthorColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// reactionAuthorKeys pairs the columns Author matches on, in the order reactions_author_id_fkey declares them.
var reactionAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// reactionAuthorBind allocates one row's worth of storage for Reaction.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func reactionAuthorBind() ([]any, func(*Reaction)) {
	var n userNulls
	return userNullDest(&n), func(e *Reaction) {
		if v, ok := userFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[User]()
	}
}

// reactionAuthorAttach sets Reaction.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func reactionAuthorAttach(e *Reaction, t *User) {
	if t == nil {
		e.Author = orm.Absent[User]()
		return
	}
	e.Author = orm.NewOne(t)
}

// reactionAuthorRefs appends pointers to the rows Reaction.Author loaded, which is what a
// relation of User is loaded against.
func reactionAuthorRefs(e *Reaction, out []*User) []*User {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// reactionAuthorAuxColumns are the columns Reaction.Author matches on that Reaction does not map.
//
// The statement that loads the Reaction selects them as extra values, so that
// this relation has keys to load by without Reaction having to carry a field it
// was never written with.
var reactionAuthorAuxColumns = []string{
	"author_id",
}

// reactionAuthorAux buffers those values for as long as Reaction.Author needs them.
//
// A key may be NULL, which is a row with no related row rather than a fault,
// so every value is held as a pointer and travels to PostgreSQL as one.
type reactionAuthorAux struct {
	k0 []*int64
}

func newReactionAuthorAux() orm.AuxKeys { return &reactionAuthorAux{} }

// Next makes room for one more row and returns where to scan it.
func (a *reactionAuthorAux) Next() []any {
	a.k0 = append(a.k0, nil)
	return []any{
		&a.k0[len(a.k0)-1],
	}
}

// Reorder puts the values in the order the rows were attached in.
func (a *reactionAuthorAux) Reorder(order []int) {
	k0 := make([]*int64, len(order))
	for i, j := range order {
		k0[i] = a.k0[j]
	}
	a.k0 = k0
}

// Arrays returns one array per key column.
func (a *reactionAuthorAux) Arrays() []any {
	return []any{
		a.k0,
	}
}

// teamMembersColumns are the columns of public.members that Team.Members reads.
var teamMembersColumns = []string{
	"id",
	"team_slug",
	"nickname",
}

// teamMembersKeys pairs the columns Members matches on, in the order members_team_slug_fkey declares them.
var teamMembersKeys = []orm.RelKey{
	{Parent: "slug", Target: "team_slug", Type: "public.citext"},
}

// teamMembersAttach sets Team.Members from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func teamMembersAttach(e *Team, rows []Member) { e.Members = orm.NewManyFrom(rows) }

// teamMembersRefs appends pointers to the rows Team.Members loaded, which is what a
// relation of Member is loaded against.
func teamMembersRefs(e *Team, out []*Member) []*Member {
	rows, ok := e.Members.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// teamMembersLoadKeys reads the keys of Team.Members from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func teamMembersLoadKeys(parents []*Team) ([]any, error) {
	k0 := make([]string, len(parents))
	for i, p := range parents {
		k0[i] = p.Slug
	}
	return []any{
		k0,
	}, nil
}

// tenantBranchesColumns are the columns of public.branches that Tenant.Branches reads.
var tenantBranchesColumns = []string{
	"id",
	"label",
	"branch_code",
	"branch_region",
}

// tenantBranchesKeys pairs the columns Branches matches on, in the order branches_tenant_fkey declares them.
var tenantBranchesKeys = []orm.RelKey{
	{Parent: "region", Target: "branch_region", Type: "text"},
	{Parent: "code", Target: "branch_code", Type: "text"},
}

// tenantBranchesAttach sets Tenant.Branches from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func tenantBranchesAttach(e *Tenant, rows []Branch) { e.Branches = orm.NewManyFrom(rows) }

// tenantBranchesRefs appends pointers to the rows Tenant.Branches loaded, which is what a
// relation of Branch is loaded against.
func tenantBranchesRefs(e *Tenant, out []*Branch) []*Branch {
	rows, ok := e.Branches.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// tenantBranchesLoadKeys reads the keys of Tenant.Branches from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func tenantBranchesLoadKeys(parents []*Tenant) ([]any, error) {
	k0 := make([]string, len(parents))
	k1 := make([]string, len(parents))
	for i, p := range parents {
		k0[i] = p.Region
		k1[i] = p.Code
	}
	return []any{
		k0,
		k1,
	}, nil
}

// tenantEventsColumns are the columns of public.branch_events that Tenant.Events reads.
var tenantEventsColumns = []string{
	"id",
	"label",
	"event_code",
	"event_region",
}

// tenantEventsKeys pairs the columns Events matches on, in the order branch_events_tenant_fkey declares them.
var tenantEventsKeys = []orm.RelKey{
	{Parent: "region", Target: "event_region", Type: "text"},
	{Parent: "code", Target: "event_code", Type: "text"},
}

// tenantEventsAttach sets Tenant.Events from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func tenantEventsAttach(e *Tenant, rows []BranchEvent) { e.Events = orm.NewManyFrom(rows) }

// tenantEventsRefs appends pointers to the rows Tenant.Events loaded, which is what a
// relation of BranchEvent is loaded against.
func tenantEventsRefs(e *Tenant, out []*BranchEvent) []*BranchEvent {
	rows, ok := e.Events.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// tenantEventsLoadKeys reads the keys of Tenant.Events from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func tenantEventsLoadKeys(parents []*Tenant) ([]any, error) {
	k0 := make([]string, len(parents))
	k1 := make([]string, len(parents))
	for i, p := range parents {
		k0[i] = p.Region
		k1[i] = p.Code
	}
	return []any{
		k0,
		k1,
	}, nil
}

// userPostsColumns are the columns of public.posts that User.Posts reads.
var userPostsColumns = []string{
	"id",
	"author_id",
	"title",
	"published",
	"score",
	"created_at",
}

// userPostsKeys pairs the columns Posts matches on, in the order posts_author_id_fkey declares them.
var userPostsKeys = []orm.RelKey{
	{Parent: "id", Target: "author_id", Type: "int8"},
}

// userPostsAttach sets User.Posts from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userPostsAttach(e *User, rows []Post) { e.Posts = orm.NewManyFrom(rows) }

// userPostsRefs appends pointers to the rows User.Posts loaded, which is what a
// relation of Post is loaded against.
func userPostsRefs(e *User, out []*Post) []*Post {
	rows, ok := e.Posts.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userPostsLoadKeys reads the keys of User.Posts from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userPostsLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// userProfileColumns are the columns of public.profiles that User.Profile reads.
var userProfileColumns = []string{
	"id",
	"user_id",
	"bio",
}

// userProfileKeys pairs the columns Profile matches on, in the order profiles_user_id_fkey declares them.
var userProfileKeys = []orm.RelKey{
	{Parent: "id", Target: "user_id", Type: "int8"},
}

// userProfileBind allocates one row's worth of storage for User.Profile and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func userProfileBind() ([]any, func(*User)) {
	var n profileNulls
	return profileNullDest(&n), func(e *User) {
		if v, ok := profileFromNulls(&n); ok {
			e.Profile = orm.NewOne(&v)
			return
		}
		e.Profile = orm.Absent[Profile]()
	}
}

// userProfileAttach sets User.Profile from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userProfileAttach(e *User, t *Profile) {
	if t == nil {
		e.Profile = orm.Absent[Profile]()
		return
	}
	e.Profile = orm.NewOne(t)
}

// userProfileRefs appends pointers to the rows User.Profile loaded, which is what a
// relation of Profile is loaded against.
func userProfileRefs(e *User, out []*Profile) []*Profile {
	if v, ok := e.Profile.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// userProfileLoadKeys reads the keys of User.Profile from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userProfileLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// userManagerColumns are the columns of public.users that User.Manager reads.
var userManagerColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// userManagerKeys pairs the columns Manager matches on, in the order users_manager_id_fkey declares them.
var userManagerKeys = []orm.RelKey{
	{Parent: "manager_id", Target: "id", Type: "int8"},
}

// userManagerBind allocates one row's worth of storage for User.Manager and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func userManagerBind() ([]any, func(*User)) {
	var n userNulls
	return userNullDest(&n), func(e *User) {
		if v, ok := userFromNulls(&n); ok {
			e.Manager = orm.NewOne(&v)
			return
		}
		e.Manager = orm.Absent[User]()
	}
}

// userManagerAttach sets User.Manager from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userManagerAttach(e *User, t *User) {
	if t == nil {
		e.Manager = orm.Absent[User]()
		return
	}
	e.Manager = orm.NewOne(t)
}

// userManagerRefs appends pointers to the rows User.Manager loaded, which is what a
// relation of User is loaded against.
func userManagerRefs(e *User, out []*User) []*User {
	if v, ok := e.Manager.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// userManagerLoadKeys reads the keys of User.Manager from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userManagerLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]*int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ManagerID
	}
	return []any{
		k0,
	}, nil
}

// userReportsColumns are the columns of public.users that User.Reports reads.
var userReportsColumns = []string{
	"id",
	"email",
	"age",
	"active",
	"state",
	"nickname",
	"score",
	"tags",
	"settings",
	"avatar",
	"manager_id",
	"bio",
	"visits",
	"deleted_at",
	"created_at",
	"slug",
	"metadata",
}

// userReportsKeys pairs the columns Reports matches on, in the order users_manager_id_fkey declares them.
var userReportsKeys = []orm.RelKey{
	{Parent: "id", Target: "manager_id", Type: "int8"},
}

// userReportsAttach sets User.Reports from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userReportsAttach(e *User, rows []User) { e.Reports = orm.NewManyFrom(rows) }

// userReportsRefs appends pointers to the rows User.Reports loaded, which is what a
// relation of User is loaded against.
func userReportsRefs(e *User, out []*User) []*User {
	rows, ok := e.Reports.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userReportsLoadKeys reads the keys of User.Reports from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userReportsLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
