CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE user_state AS ENUM ('pending', 'active', 'banned');

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text NOT NULL UNIQUE,
    age        integer NOT NULL,
    active     boolean NOT NULL DEFAULT true,
    state      user_state NOT NULL DEFAULT 'pending',
    nickname   text,
    score      double precision,
    tags       text[] NOT NULL DEFAULT '{}',
    settings   jsonb NOT NULL DEFAULT '{}',
    avatar     bytea,
    manager_id bigint REFERENCES users(id),
    bio        text,
    visits     bigint,
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    slug       text GENERATED ALWAYS AS (lower(email)) STORED,
    metadata   jsonb
);

CREATE TABLE posts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id  bigint REFERENCES users(id),
    title      text NOT NULL,
    published  boolean NOT NULL DEFAULT false,
    score      integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE profiles (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id),
    bio     text
);

-- Two foreign keys to one table, so each relation needs its own occurrence of
-- users in the statement.
CREATE TABLE documents (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      text NOT NULL,
    creator_id bigint NOT NULL REFERENCES users(id),
    editor_id  bigint REFERENCES users(id)
);

-- A composite relation key whose constraint order is deliberately not
-- alphabetical: tenants(region, code) is referenced as (region, code) while the
-- child declares them in the other order in the table.
CREATE TABLE tenants (
    code   text NOT NULL,
    region text NOT NULL,
    name   text NOT NULL,
    PRIMARY KEY (region, code)
);

CREATE TABLE branches (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_code   text NOT NULL,
    branch_region text NOT NULL,
    label         text NOT NULL,
    CONSTRAINT branches_tenant_fkey FOREIGN KEY (branch_region, branch_code)
        REFERENCES tenants(region, code)
);

-- A relation keyed on citext, whose equality is case-insensitive and so is not
-- Go's. Matching these rows in Go would silently drop them.
CREATE TABLE teams (
    slug citext PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE members (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_slug citext NOT NULL REFERENCES teams(slug),
    nickname  text NOT NULL
);

-- The nested-relation graph. Avatars hang off profiles, comments off posts, and
-- reactions off comments, so a requested tree can be four levels deep.
CREATE TABLE avatars (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url     text NOT NULL
);

ALTER TABLE profiles ADD COLUMN avatar_id bigint REFERENCES avatars(id);

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

ALTER TABLE posts ADD COLUMN category_id bigint REFERENCES categories(id);

-- comments.post_id and comments.author_id are both deliberately left out of the
-- Go struct, so two consecutive nested levels have to read their keys from the
-- statement that loaded their parents rather than from an entity.
CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint REFERENCES posts(id),
    author_id  bigint REFERENCES users(id),
    body       text NOT NULL,
    visible    boolean NOT NULL DEFAULT true,
    score      integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reactions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint REFERENCES comments(id),
    author_id  bigint REFERENCES users(id),
    kind       text NOT NULL
);

-- A composite relation two levels down: a tenant's branches, and each branch's
-- events, keyed on the branch's own composite identity.
CREATE TABLE branch_events (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_region  text NOT NULL,
    event_code    text NOT NULL,
    label         text NOT NULL,
    CONSTRAINT branch_events_tenant_fkey FOREIGN KEY (event_region, event_code)
        REFERENCES tenants(region, code)
);

-- M12: PostgreSQL-native network types, mapped end to end.
CREATE TABLE networks (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label    text NOT NULL,
    subnet   cidr NOT NULL,
    host     inet NOT NULL,
    fallback inet,
    hardware macaddr NOT NULL
);

-- M12.4: full text search, with the vector maintained as a generated column
-- and a GIN index over it.
CREATE TABLE articles (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   text NOT NULL,
    body    text NOT NULL,
    search  tsvector GENERATED ALWAYS AS (
                to_tsvector('english', title || ' ' || body)
            ) STORED
);

CREATE INDEX articles_search_idx ON articles USING GIN (search);

-- M12.2: ranges, multiranges and intervals, one column per family so that the
-- three that share time.Time on the Go side are proved to stay distinct here.
CREATE TABLE bookings (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room      text NOT NULL,
    starts_at timestamptz NOT NULL,
    period   tstzrange NOT NULL,
    stay     daterange NOT NULL,
    shift    tsrange NOT NULL,
    quota    int4range NOT NULL,
    span     int8range NOT NULL,
    revised  tstzrange,
    lease    interval NOT NULL,
    grace    interval,
    holds    tstzmultirange NOT NULL,
    slots    int4multirange
);

CREATE INDEX bookings_period_gist ON bookings USING gist (period);
