-- A NOT NULL domain rejects an omitted value exactly as a NOT NULL column does.
CREATE DOMAIN required_text AS text NOT NULL;

CREATE TABLE invoices (
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    number        bigint GENERATED BY DEFAULT AS IDENTITY,
    net           integer NOT NULL,
    gross         integer GENERATED ALWAYS AS (net * 2) STORED NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    required_note text NOT NULL,
    domain_note   required_text,
    optional_note text,
    seq           bigserial NOT NULL
);
