-- The blog example's schema. The ORM does not own it: this file is applied by
-- psql, and a real project would use whatever migration tool it already has.

CREATE TYPE post_status AS ENUM ('draft', 'published', 'archived');

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text NOT NULL UNIQUE,
    name       text NOT NULL,
    active     boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- One profile per user, which is what makes the relation a has-one rather than
-- a has-many: the unique constraint is the proof.
CREATE TABLE profiles (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id),
    bio     text
);

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE posts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   bigint NOT NULL REFERENCES users(id),
    -- Nullable: a post need not be filed under anything.
    category_id bigint REFERENCES categories(id),
    title       text NOT NULL,
    body        text NOT NULL,
    status      post_status NOT NULL DEFAULT 'draft',
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE comments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint NOT NULL REFERENCES posts(id),
    author_id  bigint NOT NULL REFERENCES users(id),
    body       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
