// Code generated by orm. DO NOT EDIT.

package domain

import (
	"time"

	"github.com/AlexAli29/orm"
)

// articlesSource is the occurrence of public.articles that Articles reads from.
var articlesSource = orm.NewSource("public", "articles")

// articleTable holds one typed descriptor per mapped column of public.articles, and one
// per relation reconciliation proved.
type articleTable struct {
	src         *orm.Source
	ID          orm.OrdCol[Article, int64]
	AuthorID    orm.OrdCol[Article, int64]
	Title       orm.TextCol[Article]
	Body        orm.TextCol[Article]
	Status      orm.OrdCol[Article, Status]
	PublishedAt orm.NullOrdCol[Article, time.Time]
	CreatedAt   orm.OrdCol[Article, time.Time]
	Author      orm.Rel[Article, Author]
}

// newArticleTable builds the descriptors for one occurrence of public.articles.
func newArticleTable(src *orm.Source) articleTable {
	return articleTable{
		src:         src,
		ID:          orm.NewOrdCol[Article, int64](src, "id"),
		AuthorID:    orm.NewOrdCol[Article, int64](src, "author_id"),
		Title:       orm.NewTextCol[Article](src, "title"),
		Body:        orm.NewTextCol[Article](src, "body"),
		Status:      orm.NewOrdCol[Article, Status](src, "status"),
		PublishedAt: orm.NewNullOrdCol[Article, time.Time](src, "published_at"),
		CreatedAt:   orm.NewOrdCol[Article, time.Time](src, "created_at"),
		Author: orm.NewOneRel(orm.OneRelSpec[Article, Author]{
			Name:        "Author",
			Parent:      src,
			Target:      authorsSource,
			Keys:        articleAuthorKeys,
			Columns:     articleAuthorColumns,
			Bind:        articleAuthorBind,
			ExtractKeys: articleAuthorLoadKeys,
			Dest:        authorRelDest,
			Attach:      articleAuthorAttach,
			Refs:        articleAuthorRefs,
		}),
	}
}

// Articles addresses the columns of public.articles.
var Articles = newArticleTable(articlesSource)

// As returns descriptors for a second occurrence of public.articles under
// alias, leaving Articles untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t articleTable) As(alias string) articleTable { return newArticleTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t articleTable) Source() *orm.Source { return t.src }

// authorsSource is the occurrence of public.authors that Authors reads from.
var authorsSource = orm.NewSource("public", "authors")

// authorTable holds one typed descriptor per mapped column of public.authors, and one
// per relation reconciliation proved.
type authorTable struct {
	src      *orm.Source
	ID       orm.OrdCol[Author, int64]
	Email    orm.TextCol[Author]
	Name     orm.TextCol[Author]
	Bio      orm.NullTextCol[Author]
	JoinedAt orm.OrdCol[Author, time.Time]
	Articles orm.Rel[Author, Article]
}

// newAuthorTable builds the descriptors for one occurrence of public.authors.
func newAuthorTable(src *orm.Source) authorTable {
	return authorTable{
		src:      src,
		ID:       orm.NewOrdCol[Author, int64](src, "id"),
		Email:    orm.NewTextCol[Author](src, "email"),
		Name:     orm.NewTextCol[Author](src, "name"),
		Bio:      orm.NewNullTextCol[Author](src, "bio"),
		JoinedAt: orm.NewOrdCol[Author, time.Time](src, "joined_at"),
		Articles: orm.NewManyRel(orm.ManyRelSpec[Author, Article]{
			Name:        "Articles",
			Parent:      src,
			Target:      articlesSource,
			Keys:        authorArticlesKeys,
			Columns:     authorArticlesColumns,
			ExtractKeys: authorArticlesLoadKeys,
			Dest:        articleRelDest,
			Attach:      authorArticlesAttach,
			Refs:        authorArticlesRefs,
		}),
	}
}

// Authors addresses the columns of public.authors.
var Authors = newAuthorTable(authorsSource)

// As returns descriptors for a second occurrence of public.authors under
// alias, leaving Authors untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t authorTable) As(alias string) authorTable { return newAuthorTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t authorTable) Source() *orm.Source { return t.src }
