// Code generated by orm. DO NOT EDIT.

package domain

import (
	"time"

	"github.com/AlexAli29/orm"
)

// authorNulls mirrors Author with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Author would fail on those rather than report an absent
// relation, so the row lands here first.
type authorNulls struct {
	ID       *int64
	Email    *string
	Name     *string
	Bio      *string
	JoinedAt *time.Time
}

// authorNullDest returns scan destinations for every column of public.authors.
func authorNullDest(n *authorNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.Name,
		&n.Bio,
		&n.JoinedAt,
	}
}

// authorFromNulls rebuilds Author from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func authorFromNulls(n *authorNulls) (Author, bool) {
	if n.ID == nil {
		return Author{}, false
	}
	return Author{
		ID:       *n.ID,
		Email:    *n.Email,
		Name:     *n.Name,
		Bio:      n.Bio,
		JoinedAt: *n.JoinedAt,
	}, true
}

// articleRelDest returns scan destinations for a Article loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func articleRelDest(t *Article) []any {
	dest := make([]any, 7)
	for i := range dest {
		dest[i] = articleDest(t, i)
	}
	return dest
}

// authorRelDest returns scan destinations for a Author loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func authorRelDest(t *Author) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = authorDest(t, i)
	}
	return dest
}

// articleAuthorColumns are the columns of public.authors that Article.Author reads.
var articleAuthorColumns = []string{
	"id",
	"email",
	"name",
	"bio",
	"joined_at",
}

// articleAuthorKeys pairs the columns Author matches on, in the order articles_author_id_fkey declares them.
var articleAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// articleAuthorBind allocates one row's worth of storage for Article.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func articleAuthorBind() ([]any, func(*Article)) {
	var n authorNulls
	return authorNullDest(&n), func(e *Article) {
		if v, ok := authorFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[Author]()
	}
}

// articleAuthorAttach sets Article.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func articleAuthorAttach(e *Article, t *Author) {
	if t == nil {
		e.Author = orm.Absent[Author]()
		return
	}
	e.Author = orm.NewOne(t)
}

// articleAuthorRefs appends pointers to the rows Article.Author loaded, which is what a
// relation of Author is loaded against.
func articleAuthorRefs(e *Article, out []*Author) []*Author {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// articleAuthorLoadKeys reads the keys of Article.Author from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func articleAuthorLoadKeys(parents []*Article) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.AuthorID
	}
	return []any{
		k0,
	}, nil
}

// authorArticlesColumns are the columns of public.articles that Author.Articles reads.
var authorArticlesColumns = []string{
	"id",
	"author_id",
	"title",
	"body",
	"status",
	"published_at",
	"created_at",
}

// authorArticlesKeys pairs the columns Articles matches on, in the order articles_author_id_fkey declares them.
var authorArticlesKeys = []orm.RelKey{
	{Parent: "id", Target: "author_id", Type: "int8"},
}

// authorArticlesAttach sets Author.Articles from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func authorArticlesAttach(e *Author, rows []Article) { e.Articles = orm.NewManyFrom(rows) }

// authorArticlesRefs appends pointers to the rows Author.Articles loaded, which is what a
// relation of Article is loaded against.
func authorArticlesRefs(e *Author, out []*Article) []*Article {
	rows, ok := e.Articles.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// authorArticlesLoadKeys reads the keys of Author.Articles from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func authorArticlesLoadKeys(parents []*Author) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
