// Code generated by orm. DO NOT EDIT.

package domain

import (
	"github.com/AlexAli29/orm"
)

// articleMeta describes how Article is read from public.articles.
var articleMeta = orm.EntityMeta[Article]{
	Table:  orm.TableID{Schema: "public", Name: "articles"},
	Source: articlesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "author_id", Field: "AuthorID", NotNull: true},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "body", Field: "Body", NotNull: true},
		{Name: "status", Field: "Status", NotNull: true, HasDefault: true},
		{Name: "published_at", Field: "PublishedAt"},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  articleDest,
	Value: articleValue,
}

// articleDest returns a pointer to the field holding column idx of public.articles.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func articleDest(e *Article, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.AuthorID
	case 2:
		return &e.Title
	case 3:
		return &e.Body
	case 4:
		return &e.Status
	case 5:
		return &e.PublishedAt
	case 6:
		return &e.CreatedAt
	default:
		return nil
	}
}

// articleValue returns the value of the field holding column idx of public.articles.
//
// It is the counterpart of articleDest and is written the same way, so an
// insert reads the entity without reflection either.
func articleValue(e *Article, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.AuthorID
	case 2:
		return e.Title
	case 3:
		return e.Body
	case 4:
		return e.Status
	case 5:
		return e.PublishedAt
	case 6:
		return e.CreatedAt
	default:
		return nil
	}
}

// authorMeta describes how Author is read from public.authors.
var authorMeta = orm.EntityMeta[Author]{
	Table:  orm.TableID{Schema: "public", Name: "authors"},
	Source: authorsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "bio", Field: "Bio"},
		{Name: "joined_at", Field: "JoinedAt", NotNull: true, HasDefault: true},
	},
	Dest:  authorDest,
	Value: authorValue,
}

// authorDest returns a pointer to the field holding column idx of public.authors.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func authorDest(e *Author, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.Name
	case 3:
		return &e.Bio
	case 4:
		return &e.JoinedAt
	default:
		return nil
	}
}

// authorValue returns the value of the field holding column idx of public.authors.
//
// It is the counterpart of authorDest and is written the same way, so an
// insert reads the entity without reflection either.
func authorValue(e *Author, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.Name
	case 3:
		return e.Bio
	case 4:
		return e.JoinedAt
	default:
		return nil
	}
}
