// Code generated by orm. DO NOT EDIT.

package ormstore

import (
	"time"

	"github.com/AlexAli29/orm"
)

// projectsSource is the occurrence of public.projects that Projects reads from.
var projectsSource = orm.NewSource("public", "projects")

// projectRowTable holds one typed descriptor per mapped column of public.projects, and one
// per relation reconciliation proved.
type projectRowTable struct {
	src       *orm.Source
	ID        orm.OrdCol[projectRow, int64]
	OwnerID   orm.OrdCol[projectRow, int64]
	Slug      orm.TextCol[projectRow]
	Name      orm.TextCol[projectRow]
	CreatedAt orm.OrdCol[projectRow, time.Time]
	Owner     orm.Rel[projectRow, userRow]
}

// newprojectRowTable builds the descriptors for one occurrence of public.projects.
func newprojectRowTable(src *orm.Source) projectRowTable {
	return projectRowTable{
		src:       src,
		ID:        orm.NewOrdCol[projectRow, int64](src, "id"),
		OwnerID:   orm.NewOrdCol[projectRow, int64](src, "owner_id"),
		Slug:      orm.NewTextCol[projectRow](src, "slug"),
		Name:      orm.NewTextCol[projectRow](src, "name"),
		CreatedAt: orm.NewOrdCol[projectRow, time.Time](src, "created_at"),
		Owner: orm.NewOneRel(orm.OneRelSpec[projectRow, userRow]{
			Name:        "Owner",
			Parent:      src,
			Target:      usersSource,
			Keys:        projectRowOwnerKeys,
			Columns:     projectRowOwnerColumns,
			Bind:        projectRowOwnerBind,
			ExtractKeys: projectRowOwnerLoadKeys,
			Dest:        userRowRelDest,
			Attach:      projectRowOwnerAttach,
			Refs:        projectRowOwnerRefs,
		}),
	}
}

// Projects addresses the columns of public.projects.
var Projects = newprojectRowTable(projectsSource)

// As returns descriptors for a second occurrence of public.projects under
// alias, leaving Projects untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t projectRowTable) As(alias string) projectRowTable { return newprojectRowTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t projectRowTable) Source() *orm.Source { return t.src }

// usersSource is the occurrence of public.users that Users reads from.
var usersSource = orm.NewSource("public", "users")

// userRowTable holds one typed descriptor per mapped column of public.users, and one
// per relation reconciliation proved.
type userRowTable struct {
	src       *orm.Source
	ID        orm.OrdCol[userRow, int64]
	Email     orm.TextCol[userRow]
	Name      orm.TextCol[userRow]
	CreatedAt orm.OrdCol[userRow, time.Time]
	Projects  orm.Rel[userRow, projectRow]
}

// newuserRowTable builds the descriptors for one occurrence of public.users.
func newuserRowTable(src *orm.Source) userRowTable {
	return userRowTable{
		src:       src,
		ID:        orm.NewOrdCol[userRow, int64](src, "id"),
		Email:     orm.NewTextCol[userRow](src, "email"),
		Name:      orm.NewTextCol[userRow](src, "name"),
		CreatedAt: orm.NewOrdCol[userRow, time.Time](src, "created_at"),
		Projects: orm.NewManyRel(orm.ManyRelSpec[userRow, projectRow]{
			Name:        "Projects",
			Parent:      src,
			Target:      projectsSource,
			Keys:        userRowProjectsKeys,
			Columns:     userRowProjectsColumns,
			ExtractKeys: userRowProjectsLoadKeys,
			Dest:        projectRowRelDest,
			Attach:      userRowProjectsAttach,
			Refs:        userRowProjectsRefs,
		}),
	}
}

// Users addresses the columns of public.users.
var Users = newuserRowTable(usersSource)

// As returns descriptors for a second occurrence of public.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userRowTable) As(alias string) userRowTable { return newuserRowTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userRowTable) Source() *orm.Source { return t.src }
