// Code generated by orm. DO NOT EDIT.

package ormstore

import (
	"github.com/AlexAli29/orm"
)

// projectRowMeta describes how projectRow is read from public.projects.
var projectRowMeta = orm.EntityMeta[projectRow]{
	Table:  orm.TableID{Schema: "public", Name: "projects"},
	Source: projectsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "owner_id", Field: "OwnerID", NotNull: true},
		{Name: "slug", Field: "Slug", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  projectRowDest,
	Value: projectRowValue,
}

// projectRowDest returns a pointer to the field holding column idx of public.projects.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func projectRowDest(e *projectRow, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.OwnerID
	case 2:
		return &e.Slug
	case 3:
		return &e.Name
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// projectRowValue returns the value of the field holding column idx of public.projects.
//
// It is the counterpart of projectRowDest and is written the same way, so an
// insert reads the entity without reflection either.
func projectRowValue(e *projectRow, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.OwnerID
	case 2:
		return e.Slug
	case 3:
		return e.Name
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}

// userRowMeta describes how userRow is read from public.users.
var userRowMeta = orm.EntityMeta[userRow]{
	Table:  orm.TableID{Schema: "public", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  userRowDest,
	Value: userRowValue,
}

// userRowDest returns a pointer to the field holding column idx of public.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userRowDest(e *userRow, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.Name
	case 3:
		return &e.CreatedAt
	default:
		return nil
	}
}

// userRowValue returns the value of the field holding column idx of public.users.
//
// It is the counterpart of userRowDest and is written the same way, so an
// insert reads the entity without reflection either.
func userRowValue(e *userRow, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.Name
	case 3:
		return e.CreatedAt
	default:
		return nil
	}
}
