// Code generated by orm. DO NOT EDIT.

package ormstore

import (
	"time"

	"github.com/AlexAli29/orm"
)

// userRowNulls mirrors userRow with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into userRow would fail on those rather than report an absent
// relation, so the row lands here first.
type userRowNulls struct {
	ID        *int64
	Email     *string
	Name      *string
	CreatedAt *time.Time
}

// userRowNullDest returns scan destinations for every column of public.users.
func userRowNullDest(n *userRowNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.Name,
		&n.CreatedAt,
	}
}

// userRowFromNulls rebuilds userRow from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func userRowFromNulls(n *userRowNulls) (userRow, bool) {
	if n.ID == nil {
		return userRow{}, false
	}
	return userRow{
		ID:        *n.ID,
		Email:     *n.Email,
		Name:      *n.Name,
		CreatedAt: *n.CreatedAt,
	}, true
}

// projectRowRelDest returns scan destinations for a projectRow loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func projectRowRelDest(t *projectRow) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = projectRowDest(t, i)
	}
	return dest
}

// userRowRelDest returns scan destinations for a userRow loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func userRowRelDest(t *userRow) []any {
	dest := make([]any, 4)
	for i := range dest {
		dest[i] = userRowDest(t, i)
	}
	return dest
}

// projectRowOwnerColumns are the columns of public.users that projectRow.Owner reads.
var projectRowOwnerColumns = []string{
	"id",
	"email",
	"name",
	"created_at",
}

// projectRowOwnerKeys pairs the columns Owner matches on, in the order owner_id declares them.
var projectRowOwnerKeys = []orm.RelKey{
	{Parent: "owner_id", Target: "id", Type: "int8"},
}

// projectRowOwnerBind allocates one row's worth of storage for projectRow.Owner and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func projectRowOwnerBind() ([]any, func(*projectRow)) {
	var n userRowNulls
	return userRowNullDest(&n), func(e *projectRow) {
		if v, ok := userRowFromNulls(&n); ok {
			e.Owner = orm.NewOne(&v)
			return
		}
		e.Owner = orm.Absent[userRow]()
	}
}

// projectRowOwnerAttach sets projectRow.Owner from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func projectRowOwnerAttach(e *projectRow, t *userRow) {
	if t == nil {
		e.Owner = orm.Absent[userRow]()
		return
	}
	e.Owner = orm.NewOne(t)
}

// projectRowOwnerRefs appends pointers to the rows projectRow.Owner loaded, which is what a
// relation of userRow is loaded against.
func projectRowOwnerRefs(e *projectRow, out []*userRow) []*userRow {
	if v, ok := e.Owner.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// projectRowOwnerLoadKeys reads the keys of projectRow.Owner from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func projectRowOwnerLoadKeys(parents []*projectRow) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.OwnerID
	}
	return []any{
		k0,
	}, nil
}

// userRowProjectsColumns are the columns of public.projects that userRow.Projects reads.
var userRowProjectsColumns = []string{
	"id",
	"owner_id",
	"slug",
	"name",
	"created_at",
}

// userRowProjectsKeys pairs the columns Projects matches on, in the order owner_id declares them.
var userRowProjectsKeys = []orm.RelKey{
	{Parent: "id", Target: "owner_id", Type: "int8"},
}

// userRowProjectsAttach sets userRow.Projects from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userRowProjectsAttach(e *userRow, rows []projectRow) { e.Projects = orm.NewManyFrom(rows) }

// userRowProjectsRefs appends pointers to the rows userRow.Projects loaded, which is what a
// relation of projectRow is loaded against.
func userRowProjectsRefs(e *userRow, out []*projectRow) []*projectRow {
	rows, ok := e.Projects.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userRowProjectsLoadKeys reads the keys of userRow.Projects from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userRowProjectsLoadKeys(parents []*userRow) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
