// Code generated by orm. DO NOT EDIT.

package gisdemo

import (
	"context"

	"github.com/AlexAli29/orm"
	"github.com/jackc/pgx/v5"
)

// DB reads this package's entities through one executor.
//
// The repositories are the runtime's generic ones: nothing about reading a
// row differs per entity, so nothing per entity is generated for it.
//
// A view gets a read-only repository. It has no Insert, Update, Delete or
// CopyFrom — not methods that fail, no methods — so writing through a view
// is a compile error at the line that tried rather than a runtime error on
// the path least likely to be tested.
type DB struct {
	ex       orm.Executor
	Places   *orm.Repo[Place]
	Readings *orm.Repo[Reading]
	Roads    *orm.Repo[Road]
	Zones    *orm.Repo[Zone]
}

// New binds the generated metadata to ex, which may be a *pgxpool.Pool, a
// pgx.Tx or a *pgx.Conn.
func New(ex orm.Executor) *DB {
	return &DB{
		ex:       ex,
		Places:   orm.NewRepo(ex, &placeMeta),
		Readings: orm.NewRepo(ex, &readingMeta),
		Roads:    orm.NewRepo(ex, &roadMeta),
		Zones:    orm.NewRepo(ex, &zoneMeta),
	}
}

// Executor returns the executor every repository here reads through.
//
// Inside a transaction callback that is the transaction, which is what lets
// code written against an executor rather than against DB take part in one.
func (db *DB) Executor() orm.Executor { return db.ex }

// Tx runs fn inside a transaction.
//
// The DB handed to the callback is a new one bound to the transaction, so
// every repository reached through it is in the transaction and the receiver's
// repositories are not:
//
//	err := db.Tx(ctx, func(tx *DB) error {
//	    place, err := tx.Places.Insert(ctx, place)
//	    return err
//	})
//
// Returning nil commits and returning an error rolls back. Calling it again on
// the transaction's own DB nests, which pgx implements with a savepoint.
// Nothing is retried.
func (db *DB) Tx(ctx context.Context, fn func(*DB) error) error {
	return orm.RunTx(ctx, db.ex, func(ex orm.Executor) error { return fn(New(ex)) })
}

// TxOptions runs fn inside a transaction with the given characteristics.
//
// Zero options mean the same as [DB.Tx]. Non-zero options inside a transaction
// return orm.ErrNestedTxOptions, because PostgreSQL sets them for a transaction
// rather than for a savepoint inside one.
func (db *DB) TxOptions(ctx context.Context, opts pgx.TxOptions, fn func(*DB) error) error {
	return orm.RunTxOptions(ctx, db.ex, opts, func(ex orm.Executor) error { return fn(New(ex)) })
}

// RegisterTypes teaches a connection the PostgreSQL types this package's
// entities use that pgx does not know by default.
//
// Enums, domains and composites have OIDs assigned when they were created, so
// they are per-database facts a driver can only learn by asking. Wire it into
// a pool so every connection is taught once:
//
//	cfg, err := pgxpool.ParseConfig(dsn)
//	if err != nil {
//	    return err
//	}
//	cfg.AfterConnect = gisdemo.RegisterTypes
//	pool, err := pgxpool.NewWithConfig(ctx, cfg)
//
// This package's entities use no such types, so this is a no-op kept for the
// sake of the pool setup above staying the same when one is added.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error { return nil }
