// Code generated by orm. DO NOT EDIT.

package gisdemo

import (
	"time"

	"github.com/AlexAli29/orm"
	"github.com/AlexAli29/orm/postgis"
)

// placesSource is the occurrence of public.places that Places reads from.
var placesSource = orm.NewSource("public", "places")

// placeTable holds one typed descriptor per mapped column of public.places.
type placeTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Place, int64]
	Name      orm.TextCol[Place]
	Spot      postgis.GeogCol[Place]
	Location  postgis.GeomCol[Place]
	Projected postgis.NullGeomCol[Place]
	Footprint postgis.NullGeomCol[Place]
	Sketch    postgis.NullGeomCol[Place]
	CreatedAt orm.OrdCol[Place, time.Time]
}

// newPlaceTable builds the descriptors for one occurrence of public.places.
func newPlaceTable(src *orm.Source) placeTable {
	return placeTable{
		src:       src,
		ID:        orm.NewOrdCol[Place, int64](src, "id"),
		Name:      orm.NewTextCol[Place](src, "name"),
		Spot:      postgis.NewGeogCol[Place](src, "spot", 4326, postgis.KindPoint, postgis.XY),
		Location:  postgis.NewGeomCol[Place](src, "location", 4326, postgis.KindPoint, postgis.XY),
		Projected: postgis.NewNullGeomCol[Place](src, "projected", 3857, postgis.KindPoint, postgis.XY),
		Footprint: postgis.NewNullGeomCol[Place](src, "footprint", 4326, postgis.KindPolygon, postgis.XY),
		Sketch:    postgis.NewNullGeomCol[Place](src, "sketch", 0, postgis.AnyKind, postgis.XY),
		CreatedAt: orm.NewOrdCol[Place, time.Time](src, "created_at"),
	}
}

// Places addresses the columns of public.places.
var Places = newPlaceTable(placesSource)

// As returns descriptors for a second occurrence of public.places under
// alias, leaving Places untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t placeTable) As(alias string) placeTable { return newPlaceTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t placeTable) Source() *orm.Source { return t.src }

// readingsSource is the occurrence of public.readings that Readings reads from.
var readingsSource = orm.NewSource("public", "readings")

// readingTable holds one typed descriptor per mapped column of public.readings.
type readingTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Reading, int64]
	Flat   postgis.GeomCol[Reading]
	Raised postgis.GeomCol[Reading]
	Marked postgis.GeomCol[Reading]
	ZM     postgis.GeomCol[Reading]
	Line3D postgis.NullGeomCol[Reading]
}

// newReadingTable builds the descriptors for one occurrence of public.readings.
func newReadingTable(src *orm.Source) readingTable {
	return readingTable{
		src:    src,
		ID:     orm.NewOrdCol[Reading, int64](src, "id"),
		Flat:   postgis.NewGeomCol[Reading](src, "flat", 4326, postgis.KindPoint, postgis.XY),
		Raised: postgis.NewGeomCol[Reading](src, "raised", 4326, postgis.KindPoint, postgis.XYZ),
		Marked: postgis.NewGeomCol[Reading](src, "marked", 4326, postgis.KindPoint, postgis.XYM),
		ZM:     postgis.NewGeomCol[Reading](src, "zm", 4326, postgis.KindPoint, postgis.XYZM),
		Line3D: postgis.NewNullGeomCol[Reading](src, "line3d", 4326, postgis.KindLineString, postgis.XYZ),
	}
}

// Readings addresses the columns of public.readings.
var Readings = newReadingTable(readingsSource)

// As returns descriptors for a second occurrence of public.readings under
// alias, leaving Readings untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t readingTable) As(alias string) readingTable { return newReadingTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t readingTable) Source() *orm.Source { return t.src }

// roadsSource is the occurrence of public.roads that Roads reads from.
var roadsSource = orm.NewSource("public", "roads")

// roadTable holds one typed descriptor per mapped column of public.roads.
type roadTable struct {
	src  *orm.Source
	ID   orm.OrdCol[Road, int64]
	Name orm.TextCol[Road]
	Path postgis.GeomCol[Road]
}

// newRoadTable builds the descriptors for one occurrence of public.roads.
func newRoadTable(src *orm.Source) roadTable {
	return roadTable{
		src:  src,
		ID:   orm.NewOrdCol[Road, int64](src, "id"),
		Name: orm.NewTextCol[Road](src, "name"),
		Path: postgis.NewGeomCol[Road](src, "path", 4326, postgis.KindLineString, postgis.XY),
	}
}

// Roads addresses the columns of public.roads.
var Roads = newRoadTable(roadsSource)

// As returns descriptors for a second occurrence of public.roads under
// alias, leaving Roads untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t roadTable) As(alias string) roadTable { return newRoadTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t roadTable) Source() *orm.Source { return t.src }

// zonesSource is the occurrence of public.zones that Zones reads from.
var zonesSource = orm.NewSource("public", "zones")

// zoneTable holds one typed descriptor per mapped column of public.zones.
type zoneTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Zone, int64]
	Name   orm.TextCol[Zone]
	Area   postgis.GeomCol[Zone]
	Centre postgis.NullGeomCol[Zone]
}

// newZoneTable builds the descriptors for one occurrence of public.zones.
func newZoneTable(src *orm.Source) zoneTable {
	return zoneTable{
		src:    src,
		ID:     orm.NewOrdCol[Zone, int64](src, "id"),
		Name:   orm.NewTextCol[Zone](src, "name"),
		Area:   postgis.NewGeomCol[Zone](src, "area", 4326, postgis.KindMultiPolygon, postgis.XY),
		Centre: postgis.NewNullGeomCol[Zone](src, "centre", 4326, postgis.KindPoint, postgis.XY),
	}
}

// Zones addresses the columns of public.zones.
var Zones = newZoneTable(zonesSource)

// As returns descriptors for a second occurrence of public.zones under
// alias, leaving Zones untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t zoneTable) As(alias string) zoneTable { return newZoneTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t zoneTable) Source() *orm.Source { return t.src }
