// Code generated by orm. DO NOT EDIT.

package gisdemo

import (
	"github.com/AlexAli29/orm"
)

// placeMeta describes how Place is read from public.places.
var placeMeta = orm.EntityMeta[Place]{
	Table:  orm.TableID{Schema: "public", Name: "places"},
	Source: placesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "spot", Field: "Spot", NotNull: true},
		{Name: "location", Field: "Location", NotNull: true},
		{Name: "projected", Field: "Projected"},
		{Name: "footprint", Field: "Footprint"},
		{Name: "sketch", Field: "Sketch"},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  placeDest,
	Value: placeValue,
}

// placeDest returns a pointer to the field holding column idx of public.places.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func placeDest(e *Place, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Name
	case 2:
		return &e.Spot
	case 3:
		return &e.Location
	case 4:
		return &e.Projected
	case 5:
		return &e.Footprint
	case 6:
		return &e.Sketch
	case 7:
		return &e.CreatedAt
	default:
		return nil
	}
}

// placeValue returns the value of the field holding column idx of public.places.
//
// It is the counterpart of placeDest and is written the same way, so an
// insert reads the entity without reflection either.
func placeValue(e *Place, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Name
	case 2:
		return e.Spot
	case 3:
		return e.Location
	case 4:
		return e.Projected
	case 5:
		return e.Footprint
	case 6:
		return e.Sketch
	case 7:
		return e.CreatedAt
	default:
		return nil
	}
}

// readingMeta describes how Reading is read from public.readings.
var readingMeta = orm.EntityMeta[Reading]{
	Table:  orm.TableID{Schema: "public", Name: "readings"},
	Source: readingsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "flat", Field: "Flat", NotNull: true},
		{Name: "raised", Field: "Raised", NotNull: true},
		{Name: "marked", Field: "Marked", NotNull: true},
		{Name: "zm", Field: "ZM", NotNull: true},
		{Name: "line3d", Field: "Line3D"},
	},
	Dest:  readingDest,
	Value: readingValue,
}

// readingDest returns a pointer to the field holding column idx of public.readings.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func readingDest(e *Reading, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Flat
	case 2:
		return &e.Raised
	case 3:
		return &e.Marked
	case 4:
		return &e.ZM
	case 5:
		return &e.Line3D
	default:
		return nil
	}
}

// readingValue returns the value of the field holding column idx of public.readings.
//
// It is the counterpart of readingDest and is written the same way, so an
// insert reads the entity without reflection either.
func readingValue(e *Reading, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Flat
	case 2:
		return e.Raised
	case 3:
		return e.Marked
	case 4:
		return e.ZM
	case 5:
		return e.Line3D
	default:
		return nil
	}
}

// roadMeta describes how Road is read from public.roads.
var roadMeta = orm.EntityMeta[Road]{
	Table:  orm.TableID{Schema: "public", Name: "roads"},
	Source: roadsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "path", Field: "Path", NotNull: true},
	},
	Dest:  roadDest,
	Value: roadValue,
}

// roadDest returns a pointer to the field holding column idx of public.roads.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func roadDest(e *Road, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Name
	case 2:
		return &e.Path
	default:
		return nil
	}
}

// roadValue returns the value of the field holding column idx of public.roads.
//
// It is the counterpart of roadDest and is written the same way, so an
// insert reads the entity without reflection either.
func roadValue(e *Road, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Name
	case 2:
		return e.Path
	default:
		return nil
	}
}

// zoneMeta describes how Zone is read from public.zones.
var zoneMeta = orm.EntityMeta[Zone]{
	Table:  orm.TableID{Schema: "public", Name: "zones"},
	Source: zonesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "area", Field: "Area", NotNull: true},
		{Name: "centre", Field: "Centre"},
	},
	Dest:  zoneDest,
	Value: zoneValue,
}

// zoneDest returns a pointer to the field holding column idx of public.zones.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func zoneDest(e *Zone, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Name
	case 2:
		return &e.Area
	case 3:
		return &e.Centre
	default:
		return nil
	}
}

// zoneValue returns the value of the field holding column idx of public.zones.
//
// It is the counterpart of zoneDest and is written the same way, so an
// insert reads the entity without reflection either.
func zoneValue(e *Zone, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Name
	case 2:
		return e.Area
	case 3:
		return e.Centre
	default:
		return nil
	}
}
