// Code generated by orm. DO NOT EDIT.

package domain

import (
	"github.com/AlexAli29/orm"
)

// categoryMeta describes how Category is read from public.categories.
var categoryMeta = orm.EntityMeta[Category]{
	Table:  orm.TableID{Schema: "public", Name: "categories"},
	Source: categoriesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "name", Field: "Name", NotNull: true},
	},
	Dest:  categoryDest,
	Value: categoryValue,
}

// categoryDest returns a pointer to the field holding column idx of public.categories.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func categoryDest(e *Category, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Name
	default:
		return nil
	}
}

// categoryValue returns the value of the field holding column idx of public.categories.
//
// It is the counterpart of categoryDest and is written the same way, so an
// insert reads the entity without reflection either.
func categoryValue(e *Category, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Name
	default:
		return nil
	}
}

// commentMeta describes how Comment is read from public.comments.
var commentMeta = orm.EntityMeta[Comment]{
	Table:  orm.TableID{Schema: "public", Name: "comments"},
	Source: commentsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "post_id", Field: "PostID", NotNull: true},
		{Name: "author_id", Field: "AuthorID", NotNull: true},
		{Name: "body", Field: "Body", NotNull: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  commentDest,
	Value: commentValue,
}

// commentDest returns a pointer to the field holding column idx of public.comments.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func commentDest(e *Comment, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.PostID
	case 2:
		return &e.AuthorID
	case 3:
		return &e.Body
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// commentValue returns the value of the field holding column idx of public.comments.
//
// It is the counterpart of commentDest and is written the same way, so an
// insert reads the entity without reflection either.
func commentValue(e *Comment, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.PostID
	case 2:
		return e.AuthorID
	case 3:
		return e.Body
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}

// postMeta describes how Post is read from public.posts.
var postMeta = orm.EntityMeta[Post]{
	Table:  orm.TableID{Schema: "public", Name: "posts"},
	Source: postsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "author_id", Field: "AuthorID", NotNull: true},
		{Name: "category_id", Field: "CategoryID"},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "body", Field: "Body", NotNull: true},
		{Name: "status", Field: "Status", NotNull: true, HasDefault: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  postDest,
	Value: postValue,
}

// postDest returns a pointer to the field holding column idx of public.posts.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func postDest(e *Post, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.AuthorID
	case 2:
		return &e.CategoryID
	case 3:
		return &e.Title
	case 4:
		return &e.Body
	case 5:
		return &e.Status
	case 6:
		return &e.CreatedAt
	default:
		return nil
	}
}

// postValue returns the value of the field holding column idx of public.posts.
//
// It is the counterpart of postDest and is written the same way, so an
// insert reads the entity without reflection either.
func postValue(e *Post, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.AuthorID
	case 2:
		return e.CategoryID
	case 3:
		return e.Title
	case 4:
		return e.Body
	case 5:
		return e.Status
	case 6:
		return e.CreatedAt
	default:
		return nil
	}
}

// profileMeta describes how Profile is read from public.profiles.
var profileMeta = orm.EntityMeta[Profile]{
	Table:  orm.TableID{Schema: "public", Name: "profiles"},
	Source: profilesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "user_id", Field: "UserID", NotNull: true},
		{Name: "bio", Field: "Bio"},
	},
	Dest:  profileDest,
	Value: profileValue,
}

// profileDest returns a pointer to the field holding column idx of public.profiles.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func profileDest(e *Profile, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.UserID
	case 2:
		return &e.Bio
	default:
		return nil
	}
}

// profileValue returns the value of the field holding column idx of public.profiles.
//
// It is the counterpart of profileDest and is written the same way, so an
// insert reads the entity without reflection either.
func profileValue(e *Profile, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.UserID
	case 2:
		return e.Bio
	default:
		return nil
	}
}

// userMeta describes how User is read from public.users.
var userMeta = orm.EntityMeta[User]{
	Table:  orm.TableID{Schema: "public", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "active", Field: "Active", NotNull: true, HasDefault: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  userDest,
	Value: userValue,
}

// userDest returns a pointer to the field holding column idx of public.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userDest(e *User, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.Name
	case 3:
		return &e.Active
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// userValue returns the value of the field holding column idx of public.users.
//
// It is the counterpart of userDest and is written the same way, so an
// insert reads the entity without reflection either.
func userValue(e *User, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.Name
	case 3:
		return e.Active
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}
