// Code generated by orm. DO NOT EDIT.

package domain

import (
	"time"

	"github.com/AlexAli29/orm"
)

// categoriesSource is the occurrence of public.categories that Categories reads from.
var categoriesSource = orm.NewSource("public", "categories")

// categoryTable holds one typed descriptor per mapped column of public.categories.
type categoryTable struct {
	src  *orm.Source
	ID   orm.OrdCol[Category, int64]
	Name orm.TextCol[Category]
}

// newCategoryTable builds the descriptors for one occurrence of public.categories.
func newCategoryTable(src *orm.Source) categoryTable {
	return categoryTable{
		src:  src,
		ID:   orm.NewOrdCol[Category, int64](src, "id"),
		Name: orm.NewTextCol[Category](src, "name"),
	}
}

// Categories addresses the columns of public.categories.
var Categories = newCategoryTable(categoriesSource)

// As returns descriptors for a second occurrence of public.categories under
// alias, leaving Categories untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t categoryTable) As(alias string) categoryTable { return newCategoryTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t categoryTable) Source() *orm.Source { return t.src }

// commentsSource is the occurrence of public.comments that Comments reads from.
var commentsSource = orm.NewSource("public", "comments")

// commentTable holds one typed descriptor per mapped column of public.comments, and one
// per relation reconciliation proved.
type commentTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Comment, int64]
	PostID    orm.OrdCol[Comment, int64]
	AuthorID  orm.OrdCol[Comment, int64]
	Body      orm.TextCol[Comment]
	CreatedAt orm.OrdCol[Comment, time.Time]
	Author    orm.Rel[Comment, User]
}

// newCommentTable builds the descriptors for one occurrence of public.comments.
func newCommentTable(src *orm.Source) commentTable {
	return commentTable{
		src:       src,
		ID:        orm.NewOrdCol[Comment, int64](src, "id"),
		PostID:    orm.NewOrdCol[Comment, int64](src, "post_id"),
		AuthorID:  orm.NewOrdCol[Comment, int64](src, "author_id"),
		Body:      orm.NewTextCol[Comment](src, "body"),
		CreatedAt: orm.NewOrdCol[Comment, time.Time](src, "created_at"),
		Author: orm.NewOneRel(orm.OneRelSpec[Comment, User]{
			Name:        "Author",
			Parent:      src,
			Target:      usersSource,
			Keys:        commentAuthorKeys,
			Columns:     commentAuthorColumns,
			Bind:        commentAuthorBind,
			ExtractKeys: commentAuthorLoadKeys,
			Dest:        userRelDest,
			Attach:      commentAuthorAttach,
			Refs:        commentAuthorRefs,
		}),
	}
}

// Comments addresses the columns of public.comments.
var Comments = newCommentTable(commentsSource)

// As returns descriptors for a second occurrence of public.comments under
// alias, leaving Comments untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t commentTable) As(alias string) commentTable { return newCommentTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t commentTable) Source() *orm.Source { return t.src }

// postsSource is the occurrence of public.posts that Posts reads from.
var postsSource = orm.NewSource("public", "posts")

// postTable holds one typed descriptor per mapped column of public.posts, and one
// per relation reconciliation proved.
type postTable struct {
	src        *orm.Source
	ID         orm.OrdCol[Post, int64]
	AuthorID   orm.OrdCol[Post, int64]
	CategoryID orm.NullOrdCol[Post, int64]
	Title      orm.TextCol[Post]
	Body       orm.TextCol[Post]
	Status     orm.OrdCol[Post, PostStatus]
	CreatedAt  orm.OrdCol[Post, time.Time]
	Author     orm.Rel[Post, User]
	Category   orm.Rel[Post, Category]
	Comments   orm.Rel[Post, Comment]
}

// newPostTable builds the descriptors for one occurrence of public.posts.
func newPostTable(src *orm.Source) postTable {
	return postTable{
		src:        src,
		ID:         orm.NewOrdCol[Post, int64](src, "id"),
		AuthorID:   orm.NewOrdCol[Post, int64](src, "author_id"),
		CategoryID: orm.NewNullOrdCol[Post, int64](src, "category_id"),
		Title:      orm.NewTextCol[Post](src, "title"),
		Body:       orm.NewTextCol[Post](src, "body"),
		Status:     orm.NewOrdCol[Post, PostStatus](src, "status"),
		CreatedAt:  orm.NewOrdCol[Post, time.Time](src, "created_at"),
		Author: orm.NewOneRel(orm.OneRelSpec[Post, User]{
			Name:        "Author",
			Parent:      src,
			Target:      usersSource,
			Keys:        postAuthorKeys,
			Columns:     postAuthorColumns,
			Bind:        postAuthorBind,
			ExtractKeys: postAuthorLoadKeys,
			Dest:        userRelDest,
			Attach:      postAuthorAttach,
			Refs:        postAuthorRefs,
		}),
		Category: orm.NewOneRel(orm.OneRelSpec[Post, Category]{
			Name:        "Category",
			Parent:      src,
			Target:      categoriesSource,
			Keys:        postCategoryKeys,
			Columns:     postCategoryColumns,
			Bind:        postCategoryBind,
			ExtractKeys: postCategoryLoadKeys,
			Dest:        categoryRelDest,
			Attach:      postCategoryAttach,
			Refs:        postCategoryRefs,
		}),
		Comments: orm.NewManyRel(orm.ManyRelSpec[Post, Comment]{
			Name:        "Comments",
			Parent:      src,
			Target:      commentsSource,
			Keys:        postCommentsKeys,
			Columns:     postCommentsColumns,
			ExtractKeys: postCommentsLoadKeys,
			Dest:        commentRelDest,
			Attach:      postCommentsAttach,
			Refs:        postCommentsRefs,
		}),
	}
}

// Posts addresses the columns of public.posts.
var Posts = newPostTable(postsSource)

// As returns descriptors for a second occurrence of public.posts under
// alias, leaving Posts untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t postTable) As(alias string) postTable { return newPostTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t postTable) Source() *orm.Source { return t.src }

// profilesSource is the occurrence of public.profiles that Profiles reads from.
var profilesSource = orm.NewSource("public", "profiles")

// profileTable holds one typed descriptor per mapped column of public.profiles.
type profileTable struct {
	src    *orm.Source
	ID     orm.OrdCol[Profile, int64]
	UserID orm.OrdCol[Profile, int64]
	Bio    orm.NullTextCol[Profile]
}

// newProfileTable builds the descriptors for one occurrence of public.profiles.
func newProfileTable(src *orm.Source) profileTable {
	return profileTable{
		src:    src,
		ID:     orm.NewOrdCol[Profile, int64](src, "id"),
		UserID: orm.NewOrdCol[Profile, int64](src, "user_id"),
		Bio:    orm.NewNullTextCol[Profile](src, "bio"),
	}
}

// Profiles addresses the columns of public.profiles.
var Profiles = newProfileTable(profilesSource)

// As returns descriptors for a second occurrence of public.profiles under
// alias, leaving Profiles untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t profileTable) As(alias string) profileTable { return newProfileTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t profileTable) Source() *orm.Source { return t.src }

// usersSource is the occurrence of public.users that Users reads from.
var usersSource = orm.NewSource("public", "users")

// userTable holds one typed descriptor per mapped column of public.users, and one
// per relation reconciliation proved.
type userTable struct {
	src       *orm.Source
	ID        orm.OrdCol[User, int64]
	Email     orm.TextCol[User]
	Name      orm.TextCol[User]
	Active    orm.Col[User, bool]
	CreatedAt orm.OrdCol[User, time.Time]
	Profile   orm.Rel[User, Profile]
	Posts     orm.Rel[User, Post]
	Comments  orm.Rel[User, Comment]
}

// newUserTable builds the descriptors for one occurrence of public.users.
func newUserTable(src *orm.Source) userTable {
	return userTable{
		src:       src,
		ID:        orm.NewOrdCol[User, int64](src, "id"),
		Email:     orm.NewTextCol[User](src, "email"),
		Name:      orm.NewTextCol[User](src, "name"),
		Active:    orm.NewCol[User, bool](src, "active"),
		CreatedAt: orm.NewOrdCol[User, time.Time](src, "created_at"),
		Profile: orm.NewOneRel(orm.OneRelSpec[User, Profile]{
			Name:        "Profile",
			Parent:      src,
			Target:      profilesSource,
			Keys:        userProfileKeys,
			Columns:     userProfileColumns,
			Bind:        userProfileBind,
			ExtractKeys: userProfileLoadKeys,
			Dest:        profileRelDest,
			Attach:      userProfileAttach,
			Refs:        userProfileRefs,
		}),
		Posts: orm.NewManyRel(orm.ManyRelSpec[User, Post]{
			Name:        "Posts",
			Parent:      src,
			Target:      postsSource,
			Keys:        userPostsKeys,
			Columns:     userPostsColumns,
			ExtractKeys: userPostsLoadKeys,
			Dest:        postRelDest,
			Attach:      userPostsAttach,
			Refs:        userPostsRefs,
		}),
		Comments: orm.NewManyRel(orm.ManyRelSpec[User, Comment]{
			Name:        "Comments",
			Parent:      src,
			Target:      commentsSource,
			Keys:        userCommentsKeys,
			Columns:     userCommentsColumns,
			ExtractKeys: userCommentsLoadKeys,
			Dest:        commentRelDest,
			Attach:      userCommentsAttach,
			Refs:        userCommentsRefs,
		}),
	}
}

// Users addresses the columns of public.users.
var Users = newUserTable(usersSource)

// As returns descriptors for a second occurrence of public.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userTable) As(alias string) userTable { return newUserTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userTable) Source() *orm.Source { return t.src }
