// Code generated by orm. DO NOT EDIT.

package domain

import (
	"time"

	"github.com/AlexAli29/orm"
)

// categoryNulls mirrors Category with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Category would fail on those rather than report an absent
// relation, so the row lands here first.
type categoryNulls struct {
	ID   *int64
	Name *string
}

// categoryNullDest returns scan destinations for every column of public.categories.
func categoryNullDest(n *categoryNulls) []any {
	return []any{
		&n.ID,
		&n.Name,
	}
}

// categoryFromNulls rebuilds Category from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func categoryFromNulls(n *categoryNulls) (Category, bool) {
	if n.ID == nil {
		return Category{}, false
	}
	return Category{
		ID:   *n.ID,
		Name: *n.Name,
	}, true
}

// profileNulls mirrors Profile with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Profile would fail on those rather than report an absent
// relation, so the row lands here first.
type profileNulls struct {
	ID     *int64
	UserID *int64
	Bio    *string
}

// profileNullDest returns scan destinations for every column of public.profiles.
func profileNullDest(n *profileNulls) []any {
	return []any{
		&n.ID,
		&n.UserID,
		&n.Bio,
	}
}

// profileFromNulls rebuilds Profile from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func profileFromNulls(n *profileNulls) (Profile, bool) {
	if n.ID == nil {
		return Profile{}, false
	}
	return Profile{
		ID:     *n.ID,
		UserID: *n.UserID,
		Bio:    n.Bio,
	}, true
}

// userNulls mirrors User with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into User would fail on those rather than report an absent
// relation, so the row lands here first.
type userNulls struct {
	ID        *int64
	Email     *string
	Name      *string
	Active    *bool
	CreatedAt *time.Time
}

// userNullDest returns scan destinations for every column of public.users.
func userNullDest(n *userNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.Name,
		&n.Active,
		&n.CreatedAt,
	}
}

// userFromNulls rebuilds User from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func userFromNulls(n *userNulls) (User, bool) {
	if n.ID == nil {
		return User{}, false
	}
	return User{
		ID:        *n.ID,
		Email:     *n.Email,
		Name:      *n.Name,
		Active:    *n.Active,
		CreatedAt: *n.CreatedAt,
	}, true
}

// categoryRelDest returns scan destinations for a Category loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func categoryRelDest(t *Category) []any {
	dest := make([]any, 2)
	for i := range dest {
		dest[i] = categoryDest(t, i)
	}
	return dest
}

// commentRelDest returns scan destinations for a Comment loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func commentRelDest(t *Comment) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = commentDest(t, i)
	}
	return dest
}

// postRelDest returns scan destinations for a Post loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func postRelDest(t *Post) []any {
	dest := make([]any, 7)
	for i := range dest {
		dest[i] = postDest(t, i)
	}
	return dest
}

// profileRelDest returns scan destinations for a Profile loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func profileRelDest(t *Profile) []any {
	dest := make([]any, 3)
	for i := range dest {
		dest[i] = profileDest(t, i)
	}
	return dest
}

// userRelDest returns scan destinations for a User loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func userRelDest(t *User) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = userDest(t, i)
	}
	return dest
}

// commentAuthorColumns are the columns of public.users that Comment.Author reads.
var commentAuthorColumns = []string{
	"id",
	"email",
	"name",
	"active",
	"created_at",
}

// commentAuthorKeys pairs the columns Author matches on, in the order comments_author_id_fkey declares them.
var commentAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// commentAuthorBind allocates one row's worth of storage for Comment.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func commentAuthorBind() ([]any, func(*Comment)) {
	var n userNulls
	return userNullDest(&n), func(e *Comment) {
		if v, ok := userFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[User]()
	}
}

// commentAuthorAttach sets Comment.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func commentAuthorAttach(e *Comment, t *User) {
	if t == nil {
		e.Author = orm.Absent[User]()
		return
	}
	e.Author = orm.NewOne(t)
}

// commentAuthorRefs appends pointers to the rows Comment.Author loaded, which is what a
// relation of User is loaded against.
func commentAuthorRefs(e *Comment, out []*User) []*User {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// commentAuthorLoadKeys reads the keys of Comment.Author from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func commentAuthorLoadKeys(parents []*Comment) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.AuthorID
	}
	return []any{
		k0,
	}, nil
}

// postAuthorColumns are the columns of public.users that Post.Author reads.
var postAuthorColumns = []string{
	"id",
	"email",
	"name",
	"active",
	"created_at",
}

// postAuthorKeys pairs the columns Author matches on, in the order posts_author_id_fkey declares them.
var postAuthorKeys = []orm.RelKey{
	{Parent: "author_id", Target: "id", Type: "int8"},
}

// postAuthorBind allocates one row's worth of storage for Post.Author and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func postAuthorBind() ([]any, func(*Post)) {
	var n userNulls
	return userNullDest(&n), func(e *Post) {
		if v, ok := userFromNulls(&n); ok {
			e.Author = orm.NewOne(&v)
			return
		}
		e.Author = orm.Absent[User]()
	}
}

// postAuthorAttach sets Post.Author from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postAuthorAttach(e *Post, t *User) {
	if t == nil {
		e.Author = orm.Absent[User]()
		return
	}
	e.Author = orm.NewOne(t)
}

// postAuthorRefs appends pointers to the rows Post.Author loaded, which is what a
// relation of User is loaded against.
func postAuthorRefs(e *Post, out []*User) []*User {
	if v, ok := e.Author.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// postAuthorLoadKeys reads the keys of Post.Author from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func postAuthorLoadKeys(parents []*Post) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.AuthorID
	}
	return []any{
		k0,
	}, nil
}

// postCategoryColumns are the columns of public.categories that Post.Category reads.
var postCategoryColumns = []string{
	"id",
	"name",
}

// postCategoryKeys pairs the columns Category matches on, in the order posts_category_id_fkey declares them.
var postCategoryKeys = []orm.RelKey{
	{Parent: "category_id", Target: "id", Type: "int8"},
}

// postCategoryBind allocates one row's worth of storage for Post.Category and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func postCategoryBind() ([]any, func(*Post)) {
	var n categoryNulls
	return categoryNullDest(&n), func(e *Post) {
		if v, ok := categoryFromNulls(&n); ok {
			e.Category = orm.NewOne(&v)
			return
		}
		e.Category = orm.Absent[Category]()
	}
}

// postCategoryAttach sets Post.Category from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postCategoryAttach(e *Post, t *Category) {
	if t == nil {
		e.Category = orm.Absent[Category]()
		return
	}
	e.Category = orm.NewOne(t)
}

// postCategoryRefs appends pointers to the rows Post.Category loaded, which is what a
// relation of Category is loaded against.
func postCategoryRefs(e *Post, out []*Category) []*Category {
	if v, ok := e.Category.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// postCategoryLoadKeys reads the keys of Post.Category from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func postCategoryLoadKeys(parents []*Post) ([]any, error) {
	k0 := make([]*int64, len(parents))
	for i, p := range parents {
		k0[i] = p.CategoryID
	}
	return []any{
		k0,
	}, nil
}

// postCommentsColumns are the columns of public.comments that Post.Comments reads.
var postCommentsColumns = []string{
	"id",
	"post_id",
	"author_id",
	"body",
	"created_at",
}

// postCommentsKeys pairs the columns Comments matches on, in the order comments_post_id_fkey declares them.
var postCommentsKeys = []orm.RelKey{
	{Parent: "id", Target: "post_id", Type: "int8"},
}

// postCommentsAttach sets Post.Comments from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func postCommentsAttach(e *Post, rows []Comment) { e.Comments = orm.NewManyFrom(rows) }

// postCommentsRefs appends pointers to the rows Post.Comments loaded, which is what a
// relation of Comment is loaded against.
func postCommentsRefs(e *Post, out []*Comment) []*Comment {
	rows, ok := e.Comments.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// postCommentsLoadKeys reads the keys of Post.Comments from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func postCommentsLoadKeys(parents []*Post) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// userProfileColumns are the columns of public.profiles that User.Profile reads.
var userProfileColumns = []string{
	"id",
	"user_id",
	"bio",
}

// userProfileKeys pairs the columns Profile matches on, in the order profiles_user_id_fkey declares them.
var userProfileKeys = []orm.RelKey{
	{Parent: "id", Target: "user_id", Type: "int8"},
}

// userProfileBind allocates one row's worth of storage for User.Profile and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func userProfileBind() ([]any, func(*User)) {
	var n profileNulls
	return profileNullDest(&n), func(e *User) {
		if v, ok := profileFromNulls(&n); ok {
			e.Profile = orm.NewOne(&v)
			return
		}
		e.Profile = orm.Absent[Profile]()
	}
}

// userProfileAttach sets User.Profile from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userProfileAttach(e *User, t *Profile) {
	if t == nil {
		e.Profile = orm.Absent[Profile]()
		return
	}
	e.Profile = orm.NewOne(t)
}

// userProfileRefs appends pointers to the rows User.Profile loaded, which is what a
// relation of Profile is loaded against.
func userProfileRefs(e *User, out []*Profile) []*Profile {
	if v, ok := e.Profile.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// userProfileLoadKeys reads the keys of User.Profile from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userProfileLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// userPostsColumns are the columns of public.posts that User.Posts reads.
var userPostsColumns = []string{
	"id",
	"author_id",
	"category_id",
	"title",
	"body",
	"status",
	"created_at",
}

// userPostsKeys pairs the columns Posts matches on, in the order posts_author_id_fkey declares them.
var userPostsKeys = []orm.RelKey{
	{Parent: "id", Target: "author_id", Type: "int8"},
}

// userPostsAttach sets User.Posts from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userPostsAttach(e *User, rows []Post) { e.Posts = orm.NewManyFrom(rows) }

// userPostsRefs appends pointers to the rows User.Posts loaded, which is what a
// relation of Post is loaded against.
func userPostsRefs(e *User, out []*Post) []*Post {
	rows, ok := e.Posts.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userPostsLoadKeys reads the keys of User.Posts from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userPostsLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// userCommentsColumns are the columns of public.comments that User.Comments reads.
var userCommentsColumns = []string{
	"id",
	"post_id",
	"author_id",
	"body",
	"created_at",
}

// userCommentsKeys pairs the columns Comments matches on, in the order comments_author_id_fkey declares them.
var userCommentsKeys = []orm.RelKey{
	{Parent: "id", Target: "author_id", Type: "int8"},
}

// userCommentsAttach sets User.Comments from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userCommentsAttach(e *User, rows []Comment) { e.Comments = orm.NewManyFrom(rows) }

// userCommentsRefs appends pointers to the rows User.Comments loaded, which is what a
// relation of Comment is loaded against.
func userCommentsRefs(e *User, out []*Comment) []*Comment {
	rows, ok := e.Comments.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userCommentsLoadKeys reads the keys of User.Comments from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userCommentsLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
