// Code generated by orm. DO NOT EDIT.

package tenantb

import (
	"github.com/AlexAli29/orm"
)

// userMeta describes how User is read from schema_b.users.
var userMeta = orm.EntityMeta[User]{
	Table:  orm.TableID{Schema: "schema_b", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true},
		{Name: "label", Field: "Label", NotNull: true},
	},
	Dest:  userDest,
	Value: userValue,
}

// userDest returns a pointer to the field holding column idx of schema_b.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userDest(e *User, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Label
	default:
		return nil
	}
}

// userValue returns the value of the field holding column idx of schema_b.users.
//
// It is the counterpart of userDest and is written the same way, so an
// insert reads the entity without reflection either.
func userValue(e *User, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Label
	default:
		return nil
	}
}
