// Code generated by orm. DO NOT EDIT.

package postgres

import (
	"time"

	"github.com/AlexAli29/orm"
)

// auditEntriesSource is the occurrence of public.audit_entries that AuditEntries reads from.
var auditEntriesSource = orm.NewSource("public", "audit_entries")

// auditEntryTable holds one typed descriptor per mapped column of public.audit_entries.
type auditEntryTable struct {
	src      *orm.Source
	ID       orm.OrdCol[AuditEntry, int64]
	Action   orm.TextCol[AuditEntry]
	Subject  orm.TextCol[AuditEntry]
	Recorded orm.OrdCol[AuditEntry, time.Time]
}

// newAuditEntryTable builds the descriptors for one occurrence of public.audit_entries.
func newAuditEntryTable(src *orm.Source) auditEntryTable {
	return auditEntryTable{
		src:      src,
		ID:       orm.NewOrdCol[AuditEntry, int64](src, "id"),
		Action:   orm.NewTextCol[AuditEntry](src, "action"),
		Subject:  orm.NewTextCol[AuditEntry](src, "subject"),
		Recorded: orm.NewOrdCol[AuditEntry, time.Time](src, "recorded"),
	}
}

// AuditEntries addresses the columns of public.audit_entries.
var AuditEntries = newAuditEntryTable(auditEntriesSource)

// As returns descriptors for a second occurrence of public.audit_entries under
// alias, leaving AuditEntries untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t auditEntryTable) As(alias string) auditEntryTable { return newAuditEntryTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t auditEntryTable) Source() *orm.Source { return t.src }

// projectsSource is the occurrence of public.projects that Projects reads from.
var projectsSource = orm.NewSource("public", "projects")

// projectTable holds one typed descriptor per mapped column of public.projects, and one
// per relation reconciliation proved.
type projectTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Project, int64]
	OwnerID   orm.OrdCol[Project, int64]
	Slug      orm.TextCol[Project]
	Name      orm.TextCol[Project]
	CreatedAt orm.OrdCol[Project, time.Time]
	Owner     orm.Rel[Project, User]
	Tasks     orm.Rel[Project, Task]
}

// newProjectTable builds the descriptors for one occurrence of public.projects.
func newProjectTable(src *orm.Source) projectTable {
	return projectTable{
		src:       src,
		ID:        orm.NewOrdCol[Project, int64](src, "id"),
		OwnerID:   orm.NewOrdCol[Project, int64](src, "owner_id"),
		Slug:      orm.NewTextCol[Project](src, "slug"),
		Name:      orm.NewTextCol[Project](src, "name"),
		CreatedAt: orm.NewOrdCol[Project, time.Time](src, "created_at"),
		Owner: orm.NewOneRel(orm.OneRelSpec[Project, User]{
			Name:        "Owner",
			Parent:      src,
			Target:      usersSource,
			Keys:        projectOwnerKeys,
			Columns:     projectOwnerColumns,
			Bind:        projectOwnerBind,
			ExtractKeys: projectOwnerLoadKeys,
			Dest:        userRelDest,
			Attach:      projectOwnerAttach,
			Refs:        projectOwnerRefs,
		}),
		Tasks: orm.NewManyRel(orm.ManyRelSpec[Project, Task]{
			Name:        "Tasks",
			Parent:      src,
			Target:      tasksSource,
			Keys:        projectTasksKeys,
			Columns:     projectTasksColumns,
			ExtractKeys: projectTasksLoadKeys,
			Dest:        taskRelDest,
			Attach:      projectTasksAttach,
			Refs:        projectTasksRefs,
		}),
	}
}

// Projects addresses the columns of public.projects.
var Projects = newProjectTable(projectsSource)

// As returns descriptors for a second occurrence of public.projects under
// alias, leaving Projects untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t projectTable) As(alias string) projectTable { return newProjectTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t projectTable) Source() *orm.Source { return t.src }

// tasksSource is the occurrence of public.tasks that Tasks reads from.
var tasksSource = orm.NewSource("public", "tasks")

// taskTable holds one typed descriptor per mapped column of public.tasks, and one
// per relation reconciliation proved.
type taskTable struct {
	src       *orm.Source
	ID        orm.OrdCol[Task, int64]
	ProjectID orm.OrdCol[Task, int64]
	Title     orm.TextCol[Task]
	Done      orm.Col[Task, bool]
	CreatedAt orm.OrdCol[Task, time.Time]
	Project   orm.Rel[Task, Project]
}

// newTaskTable builds the descriptors for one occurrence of public.tasks.
func newTaskTable(src *orm.Source) taskTable {
	return taskTable{
		src:       src,
		ID:        orm.NewOrdCol[Task, int64](src, "id"),
		ProjectID: orm.NewOrdCol[Task, int64](src, "project_id"),
		Title:     orm.NewTextCol[Task](src, "title"),
		Done:      orm.NewCol[Task, bool](src, "done"),
		CreatedAt: orm.NewOrdCol[Task, time.Time](src, "created_at"),
		Project: orm.NewOneRel(orm.OneRelSpec[Task, Project]{
			Name:        "Project",
			Parent:      src,
			Target:      projectsSource,
			Keys:        taskProjectKeys,
			Columns:     taskProjectColumns,
			Bind:        taskProjectBind,
			ExtractKeys: taskProjectLoadKeys,
			Dest:        projectRelDest,
			Attach:      taskProjectAttach,
			Refs:        taskProjectRefs,
		}),
	}
}

// Tasks addresses the columns of public.tasks.
var Tasks = newTaskTable(tasksSource)

// As returns descriptors for a second occurrence of public.tasks under
// alias, leaving Tasks untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t taskTable) As(alias string) taskTable { return newTaskTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t taskTable) Source() *orm.Source { return t.src }

// usersSource is the occurrence of public.users that Users reads from.
var usersSource = orm.NewSource("public", "users")

// userTable holds one typed descriptor per mapped column of public.users, and one
// per relation reconciliation proved.
type userTable struct {
	src       *orm.Source
	ID        orm.OrdCol[User, int64]
	Email     orm.TextCol[User]
	Name      orm.TextCol[User]
	CreatedAt orm.OrdCol[User, time.Time]
	Projects  orm.Rel[User, Project]
}

// newUserTable builds the descriptors for one occurrence of public.users.
func newUserTable(src *orm.Source) userTable {
	return userTable{
		src:       src,
		ID:        orm.NewOrdCol[User, int64](src, "id"),
		Email:     orm.NewTextCol[User](src, "email"),
		Name:      orm.NewTextCol[User](src, "name"),
		CreatedAt: orm.NewOrdCol[User, time.Time](src, "created_at"),
		Projects: orm.NewManyRel(orm.ManyRelSpec[User, Project]{
			Name:        "Projects",
			Parent:      src,
			Target:      projectsSource,
			Keys:        userProjectsKeys,
			Columns:     userProjectsColumns,
			ExtractKeys: userProjectsLoadKeys,
			Dest:        projectRelDest,
			Attach:      userProjectsAttach,
			Refs:        userProjectsRefs,
		}),
	}
}

// Users addresses the columns of public.users.
var Users = newUserTable(usersSource)

// As returns descriptors for a second occurrence of public.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userTable) As(alias string) userTable { return newUserTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userTable) Source() *orm.Source { return t.src }
