// Code generated by orm. DO NOT EDIT.

package postgres

import (
	"github.com/AlexAli29/orm"
)

// auditEntryMeta describes how AuditEntry is read from public.audit_entries.
var auditEntryMeta = orm.EntityMeta[AuditEntry]{
	Table:  orm.TableID{Schema: "public", Name: "audit_entries"},
	Source: auditEntriesSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "action", Field: "Action", NotNull: true},
		{Name: "subject", Field: "Subject", NotNull: true},
		{Name: "recorded", Field: "Recorded", NotNull: true, HasDefault: true},
	},
	Dest:  auditEntryDest,
	Value: auditEntryValue,
}

// auditEntryDest returns a pointer to the field holding column idx of public.audit_entries.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func auditEntryDest(e *AuditEntry, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Action
	case 2:
		return &e.Subject
	case 3:
		return &e.Recorded
	default:
		return nil
	}
}

// auditEntryValue returns the value of the field holding column idx of public.audit_entries.
//
// It is the counterpart of auditEntryDest and is written the same way, so an
// insert reads the entity without reflection either.
func auditEntryValue(e *AuditEntry, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Action
	case 2:
		return e.Subject
	case 3:
		return e.Recorded
	default:
		return nil
	}
}

// projectMeta describes how Project is read from public.projects.
var projectMeta = orm.EntityMeta[Project]{
	Table:  orm.TableID{Schema: "public", Name: "projects"},
	Source: projectsSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "owner_id", Field: "OwnerID", NotNull: true},
		{Name: "slug", Field: "Slug", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  projectDest,
	Value: projectValue,
}

// projectDest returns a pointer to the field holding column idx of public.projects.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func projectDest(e *Project, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.OwnerID
	case 2:
		return &e.Slug
	case 3:
		return &e.Name
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// projectValue returns the value of the field holding column idx of public.projects.
//
// It is the counterpart of projectDest and is written the same way, so an
// insert reads the entity without reflection either.
func projectValue(e *Project, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.OwnerID
	case 2:
		return e.Slug
	case 3:
		return e.Name
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}

// taskMeta describes how Task is read from public.tasks.
var taskMeta = orm.EntityMeta[Task]{
	Table:  orm.TableID{Schema: "public", Name: "tasks"},
	Source: tasksSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "project_id", Field: "ProjectID", NotNull: true},
		{Name: "title", Field: "Title", NotNull: true},
		{Name: "done", Field: "Done", NotNull: true, HasDefault: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  taskDest,
	Value: taskValue,
}

// taskDest returns a pointer to the field holding column idx of public.tasks.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func taskDest(e *Task, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.ProjectID
	case 2:
		return &e.Title
	case 3:
		return &e.Done
	case 4:
		return &e.CreatedAt
	default:
		return nil
	}
}

// taskValue returns the value of the field holding column idx of public.tasks.
//
// It is the counterpart of taskDest and is written the same way, so an
// insert reads the entity without reflection either.
func taskValue(e *Task, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.ProjectID
	case 2:
		return e.Title
	case 3:
		return e.Done
	case 4:
		return e.CreatedAt
	default:
		return nil
	}
}

// userMeta describes how User is read from public.users.
var userMeta = orm.EntityMeta[User]{
	Table:  orm.TableID{Schema: "public", Name: "users"},
	Source: usersSource,
	Columns: []orm.ColumnMeta{
		{Name: "id", Field: "ID", NotNull: true, Identity: true},
		{Name: "email", Field: "Email", NotNull: true},
		{Name: "name", Field: "Name", NotNull: true},
		{Name: "created_at", Field: "CreatedAt", NotNull: true, HasDefault: true},
	},
	Dest:  userDest,
	Value: userValue,
}

// userDest returns a pointer to the field holding column idx of public.users.
//
// The switch is over a constant index into the column list above, so
// scanning a row costs no reflection and no lookup by name.
func userDest(e *User, idx int) any {
	switch idx {
	case 0:
		return &e.ID
	case 1:
		return &e.Email
	case 2:
		return &e.Name
	case 3:
		return &e.CreatedAt
	default:
		return nil
	}
}

// userValue returns the value of the field holding column idx of public.users.
//
// It is the counterpart of userDest and is written the same way, so an
// insert reads the entity without reflection either.
func userValue(e *User, idx int) any {
	switch idx {
	case 0:
		return e.ID
	case 1:
		return e.Email
	case 2:
		return e.Name
	case 3:
		return e.CreatedAt
	default:
		return nil
	}
}
