// Code generated by orm. DO NOT EDIT.

package postgres

import (
	"time"

	"github.com/AlexAli29/orm"
)

// projectNulls mirrors Project with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into Project would fail on those rather than report an absent
// relation, so the row lands here first.
type projectNulls struct {
	ID        *int64
	OwnerID   *int64
	Slug      *string
	Name      *string
	CreatedAt *time.Time
}

// projectNullDest returns scan destinations for every column of public.projects.
func projectNullDest(n *projectNulls) []any {
	return []any{
		&n.ID,
		&n.OwnerID,
		&n.Slug,
		&n.Name,
		&n.CreatedAt,
	}
}

// projectFromNulls rebuilds Project from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func projectFromNulls(n *projectNulls) (Project, bool) {
	if n.ID == nil {
		return Project{}, false
	}
	return Project{
		ID:        *n.ID,
		OwnerID:   *n.OwnerID,
		Slug:      *n.Slug,
		Name:      *n.Name,
		CreatedAt: *n.CreatedAt,
	}, true
}

// userNulls mirrors User with every column able to hold NULL.
//
// A LEFT JOIN that matched nothing returns NULL for every column of the
// target, including the ones the entity declares as plain values. Scanning
// straight into User would fail on those rather than report an absent
// relation, so the row lands here first.
type userNulls struct {
	ID        *int64
	Email     *string
	Name      *string
	CreatedAt *time.Time
}

// userNullDest returns scan destinations for every column of public.users.
func userNullDest(n *userNulls) []any {
	return []any{
		&n.ID,
		&n.Email,
		&n.Name,
		&n.CreatedAt,
	}
}

// userFromNulls rebuilds User from a scanned row, reporting whether there was a row
// at all.
//
// Presence is decided by the primary key, which PostgreSQL guarantees is
// not NULL for a real row. Testing some other column would confuse a row
// whose fields happen to be NULL with the absence of a row.
func userFromNulls(n *userNulls) (User, bool) {
	if n.ID == nil {
		return User{}, false
	}
	return User{
		ID:        *n.ID,
		Email:     *n.Email,
		Name:      *n.Name,
		CreatedAt: *n.CreatedAt,
	}, true
}

// projectRelDest returns scan destinations for a Project loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func projectRelDest(t *Project) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = projectDest(t, i)
	}
	return dest
}

// taskRelDest returns scan destinations for a Task loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func taskRelDest(t *Task) []any {
	dest := make([]any, 5)
	for i := range dest {
		dest[i] = taskDest(t, i)
	}
	return dest
}

// userRelDest returns scan destinations for a User loaded as a related row.
//
// A related row loaded in a statement of its own is read from the target
// table directly, so no column of it is NULL for want of a matching row and
// the entity's own scanner is enough.
func userRelDest(t *User) []any {
	dest := make([]any, 4)
	for i := range dest {
		dest[i] = userDest(t, i)
	}
	return dest
}

// projectOwnerColumns are the columns of public.users that Project.Owner reads.
var projectOwnerColumns = []string{
	"id",
	"email",
	"name",
	"created_at",
}

// projectOwnerKeys pairs the columns Owner matches on, in the order owner_id declares them.
var projectOwnerKeys = []orm.RelKey{
	{Parent: "owner_id", Target: "id", Type: "int8"},
}

// projectOwnerBind allocates one row's worth of storage for Project.Owner and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func projectOwnerBind() ([]any, func(*Project)) {
	var n userNulls
	return userNullDest(&n), func(e *Project) {
		if v, ok := userFromNulls(&n); ok {
			e.Owner = orm.NewOne(&v)
			return
		}
		e.Owner = orm.Absent[User]()
	}
}

// projectOwnerAttach sets Project.Owner from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func projectOwnerAttach(e *Project, t *User) {
	if t == nil {
		e.Owner = orm.Absent[User]()
		return
	}
	e.Owner = orm.NewOne(t)
}

// projectOwnerRefs appends pointers to the rows Project.Owner loaded, which is what a
// relation of User is loaded against.
func projectOwnerRefs(e *Project, out []*User) []*User {
	if v, ok := e.Owner.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// projectOwnerLoadKeys reads the keys of Project.Owner from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func projectOwnerLoadKeys(parents []*Project) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.OwnerID
	}
	return []any{
		k0,
	}, nil
}

// projectTasksColumns are the columns of public.tasks that Project.Tasks reads.
var projectTasksColumns = []string{
	"id",
	"project_id",
	"title",
	"done",
	"created_at",
}

// projectTasksKeys pairs the columns Tasks matches on, in the order project_id declares them.
var projectTasksKeys = []orm.RelKey{
	{Parent: "id", Target: "project_id", Type: "int8"},
}

// projectTasksAttach sets Project.Tasks from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func projectTasksAttach(e *Project, rows []Task) { e.Tasks = orm.NewManyFrom(rows) }

// projectTasksRefs appends pointers to the rows Project.Tasks loaded, which is what a
// relation of Task is loaded against.
func projectTasksRefs(e *Project, out []*Task) []*Task {
	rows, ok := e.Tasks.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// projectTasksLoadKeys reads the keys of Project.Tasks from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func projectTasksLoadKeys(parents []*Project) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}

// taskProjectColumns are the columns of public.projects that Task.Project reads.
var taskProjectColumns = []string{
	"id",
	"owner_id",
	"slug",
	"name",
	"created_at",
}

// taskProjectKeys pairs the columns Project matches on, in the order project_id declares them.
var taskProjectKeys = []orm.RelKey{
	{Parent: "project_id", Target: "id", Type: "int8"},
}

// taskProjectBind allocates one row's worth of storage for Task.Project and returns the
// function that attaches whatever was scanned.
//
// A relation that was asked for is always set: to the row if there was one,
// and to absent if there was not. Neither is the same as never having asked.
func taskProjectBind() ([]any, func(*Task)) {
	var n projectNulls
	return projectNullDest(&n), func(e *Task) {
		if v, ok := projectFromNulls(&n); ok {
			e.Project = orm.NewOne(&v)
			return
		}
		e.Project = orm.Absent[Project]()
	}
}

// taskProjectAttach sets Task.Project from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func taskProjectAttach(e *Task, t *Project) {
	if t == nil {
		e.Project = orm.Absent[Project]()
		return
	}
	e.Project = orm.NewOne(t)
}

// taskProjectRefs appends pointers to the rows Task.Project loaded, which is what a
// relation of Project is loaded against.
func taskProjectRefs(e *Task, out []*Project) []*Project {
	if v, ok := e.Project.Get(); ok && v != nil {
		out = append(out, v)
	}
	return out
}

// taskProjectLoadKeys reads the keys of Task.Project from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func taskProjectLoadKeys(parents []*Task) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ProjectID
	}
	return []any{
		k0,
	}, nil
}

// userProjectsColumns are the columns of public.projects that User.Projects reads.
var userProjectsColumns = []string{
	"id",
	"owner_id",
	"slug",
	"name",
	"created_at",
}

// userProjectsKeys pairs the columns Projects matches on, in the order owner_id declares them.
var userProjectsKeys = []orm.RelKey{
	{Parent: "id", Target: "owner_id", Type: "int8"},
}

// userProjectsAttach sets User.Projects from what a relation statement returned.
//
// It is called for every parent, including the ones nothing matched: a
// relation that was asked for and found nothing is loaded and empty, which is
// not the same fact as never having asked.
func userProjectsAttach(e *User, rows []Project) { e.Projects = orm.NewManyFrom(rows) }

// userProjectsRefs appends pointers to the rows User.Projects loaded, which is what a
// relation of Project is loaded against.
func userProjectsRefs(e *User, out []*Project) []*Project {
	rows, ok := e.Projects.Get()
	if !ok {
		return out
	}
	for i := range rows {
		out = append(out, &rows[i])
	}
	return out
}

// userProjectsLoadKeys reads the keys of User.Projects from the parents.
//
// The keys travel as one array per key column rather than one parameter per
// parent, so one statement covers every parent and the number of statements
// does not grow with the number of rows.
func userProjectsLoadKeys(parents []*User) ([]any, error) {
	k0 := make([]int64, len(parents))
	for i, p := range parents {
		k0[i] = p.ID
	}
	return []any{
		k0,
	}, nil
}
