// Code generated by orm. DO NOT EDIT.

package tenanta

import (
	"github.com/AlexAli29/orm"
	"github.com/google/uuid"
)

// usersSource is the occurrence of schema_a.users that Users reads from.
var usersSource = orm.NewSource("schema_a", "users")

// userTable holds one typed descriptor per mapped column of schema_a.users.
type userTable struct {
	src   *orm.Source
	ID    orm.OrdCol[User, uuid.UUID]
	Label orm.TextCol[User]
}

// newUserTable builds the descriptors for one occurrence of schema_a.users.
func newUserTable(src *orm.Source) userTable {
	return userTable{
		src:   src,
		ID:    orm.NewOrdCol[User, uuid.UUID](src, "id"),
		Label: orm.NewTextCol[User](src, "label"),
	}
}

// Users addresses the columns of schema_a.users.
var Users = newUserTable(usersSource)

// As returns descriptors for a second occurrence of schema_a.users under
// alias, leaving Users untouched. Use it with QueryFrom, or to compare
// one occurrence of the table against another.
func (t userTable) As(alias string) userTable { return newUserTable(t.src.As(alias)) }

// Source returns the occurrence these descriptors qualify against.
func (t userTable) Source() *orm.Source { return t.src }
