CREATE TYPE user_state AS ENUM ('pending', 'active', 'banned');

CREATE TABLE users (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        text NOT NULL,
    display_name text,
    state        user_state NOT NULL DEFAULT 'pending',
    tags         text[] NOT NULL DEFAULT '{}',
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id    bigint NOT NULL REFERENCES users(id),
    title        text NOT NULL,
    body         text,
    published_at timestamptz
);
