package plan

import (
	"encoding/json"
	"fmt"
	"strconv"
)

// Decoding a plan node.
//
// This is written by hand rather than with struct tags for two reasons. Every
// unrecognised key has to be kept, which a tagged struct cannot do; and the
// numbers have to be read defensively, because PostgreSQL's JSON writer emits
// some of them as JSON numbers, some as strings on some versions, and "Actual
// Rows" changed from an integer to a fractional average in PostgreSQL 13. A
// decoder that assumed either would break on a version it had not been run
// against.

// numeric reads a JSON value that should be a number, accepting the string form
// too.
//
// PostgreSQL's explain output is generated by hand-written code rather than by a
// serialiser, and it has historically quoted a value here and there. Accepting
// both costs one branch and removes a class of version-specific failure.
func numeric(b json.RawMessage) (float64, error) {
	if len(b) == 0 || string(b) == "null" {
		return 0, errAbsent
	}
	var f float64
	if err := json.Unmarshal(b, &f); err == nil {
		return f, nil
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return 0, fmt.Errorf("%s is not a number", b)
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0, fmt.Errorf("%q is not a number", s)
	}
	return f, nil
}

// errAbsent is the sentinel for a key whose value is JSON null, which is the
// same as the key not being there.
var errAbsent = fmt.Errorf("absent")

func floatField(b json.RawMessage, dst **float64) error {
	f, err := numeric(b)
	if err == errAbsent {
		return nil
	}
	if err != nil {
		return err
	}
	*dst = &f
	return nil
}

func intField(b json.RawMessage, dst **int64) error {
	f, err := numeric(b)
	if err == errAbsent {
		return nil
	}
	if err != nil {
		return err
	}
	// The counters PostgreSQL reports as integers are read as integers, and a
	// server that ever reports a fraction here is truncated rather than
	// rejected — but only for the fields this package has decided are counts.
	v := int64(f)
	*dst = &v
	return nil
}

func stringField(b json.RawMessage, dst *string) error {
	if len(b) == 0 || string(b) == "null" {
		return nil
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		// A non-string where a string was expected is kept as its JSON, which is
		// more useful than failing.
		*dst = string(b)
		return nil
	}
	*dst = s
	return nil
}

func boolField(b json.RawMessage, dst *bool) error {
	if len(b) == 0 || string(b) == "null" {
		return nil
	}
	return json.Unmarshal(b, dst)
}

func boolPtrField(b json.RawMessage, dst **bool) error {
	if len(b) == 0 || string(b) == "null" {
		return nil
	}
	var v bool
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	*dst = &v
	return nil
}

func stringsField(b json.RawMessage, dst *[]string) error {
	if len(b) == 0 || string(b) == "null" {
		return nil
	}
	var out []string
	if err := json.Unmarshal(b, &out); err != nil {
		return err
	}
	*dst = out
	return nil
}

// parseNode reads one plan node and its children.
func parseNode(data json.RawMessage) (Node, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return Node{}, &ParseError{Reason: "a plan node is not an object", Err: err}
	}

	var n Node
	// The buffer and WAL groups are collected as they are met, because their
	// keys are siblings of the node's own rather than a nested object.
	var buf Buffers
	var wal WAL
	var sawBuffers, sawWAL bool

	setters := map[string]func(json.RawMessage) error{
		"Node Type": func(b json.RawMessage) error {
			var s string
			err := stringField(b, &s)
			n.Type = NodeType(s)
			return err
		},
		"Parent Relationship": func(b json.RawMessage) error { return stringField(b, &n.ParentRelationship) },
		"Subplan Name":        func(b json.RawMessage) error { return stringField(b, &n.SubplanName) },
		"Parallel Aware":      func(b json.RawMessage) error { return boolField(b, &n.ParallelAware) },
		"Async Capable":       func(b json.RawMessage) error { return boolField(b, &n.AsyncCapable) },
		"Relation Name":       func(b json.RawMessage) error { return stringField(b, &n.RelationName) },
		"Schema":              func(b json.RawMessage) error { return stringField(b, &n.Schema) },
		"Alias":               func(b json.RawMessage) error { return stringField(b, &n.Alias) },
		"Index Name":          func(b json.RawMessage) error { return stringField(b, &n.IndexName) },
		"Scan Direction":      func(b json.RawMessage) error { return stringField(b, &n.ScanDirection) },
		"CTE Name":            func(b json.RawMessage) error { return stringField(b, &n.CTEName) },
		"Function Name":       func(b json.RawMessage) error { return stringField(b, &n.FunctionName) },
		"Tuplestore Name":     func(b json.RawMessage) error { return stringField(b, &n.TupleStore) },
		"Join Type":           func(b json.RawMessage) error { return stringField(b, &n.JoinType) },
		"Inner Unique":        func(b json.RawMessage) error { return boolPtrField(b, &n.InnerUnique) },
		"Strategy":            func(b json.RawMessage) error { return stringField(b, &n.Strategy) },
		"Partial Mode":        func(b json.RawMessage) error { return stringField(b, &n.PartialMode) },
		"Operation":           func(b json.RawMessage) error { return stringField(b, &n.Operation) },

		"Startup Cost": func(b json.RawMessage) error { return floatField(b, &n.StartupCost) },
		"Total Cost":   func(b json.RawMessage) error { return floatField(b, &n.TotalCost) },
		"Plan Rows":    func(b json.RawMessage) error { return floatField(b, &n.PlanRows) },
		"Plan Width":   func(b json.RawMessage) error { return intField(b, &n.PlanWidth) },

		"Actual Startup Time": func(b json.RawMessage) error { return floatField(b, &n.ActualStartupTime) },
		"Actual Total Time":   func(b json.RawMessage) error { return floatField(b, &n.ActualTotalTime) },
		// Actual Rows is the per-loop average and became fractional in
		// PostgreSQL 13, so it is a float. Multiplying by Actual Loops is how a
		// total is obtained, and Node.TotalRows does it.
		"Actual Rows":  func(b json.RawMessage) error { return floatField(b, &n.ActualRows) },
		"Actual Loops": func(b json.RawMessage) error { return floatField(b, &n.ActualLoops) },

		"Filter":          func(b json.RawMessage) error { return stringField(b, &n.Filter) },
		"Index Cond":      func(b json.RawMessage) error { return stringField(b, &n.IndexCond) },
		"Recheck Cond":    func(b json.RawMessage) error { return stringField(b, &n.RecheckCond) },
		"Join Filter":     func(b json.RawMessage) error { return stringField(b, &n.JoinFilter) },
		"Hash Cond":       func(b json.RawMessage) error { return stringField(b, &n.HashCond) },
		"Merge Cond":      func(b json.RawMessage) error { return stringField(b, &n.MergeCond) },
		"TID Cond":        func(b json.RawMessage) error { return stringField(b, &n.TidCond) },
		"One-Time Filter": func(b json.RawMessage) error { return stringField(b, &n.OneTimeFilter) },

		"Rows Removed by Filter":        func(b json.RawMessage) error { return floatField(b, &n.RowsRemovedByFilter) },
		"Rows Removed by Join Filter":   func(b json.RawMessage) error { return floatField(b, &n.RowsRemovedByJoin) },
		"Rows Removed by Recheck":       func(b json.RawMessage) error { return floatField(b, &n.RowsRemovedByRecheck) },
		"Rows Removed by Index Recheck": func(b json.RawMessage) error { return floatField(b, &n.RowsRemovedByIndexRecheck) },
		"Heap Fetches":                  func(b json.RawMessage) error { return floatField(b, &n.HeapFetches) },
		"Exact Heap Blocks":             func(b json.RawMessage) error { return floatField(b, &n.ExactHeapBlocks) },
		"Lossy Heap Blocks":             func(b json.RawMessage) error { return floatField(b, &n.LossyHeapBlocks) },

		"Sort Key":          func(b json.RawMessage) error { return stringsField(b, &n.SortKey) },
		"Presorted Key":     func(b json.RawMessage) error { return stringsField(b, &n.PresortedKey) },
		"Sort Method":       func(b json.RawMessage) error { return stringField(b, &n.SortMethod) },
		"Sort Space Used":   func(b json.RawMessage) error { return intField(b, &n.SortSpaceUsed) },
		"Sort Space Type":   func(b json.RawMessage) error { return stringField(b, &n.SortSpaceType) },
		"Group Key":         func(b json.RawMessage) error { return stringsField(b, &n.GroupKey) },
		"Peak Memory Usage": func(b json.RawMessage) error { return intField(b, &n.PeakMemoryUsage) },
		"HashAgg Batches":   func(b json.RawMessage) error { return intField(b, &n.HashAggBatches) },

		"Hash Buckets":          func(b json.RawMessage) error { return intField(b, &n.HashBuckets) },
		"Original Hash Buckets": func(b json.RawMessage) error { return intField(b, &n.OriginalHashBuckets) },
		"Hash Batches":          func(b json.RawMessage) error { return intField(b, &n.HashBatches) },
		"Original Hash Batches": func(b json.RawMessage) error { return intField(b, &n.OriginalHashBatches) },

		"Workers Planned":  func(b json.RawMessage) error { return intField(b, &n.WorkersPlanned) },
		"Workers Launched": func(b json.RawMessage) error { return intField(b, &n.WorkersLaunched) },

		"Output": func(b json.RawMessage) error { return stringsField(b, &n.Output) },

		"Shared Hit Blocks":     func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.SharedHit) },
		"Shared Read Blocks":    func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.SharedRead) },
		"Shared Dirtied Blocks": func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.SharedDirtied) },
		"Shared Written Blocks": func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.SharedWritten) },
		"Local Hit Blocks":      func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.LocalHit) },
		"Local Read Blocks":     func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.LocalRead) },
		"Local Dirtied Blocks":  func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.LocalDirtied) },
		"Local Written Blocks":  func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.LocalWritten) },
		"Temp Read Blocks":      func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.TempRead) },
		"Temp Written Blocks":   func(b json.RawMessage) error { sawBuffers = true; return intField(b, &buf.TempWritten) },
		// The I/O timing keys were renamed in PostgreSQL 17: the older pair is
		// "I/O Read Time" and the newer is "Shared I/O Read Time". Both are read
		// into the same field, because they are the same measurement.
		"I/O Read Time":         func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.SharedReadTime) },
		"I/O Write Time":        func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.SharedWriteTime) },
		"Shared I/O Read Time":  func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.SharedReadTime) },
		"Shared I/O Write Time": func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.SharedWriteTime) },
		"Local I/O Read Time":   func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.LocalReadTime) },
		"Local I/O Write Time":  func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.LocalWriteTime) },
		"Temp I/O Read Time":    func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.TempReadTime) },
		"Temp I/O Write Time":   func(b json.RawMessage) error { sawBuffers = true; return floatField(b, &buf.TempWriteTime) },

		"WAL Records":      func(b json.RawMessage) error { sawWAL = true; return intField(b, &wal.Records) },
		"WAL FPI":          func(b json.RawMessage) error { sawWAL = true; return intField(b, &wal.FPI) },
		"WAL Bytes":        func(b json.RawMessage) error { sawWAL = true; return floatField(b, &wal.Bytes) },
		"WAL Buffers Full": func(b json.RawMessage) error { sawWAL = true; return intField(b, &wal.Buffers) },
	}

	for key, b := range raw {
		if key == "Plans" {
			var children []json.RawMessage
			if err := json.Unmarshal(b, &children); err != nil {
				return Node{}, &ParseError{Reason: `"Plans" is not an array`, Err: err}
			}
			for _, c := range children {
				child, err := parseNode(c)
				if err != nil {
					return Node{}, err
				}
				n.Plans = append(n.Plans, child)
			}
			continue
		}
		set, ok := setters[key]
		if !ok {
			// A field this package does not model is kept rather than dropped:
			// a newer server's plan is still fully readable through Extra.
			if n.Extra == nil {
				n.Extra = make(map[string]json.RawMessage)
			}
			n.Extra[key] = b
			continue
		}
		if err := set(b); err != nil {
			return Node{}, &ParseError{Reason: fmt.Sprintf("reading %q", key), Err: err}
		}
	}

	if n.Type == "" {
		return Node{}, &ParseError{Reason: `a plan node has no "Node Type"`}
	}
	if sawBuffers {
		n.Buffers = &buf
	}
	if sawWAL {
		n.WAL = &wal
	}
	return n, nil
}
