// Command apimanifest renders the exported API of a set of packages as
// canonical text.
//
// It exists because a count of exported symbols does not define an API. Removing
// one function and adding another keeps the count identical and breaks every
// caller, which is how a project can watch a number and still ship a breaking
// change. What defines an API is its structure: which packages exist, what they
// export, and the exact shape of every signature, field and method set.
//
// The output is a committed snapshot. CI regenerates it and diffs; any change to
// the public surface therefore appears in a pull request as a change to a file
// somebody has to approve. That is the whole mechanism — it does not decide
// whether a change is acceptable, it makes the change impossible to miss.
//
// Usage:
//
//	go run ./internal/tools/apimanifest -dir . -out api/orm.txt <packages...>
//
// The rendering is derived from go/types rather than from source text, so it
// reports what the compiler sees: an embedded field's promoted methods, a type
// alias's target, an inferred constraint. Nothing here parses Go with regular
// expressions.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/types"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	dir := flag.String("dir", ".", "module directory to load packages from")
	out := flag.String("out", "", "file to write (default stdout)")
	flag.Parse()

	patterns := flag.Args()
	if len(patterns) == 0 {
		fmt.Fprintln(os.Stderr, "apimanifest: no package patterns given")
		os.Exit(2)
	}

	text, err := render(*dir, patterns)
	if err != nil {
		fmt.Fprintf(os.Stderr, "apimanifest: %v\n", err)
		os.Exit(1)
	}
	if *out == "" {
		os.Stdout.WriteString(text)
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "apimanifest: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(text), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "apimanifest: %v\n", err)
		os.Exit(1)
	}
}

// render loads the packages and returns the canonical manifest.
func render(dir string, patterns []string) (string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo |
			packages.NeedSyntax | packages.NeedDeps | packages.NeedImports,
		Dir: dir,
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		return "", err
	}
	var problems []string
	for _, p := range pkgs {
		for _, e := range p.Errors {
			problems = append(problems, fmt.Sprintf("%s: %v", p.PkgPath, e))
		}
	}
	if len(problems) > 0 {
		// A manifest built from packages that do not type-check would be a
		// manifest of whatever survived, which is worse than no manifest.
		return "", fmt.Errorf("the packages do not load:\n    %s", strings.Join(problems, "\n    "))
	}

	slices.SortFunc(pkgs, func(a, b *packages.Package) int { return strings.Compare(a.PkgPath, b.PkgPath) })

	var b strings.Builder
	b.WriteString("# Canonical public API manifest.\n")
	b.WriteString("# Generated by internal/tools/apimanifest. Do not edit by hand.\n")
	b.WriteString("# A change here is a change to the public contract; see docs/compatibility.md.\n")

	// Types declared in unexported packages but reachable through the public
	// surface — most often through a type alias — are part of the contract even
	// though the package that declares them is not. Their shapes are collected
	// while rendering and appended, so that adding a method to one of them
	// shows up as a manifest change rather than as nothing at all.
	reach := &reachable{seen: map[string]bool{}, shapes: map[string][]string{}}
	for _, p := range pkgs {
		if p.Types == nil || skip(p.PkgPath) {
			continue
		}
		renderPackage(&b, p, reach)
	}
	reach.render(&b)
	return b.String(), nil
}

// reachable records named types that the public API exposes from packages the
// manifest otherwise skips.
type reachable struct {
	seen   map[string]bool
	shapes map[string][]string
}

// note records a type if it is declared in a skipped package.
//
// It recurses through the type's own structure, because a public alias to an
// internal struct exposes that struct's field types too.
func (r *reachable) note(t types.Type, depth int) {
	if t == nil || depth > 6 {
		return
	}
	switch u := t.(type) {
	case *types.Alias:
		r.note(types.Unalias(u), depth+1)
	case *types.Pointer:
		r.note(u.Elem(), depth+1)
	case *types.Slice:
		r.note(u.Elem(), depth+1)
	case *types.Array:
		r.note(u.Elem(), depth+1)
	case *types.Map:
		r.note(u.Key(), depth+1)
		r.note(u.Elem(), depth+1)
	case *types.Chan:
		r.note(u.Elem(), depth+1)
	case *types.Signature:
		// The constraints too. A public generic function constrained by an
		// internal interface publishes that interface: narrowing it stops
		// callers' code compiling, and nothing else in the manifest would say so.
		for i := range u.TypeParams().Len() {
			r.note(u.TypeParams().At(i), depth+1)
		}
		for i := range u.Params().Len() {
			r.note(u.Params().At(i).Type(), depth+1)
		}
		for i := range u.Results().Len() {
			r.note(u.Results().At(i).Type(), depth+1)
		}
	case *types.TypeParam:
		r.note(u.Constraint(), depth+1)
	case *types.Struct:
		// Exported fields only. An unexported field's type is not observable
		// from outside — only the slot it occupies is, because it displaces a
		// position in an unkeyed literal, and that is recorded as a slot rather
		// than as a type. Following the type as well would put the compiler's
		// own internals in the manifest and make every internal refactor look
		// like a public API change, which is how a compatibility gate becomes a
		// diff nobody reads.
		for i := range u.NumFields() {
			if f := u.Field(i); f.Exported() {
				r.note(f.Type(), depth+1)
			}
		}
	case *types.Interface:
		for i := range u.NumMethods() {
			if m := u.Method(i); m.Exported() {
				r.note(m.Type(), depth+1)
			}
		}
		for i := range u.NumEmbeddeds() {
			r.note(u.EmbeddedType(i), depth+1)
		}
	case *types.Union:
		for i := range u.Len() {
			r.note(u.Term(i).Type(), depth+1)
		}
	case *types.Named:
		obj := u.Obj()
		if obj.Pkg() == nil || !skip(obj.Pkg().Path()) {
			// Declared somewhere the manifest already covers.
			for i := range u.TypeArgs().Len() {
				r.note(u.TypeArgs().At(i), depth+1)
			}
			return
		}
		key := obj.Pkg().Path() + "." + obj.Name()
		if r.seen[key] {
			return
		}
		q := qualifier(obj.Pkg())
		r.seen[key] = true
		r.shapes[key] = shapeOf(u, q)
		// And onward through everything that shape mentions.
		//
		// Reachability does not stop at one hop. If the aliased type has an
		// exported field whose type is another internal type, a caller holding
		// the alias can read that field and everything on it, so its fields and
		// methods are just as much the public contract as the first type's —
		// and changing them breaks exactly the same callers. Recording only the
		// first hop is what let a two-level change through as no change at all.
		//
		// The recursion terminates on seen rather than on depth: each named
		// type is expanded once, and there are finitely many. Depth is reset
		// here for that reason; it guards structural nesting, not this.
		r.expand(u)
	}
}

// expand walks everything a recorded type's shape mentions, so that the second
// and later hops are recorded too.
func (r *reachable) expand(n *types.Named) {
	for i := range n.TypeArgs().Len() {
		r.note(n.TypeArgs().At(i), 0)
	}
	for i := range n.TypeParams().Len() {
		r.note(n.TypeParams().At(i), 0)
	}
	r.note(n.Underlying(), 0)
	for i := range n.NumMethods() {
		if m := n.Method(i); m.Exported() {
			r.note(m.Type(), 0)
		}
	}
}

// shapeOf renders an internal named type's exported shape.
func shapeOf(n *types.Named, q types.Qualifier) []string {
	var out []string
	switch u := n.Underlying().(type) {
	case *types.Struct:
		out = append(out, "  struct")
		for i := range u.NumFields() {
			f := u.Field(i)
			if !f.Exported() {
				out = append(out, fmt.Sprintf("  field <unexported> # %d", i))
				continue
			}
			out = append(out, fmt.Sprintf("  field %s %s%s", f.Name(), types.TypeString(f.Type(), q), tagOf(u.Tag(i))))
		}
	case *types.Interface:
		out = append(out, "  interface")
		// The type set, not only the method set. A constraint is usually all
		// type set and no methods, so rendering methods alone makes every
		// constraint look identical — and narrowing one stops a caller's code
		// compiling while the manifest says nothing changed.
		var terms []string
		for i := range u.NumEmbeddeds() {
			terms = append(terms, types.TypeString(u.EmbeddedType(i), q))
		}
		slices.Sort(terms)
		for _, t := range terms {
			out = append(out, "  embeds "+t)
		}
		for i := range u.NumMethods() {
			m := u.Method(i)
			if !m.Exported() {
				// The name and nothing else. An unexported method is not
				// callable from outside, but its presence is contract: it is
				// what makes the interface unimplementable outside its own
				// package, so removing the last one widens the API.
				out = append(out, "  method <unexported>")
				continue
			}
			out = append(out, "  method "+signature(m.Name(), m.Type().(*types.Signature), q))
		}
	default:
		out = append(out, "  "+types.TypeString(n.Underlying(), q))
	}
	var methods []string
	for i := range n.NumMethods() {
		m := n.Method(i)
		if !m.Exported() {
			continue
		}
		methods = append(methods, "  method "+signature(m.Name(), m.Type().(*types.Signature), q))
	}
	slices.Sort(methods)
	return append(out, methods...)
}

func (r *reachable) render(b *strings.Builder) {
	if len(r.shapes) == 0 {
		return
	}
	keys := make([]string, 0, len(r.shapes))
	for k := range r.shapes {
		keys = append(keys, k)
	}
	slices.Sort(keys)

	b.WriteString("\n# Types declared in unexported packages that the public API exposes.\n")
	b.WriteString("# Reaching one of these means its shape is part of the contract, whatever\n")
	b.WriteString("# package it lives in. Adding a method to one is a public API change.\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\nreachable %s\n", k)
		for _, l := range r.shapes[k] {
			b.WriteString(l)
			b.WriteString("\n")
		}
	}
}

// skip drops packages that carry no compatibility promise.
//
// Internal packages are unreachable by definition. A main package has no
// importable API at all — its exported identifiers are private in every sense
// that matters to a consumer.
func skip(path string) bool {
	return strings.Contains(path, "/internal/") ||
		strings.HasSuffix(path, "/internal") ||
		strings.Contains(path, "/testdata/")
}

func renderPackage(b *strings.Builder, p *packages.Package, reach *reachable) {
	scope := p.Types.Scope()
	names := scope.Names()

	// A main package exports nothing importable, so it is listed and left
	// empty: its presence is part of the module's shape, its identifiers are
	// not part of anyone's contract.
	if p.Name == "main" {
		fmt.Fprintf(b, "\npackage %s # command, no importable API\n", p.PkgPath)
		return
	}

	// Each object renders as a block, and the blocks are sorted by a key rather
	// than the lines being sorted individually: a type's fields and methods
	// belong under the type, where a reviewer reading a diff can see what
	// changed shape. Sorting the lines would scatter them alphabetically across
	// the package.
	//
	// The key groups by kind first so that constants, variables, functions and
	// types stay in predictable sections, and by name second. Neither depends on
	// declaration order, so moving a declaration between files changes nothing.
	type block struct {
		key   string
		lines []string
	}
	var blocks []block
	for _, name := range names {
		obj := scope.Lookup(name)
		if !obj.Exported() {
			continue
		}
		reach.note(obj.Type(), 0)
		lines := renderObject(p.Types, obj)
		if len(lines) == 0 {
			continue
		}
		blocks = append(blocks, block{key: sortKey(obj), lines: lines})
	}
	if len(blocks) == 0 {
		fmt.Fprintf(b, "\npackage %s # no exported API\n", p.PkgPath)
		return
	}
	slices.SortFunc(blocks, func(x, y block) int { return strings.Compare(x.key, y.key) })

	fmt.Fprintf(b, "\npackage %s\n", p.PkgPath)
	for _, blk := range blocks {
		for _, l := range blk.lines {
			b.WriteString(l)
			b.WriteString("\n")
		}
	}
}

// sortKey orders the manifest: constants, then variables, then functions, then
// types, each alphabetically.
func sortKey(obj types.Object) string {
	rank := "4"
	switch obj.(type) {
	case *types.Const:
		rank = "1"
	case *types.Var:
		rank = "2"
	case *types.Func:
		rank = "3"
	}
	return rank + "\x00" + obj.Name()
}

// renderObject renders one exported scope object and everything hanging off it.
func renderObject(pkg *types.Package, obj types.Object) []string {
	q := qualifier(pkg)
	switch o := obj.(type) {
	case *types.Const:
		// The value is part of the contract: an untyped constant a caller
		// compares against, or a bit flag whose number is written into a file.
		return []string{fmt.Sprintf("const %s %s = %s", o.Name(), types.TypeString(o.Type(), q), o.Val().ExactString())}

	case *types.Var:
		return []string{fmt.Sprintf("var %s %s", o.Name(), types.TypeString(o.Type(), q))}

	case *types.Func:
		return []string{"func " + signature(o.Name(), o.Type().(*types.Signature), q)}

	case *types.TypeName:
		return renderTypeName(pkg, o, q)
	}
	return nil
}

func renderTypeName(pkg *types.Package, o *types.TypeName, q types.Qualifier) []string {
	if o.IsAlias() {
		// An alias is the same type under another name, and swapping one for a
		// definition is a breaking change even though the name is unchanged.
		//
		// The target is unaliased before rendering. Go materialises aliases as
		// their own type whose String is the alias's own name, so printing it
		// directly yields "alias X = X" — which records nothing. What matters
		// here is exactly what X points at, including when that is a type in an
		// internal package: an alias to an internal type makes that type's
		// shape part of the public contract, and this is where that shows up.
		return []string{fmt.Sprintf("alias %s = %s", o.Name(), types.TypeString(types.Unalias(o.Type()), q))}
	}

	named, ok := o.Type().(*types.Named)
	if !ok {
		return []string{fmt.Sprintf("type %s %s", o.Name(), types.TypeString(o.Type(), q))}
	}

	head := "type " + o.Name() + typeParams(named.TypeParams(), q)
	under := named.Underlying()

	var out []string
	switch u := under.(type) {
	case *types.Struct:
		out = append(out, head+" struct")
		for i := range u.NumFields() {
			f := u.Field(i)
			if !f.Exported() {
				// An unexported field still affects whether a caller can use a
				// composite literal without field names, so its presence is
				// recorded without its name or type.
				out = append(out, fmt.Sprintf("\tfield %s.<unexported> # %d", o.Name(), i))
				continue
			}
			kind := "field"
			if f.Embedded() {
				kind = "embedded"
			}
			out = append(out, fmt.Sprintf("\t%s %s.%s %s%s", kind, o.Name(), f.Name(),
				types.TypeString(f.Type(), q), tagOf(u.Tag(i))))
		}

	case *types.Interface:
		out = append(out, head+" interface")
		// The method set is the contract in both directions: a caller relies on
		// what it can call, and an external implementer relies on what it must
		// provide. Adding a method breaks the second.
		for i := range u.NumMethods() {
			m := u.Method(i)
			if !m.Exported() {
				out = append(out, fmt.Sprintf("\tmethod %s.<unexported>", o.Name()))
				continue
			}
			out = append(out, "\tmethod "+o.Name()+"."+signature(m.Name(), m.Type().(*types.Signature), q))
		}
		for i := range u.NumEmbeddeds() {
			out = append(out, fmt.Sprintf("\tembeds %s %s", o.Name(), types.TypeString(u.EmbeddedType(i), q)))
		}

	default:
		out = append(out, fmt.Sprintf("%s %s", head, types.TypeString(under, q)))
	}

	// Methods declared on the named type, pointer and value receivers alike.
	var methods []string
	for i := range named.NumMethods() {
		m := named.Method(i)
		if !m.Exported() {
			continue
		}
		recv := o.Name()
		if _, isPtr := m.Type().(*types.Signature).Recv().Type().(*types.Pointer); isPtr {
			recv = "*" + o.Name()
		}
		methods = append(methods, fmt.Sprintf("\tmethod (%s) %s", recv, signature(m.Name(), m.Type().(*types.Signature), q)))
	}
	slices.Sort(methods)
	return append(out, methods...)
}

// tagOf renders a struct tag, which is part of the contract wherever encoding
// or the ORM's own reflection reads it.
func tagOf(tag string) string {
	if tag == "" {
		return ""
	}
	return " `" + tag + "`"
}

// signature renders a function or method signature.
func signature(name string, sig *types.Signature, q types.Qualifier) string {
	var b bytes.Buffer
	b.WriteString(name)
	b.WriteString(typeParams(sig.TypeParams(), q))
	b.WriteString("(")
	params := sig.Params()
	for i := range params.Len() {
		if i > 0 {
			b.WriteString(", ")
		}
		t := params.At(i).Type()
		if sig.Variadic() && i == params.Len()-1 {
			b.WriteString("...")
			if s, ok := t.(*types.Slice); ok {
				t = s.Elem()
			}
		}
		b.WriteString(types.TypeString(t, q))
	}
	b.WriteString(")")

	res := sig.Results()
	switch res.Len() {
	case 0:
	case 1:
		b.WriteString(" " + types.TypeString(res.At(0).Type(), q))
	default:
		b.WriteString(" (")
		for i := range res.Len() {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(types.TypeString(res.At(i).Type(), q))
		}
		b.WriteString(")")
	}
	return b.String()
}

// typeParams renders a type parameter list with its constraints.
//
// The constraint is included because tightening one is a breaking change that
// changes no name and no arity: code that instantiated the type yesterday stops
// compiling today, and nothing about the declaration looks different unless the
// constraint is written down.
func typeParams(tp *types.TypeParamList, q types.Qualifier) string {
	if tp == nil || tp.Len() == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("[")
	for i := range tp.Len() {
		if i > 0 {
			b.WriteString(", ")
		}
		p := tp.At(i)
		b.WriteString(p.Obj().Name())
		b.WriteString(" ")
		b.WriteString(types.TypeString(p.Constraint(), q))
	}
	b.WriteString("]")
	return b.String()
}

// qualifier renders every type by its full package path.
//
// Package *names* are ambiguous — two dependencies may both be called "schema" —
// and a manifest that used them would record a different string depending on
// which happened to be loaded. A path is unique and contains no local
// filesystem location.
func qualifier(pkg *types.Package) types.Qualifier {
	return func(other *types.Package) string {
		if other == pkg {
			return ""
		}
		return other.Path()
	}
}
