// Command genprojection writes the high-arity projection constructors.
//
// Project1 through Project8 are hand-written in projection.go and stay that
// way: their type-parameter names are part of the frozen v1 manifest, so
// regenerating them under a different naming scheme would read as an API
// change without being one. Everything from Project9 up is mechanical — the
// same twelve lines with a different arity — so it is generated rather than
// typed, and a mistake in one of them is a mistake in all of them or in none.
//
// The generated constructors name their type parameters T1..TN. The
// hand-written ones use A, B, C, D, F, G, H, I, skipping E because E is the
// entity. That scheme does not extend past a handful of letters, which is the
// other reason the boundary sits where it does.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	out := flag.String("out", "projection_gen.go", "file to write")
	from := flag.Int("from", 9, "lowest arity to generate")
	to := flag.Int("to", 50, "highest arity to generate")
	flag.Parse()

	if err := run(*out, *from, *to); err != nil {
		fmt.Fprintln(os.Stderr, "genprojection:", err)
		os.Exit(1)
	}
}

func run(out string, from, to int) error {
	if from < 2 || to < from {
		return fmt.Errorf("bad arity range %d..%d", from, to)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by internal/tools/genprojection. DO NOT EDIT.

package orm

// The constructors below are Project%d through Project%d. They are the same
// shape as the hand-written Project1..Project8 in projection.go — N typed
// locals, one Scan, one call, no reflection and no assertions — and they exist
// because a wide report is a real query and 8 is an arbitrary place to stop.
//
// Reaching for one of the very wide ones is worth a second thought: past a
// dozen or so columns, a projection is approaching the row it was meant to
// narrow, and an entity query or a nested struct is usually the clearer thing.
// The arities are here so that the ORM is not the reason you cannot write the
// query, not because a fifty-column function literal is good style.
`, from, to)

	for n := from; n <= to; n++ {
		emit(&b, n)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}
	return os.WriteFile(out, src, 0o644)
}

func emit(b *bytes.Buffer, n int) {
	var (
		tparams = seq(n, "T%d")  // T1, T2, ...
		args    = seq(n, "e%d")  // e1, e2, ...
		locals  = seq(n, "v%d")  // v1, v2, ...
		addrs   = seq(n, "&v%d") // &v1, &v2, ...
	)

	fmt.Fprintf(b, "\n// Project%d builds a %s-expression result shape.\n", n, words(n))
	fmt.Fprintf(b, "func Project%d[E, %s, R any](\n", n, strings.Join(tparams, ", "))
	for i := range n {
		fmt.Fprintf(b, "\t%s Selectable[E, %s],\n", args[i], tparams[i])
	}
	fmt.Fprintf(b, "\tbuild func(%s) R,\n", strings.Join(tparams, ", "))
	fmt.Fprintf(b, ") Projection[E, R] {\n")
	fmt.Fprintf(b, "\treturn Projection[E, R]{\n")
	fmt.Fprintf(b, "\t\titems: items(%s),\n", join(args, ".selectItem()", ", "))
	fmt.Fprintf(b, "\t\tshape: shapeOf(%s),\n", wrap(args, "slotOf(%s)", ", "))
	fmt.Fprintf(b, "\t\tnewScan: func() func(pgxRows) (R, error) {\n")
	fmt.Fprintf(b, "\t\t\tvar (\n")
	for i := range n {
		fmt.Fprintf(b, "\t\t\t\t%s %s\n", locals[i], tparams[i])
	}
	fmt.Fprintf(b, "\t\t\t)\n")
	fmt.Fprintf(b, "\t\t\tdest := []any{%s}\n", strings.Join(addrs, ", "))
	fmt.Fprintf(b, "\t\t\treturn func(rows pgxRows) (R, error) {\n")
	fmt.Fprintf(b, "\t\t\t\tif err := rows.Scan(dest...); err != nil {\n")
	fmt.Fprintf(b, "\t\t\t\t\tvar zero R\n")
	fmt.Fprintf(b, "\t\t\t\t\treturn zero, err\n")
	fmt.Fprintf(b, "\t\t\t\t}\n")
	fmt.Fprintf(b, "\t\t\t\treturn build(%s), nil\n", strings.Join(locals, ", "))
	fmt.Fprintf(b, "\t\t\t}\n")
	fmt.Fprintf(b, "\t\t},\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n")
}

func seq(n int, format string) []string {
	out := make([]string, n)
	for i := range n {
		out[i] = fmt.Sprintf(format, i+1)
	}
	return out
}

func join(names []string, suffix, sep string) string {
	out := make([]string, len(names))
	for i, s := range names {
		out[i] = s + suffix
	}
	return strings.Join(out, sep)
}

func wrap(names []string, format, sep string) string {
	out := make([]string, len(names))
	for i, s := range names {
		out[i] = fmt.Sprintf(format, s)
	}
	return strings.Join(out, sep)
}

var small = [...]string{
	9: "nine", 10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen",
	14: "fourteen", 15: "fifteen", 16: "sixteen", 17: "seventeen",
	18: "eighteen", 19: "nineteen", 20: "twenty",
}

// words spells the small arities out, matching the hand-written doc comments
// ("a two-expression result shape"), and falls back to digits past twenty where
// spelling it out stops helping anyone read it.
func words(n int) string {
	if n < len(small) && small[n] != "" {
		return small[n]
	}
	return fmt.Sprint(n)
}
