package viewdemo_test

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/AlexAli29/orm"
	"github.com/AlexAli29/orm/internal/testdb"
	"github.com/AlexAli29/orm/internal/viewdemo"
	"github.com/AlexAli29/orm/observe"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// M16.5 Stage A: views and materialized views as query sources.
//
// Everything here goes through the ordinary Query builder. There is no view
// query path to test, which is the point — a view is a source, and the compiler
// below it never learns otherwise.

const schemaSQL = `
CREATE TABLE users (
	id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email      text NOT NULL,
	active     boolean NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	settings   jsonb NOT NULL DEFAULT '{}',
	last_ip    inet
);
CREATE TABLE orders (
	id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES users(id),
	price   numeric NOT NULL
);

CREATE VIEW active_users AS
	SELECT id, email, created_at, settings FROM users WHERE active;

CREATE VIEW user_orders AS
	SELECT u.id AS user_id, u.email, o.price
	FROM users u LEFT JOIN orders o ON o.user_id = u.id;

CREATE MATERIALIZED VIEW user_totals AS
	SELECT u.id AS user_id, count(o.id) AS orders, sum(o.price) AS total
	FROM users u LEFT JOIN orders o ON o.user_id = u.id
	GROUP BY u.id WITH DATA;
CREATE UNIQUE INDEX user_totals_user_id_key ON user_totals (user_id);

INSERT INTO users (email, active) VALUES
	('a@example.com', true), ('b@example.com', true), ('quiet@example.com', true);
INSERT INTO users (email, active) VALUES ('gone@example.com', false);
INSERT INTO orders (user_id, price) VALUES (1, '10.00'), (1, '5.00'), (2, '7.50');
REFRESH MATERIALIZED VIEW user_totals;
`

func open(t *testing.T) (*viewdemo.DB, *pgxpool.Pool) {
	t.Helper()
	testdb.AdminDSN(t)
	dsn := testdb.Create(t, schemaSQL)
	pool, err := pgxpool.New(t.Context(), dsn)
	if err != nil {
		t.Fatalf("opening: %v", err)
	}
	t.Cleanup(pool.Close)
	return viewdemo.New(pool), pool
}

// A view reads through the ordinary builder.
func TestView_reads(t *testing.T) {
	db, _ := open(t)
	rows, err := db.ActiveUsers.Query().
		Where(viewdemo.ActiveUsers.Email.Like("%@example.com")).
		OrderBy(viewdemo.ActiveUsers.Email.Asc()).
		Limit(2).
		All(t.Context())
	if err != nil {
		t.Fatalf("reading the view: %v", err)
	}
	if len(rows) != 2 {
		t.Fatalf("got %d rows, want 2", len(rows))
	}
	if rows[0].Email != "a@example.com" {
		t.Errorf("first row is %s", rows[0].Email)
	}
	// The inactive user is not in the view, which is the view's own predicate
	// doing its job rather than anything the ORM added.
	all, err := db.ActiveUsers.Query().All(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 3 {
		t.Errorf("the view returned %d rows, want 3", len(all))
	}
}

// Release-critical: a view column that the definition can leave NULL scans as
// NULL, even though its base column is NOT NULL.
func TestView_outerJoinNullabilitySurvives(t *testing.T) {
	db, _ := open(t)
	rows, err := db.UserOrders.Query().
		Where(viewdemo.UserOrders.Email.Eq("quiet@example.com")).
		All(t.Context())
	if err != nil {
		t.Fatalf("reading: %v", err)
	}
	if len(rows) != 1 {
		t.Fatalf("got %d rows, want 1", len(rows))
	}
	if rows[0].Price != nil {
		t.Errorf("price = %q, want NULL: orders.price is NOT NULL on its table and "+
			"the view's LEFT JOIN still produces NULL for a user with no orders", *rows[0].Price)
	}
}

// A view joins a table, and the join goes through the ordinary composition
// layer. Nothing here is view-aware: a view is a *Source, and From/Join take a
// *Source, so this is the same code path a table join takes.
func TestView_joinsATable(t *testing.T) {
	_, pool := open(t)
	id := orm.Named("id", orm.Of(viewdemo.ActiveUsers.ID))
	sql, _, err := orm.Rows(id).
		From(viewdemo.ActiveSource()).
		LeftJoin(viewdemo.UsersSource(), orm.Cond(viewdemo.Users.Active.Eq(true))).
		Using(pool).
		SQL()
	if err != nil {
		t.Fatalf("building: %v", err)
	}
	if !strings.Contains(sql, "active_users") || !strings.Contains(sql, `"users"`) {
		t.Errorf("the join names neither relation:\n%s", sql)
	}
}

// Three aliases of one view stay three sources. A view's identity is its
// pointer exactly as a table's is, so this is the frozen source-identity system
// rather than anything new.
func TestView_selfJoinKeepsSourceIdentity(t *testing.T) {
	_, pool := open(t)
	a := viewdemo.ActiveSource().As("a")
	b := viewdemo.ActiveSource().As("b")
	c := viewdemo.ActiveSource().As("c")
	col := func(src *orm.Source) orm.OrdCol[viewdemo.ActiveUser, int64] {
		return orm.NewOrdCol[viewdemo.ActiveUser, int64](src, "id")
	}

	sql, _, err := orm.Rows(orm.Named("id", orm.Of(col(a)))).
		From(a).
		Join(b, orm.Cond(col(b).EqCol(col(a)))).
		Join(c, orm.Cond(col(c).EqCol(col(b)))).
		Using(pool).
		SQL()
	if err != nil {
		t.Fatalf("building: %v", err)
	}
	for _, alias := range []string{`"a"`, `"b"`, `"c"`} {
		if !strings.Contains(sql, alias) {
			t.Errorf("the alias %s collapsed:\n%s", alias, sql)
		}
	}
}

// A view in a CTE, joined to a materialized view: both are sources and the
// compiler below never learns which kind of relation either is.
func TestView_composesWithCTEsAndMatViews(t *testing.T) {
	_, pool := open(t)
	vid := orm.Named("id", orm.Of(viewdemo.ActiveUsers.ID))
	cte := orm.CTE("recent", orm.Rows(vid).From(viewdemo.ActiveSource()))

	sql, _, err := orm.Rows(orm.Named("id", orm.Ref(cte, vid))).
		With(cte).
		From(cte).
		LeftJoin(viewdemo.TotalsSource(), orm.Cond(viewdemo.UserTotals.Orders.Gte(0))).
		Using(pool).
		SQL()
	if err != nil {
		t.Fatalf("building: %v", err)
	}
	for _, want := range []string{"WITH", "recent", "active_users", "user_totals", "LEFT JOIN"} {
		if !strings.Contains(sql, want) {
			t.Errorf("the statement does not contain %q:\n%s", want, sql)
		}
	}
}

// A materialized view reads the same way.
func TestMatView_reads(t *testing.T) {
	db, _ := open(t)
	rows, err := db.UserTotals.Query().
		Where(viewdemo.UserTotals.Orders.Gt(0)).
		OrderBy(viewdemo.UserTotals.UserID.Asc()).
		All(t.Context())
	if err != nil {
		t.Fatalf("reading: %v", err)
	}
	if len(rows) != 2 {
		t.Fatalf("got %d rows, want 2", len(rows))
	}
	if rows[0].Orders != 2 {
		t.Errorf("first total has %d orders, want 2", rows[0].Orders)
	}
}

// Refresh replaces the contents, and the view sees the new rows.
func TestMatView_refresh(t *testing.T) {
	db, pool := open(t)
	if _, err := pool.Exec(t.Context(),
		`INSERT INTO orders (user_id, price) VALUES (3, '99.00')`); err != nil {
		t.Fatalf("inserting: %v", err)
	}

	before, err := db.UserTotals.Query().Where(viewdemo.UserTotals.UserID.Eq(3)).All(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if len(before) != 1 || before[0].Orders != 0 {
		t.Fatalf("the materialized view already sees the new order: %+v", before)
	}

	if err := db.UserTotals.Refresh(t.Context()); err != nil {
		t.Fatalf("refreshing: %v", err)
	}
	after, err := db.UserTotals.Query().Where(viewdemo.UserTotals.UserID.Eq(3)).All(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if len(after) != 1 || after[0].Orders != 1 {
		t.Errorf("after a refresh the view reports %+v", after)
	}
}

// CONCURRENTLY works when the schema has the index PostgreSQL requires.
func TestMatView_refreshConcurrently(t *testing.T) {
	db, _ := open(t)
	if err := db.UserTotals.Refresh(t.Context(), orm.Concurrently()); err != nil {
		t.Fatalf("concurrent refresh: %v", err)
	}
}

// And is refused before anything is sent when the schema shows no candidate.
func TestMatView_concurrentlyNeedsAQualifyingIndex(t *testing.T) {
	db, _ := open(t)
	err := db.TotalsNoIndex.Refresh(t.Context(), orm.Concurrently())
	if err == nil {
		t.Fatal("a concurrent refresh was attempted with no qualifying unique index")
	}
	if !strings.Contains(err.Error(), "unique index") {
		t.Errorf("the error does not say what is missing: %v", err)
	}
	// It never reached the server, so there is no PgError under it.
	var pg *pgconn.PgError
	if errors.As(err, &pg) {
		t.Errorf("the statement was sent after all: %v", pg)
	}
}

// CONCURRENTLY and WITH NO DATA cannot be combined.
func TestMatView_concurrentlyWithNoDataIsRefused(t *testing.T) {
	db, _ := open(t)
	err := db.UserTotals.Refresh(t.Context(), orm.Concurrently(), orm.WithNoData())
	if err == nil {
		t.Fatal("CONCURRENTLY was combined with WITH NO DATA")
	}
	if !strings.Contains(err.Error(), "WITH NO DATA") {
		t.Errorf("the error does not name the combination: %v", err)
	}
	// And it was refused here rather than by the server. PostgreSQL rejects
	// this combination too, and its message also says WITH NO DATA — so
	// matching the text proves nothing on its own. The absence of a PgError is
	// what proves nothing was sent.
	var pg *pgconn.PgError
	if errors.As(err, &pg) {
		t.Errorf("the combination reached the server before being refused: %v", pg)
	}
}

// WITH NO DATA empties the view, and PostgreSQL then refuses to read it. The
// server's error is preserved rather than replaced by a local guess about
// staleness.
func TestMatView_withNoDataLeavesItUnreadable(t *testing.T) {
	db, _ := open(t)
	if err := db.UserTotals.Refresh(t.Context(), orm.WithNoData()); err != nil {
		t.Fatalf("refreshing with no data: %v", err)
	}
	_, err := db.UserTotals.Query().All(t.Context())
	if err == nil {
		t.Fatal("an unpopulated materialized view was read without error")
	}
	var pg *pgconn.PgError
	if !errors.As(err, &pg) {
		t.Fatalf("PostgreSQL's own error did not survive: %v", err)
	}
	if pg.Code != "55000" {
		t.Errorf("SQLSTATE = %s, want 55000 (object not in prerequisite state)", pg.Code)
	}

	// And a concurrent refresh of an unpopulated view is the server's refusal,
	// not a cached local claim: the index qualifies, so nothing here can know.
	err = db.UserTotals.Refresh(t.Context(), orm.Concurrently())
	if err == nil {
		t.Fatal("a concurrent refresh of an unpopulated view succeeded")
	}
	if !errors.As(err, &pg) {
		t.Errorf("the server's error was replaced by a local one: %v", err)
	}

	// An ordinary refresh brings it back.
	if err := db.UserTotals.Refresh(t.Context()); err != nil {
		t.Fatalf("repopulating: %v", err)
	}
	if _, err := db.UserTotals.Query().All(t.Context()); err != nil {
		t.Errorf("the view is still unreadable after a refresh: %v", err)
	}
}

// A refresh against a missing relation preserves PostgreSQL's error.
func TestMatView_pgErrorSurvives(t *testing.T) {
	db, pool := open(t)
	if _, err := pool.Exec(t.Context(), `DROP MATERIALIZED VIEW user_totals`); err != nil {
		t.Fatalf("dropping: %v", err)
	}
	err := db.UserTotals.Refresh(t.Context())
	if err == nil {
		t.Fatal("refreshing a dropped materialized view succeeded")
	}
	var pg *pgconn.PgError
	if !errors.As(err, &pg) {
		t.Fatalf("errors.As found no PgError: %v", err)
	}
	if pg.Code != "42P01" {
		t.Errorf("SQLSTATE = %s, want 42P01", pg.Code)
	}
}

// A cancelled context cancels a refresh.
func TestMatView_contextCancellation(t *testing.T) {
	db, _ := open(t)
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	err := db.UserTotals.Refresh(ctx)
	if err == nil {
		t.Fatal("a refresh on a cancelled context succeeded")
	}
	if !errors.Is(err, context.Canceled) {
		t.Errorf("errors.Is(err, context.Canceled) is false: %v", err)
	}
}

// Refresh works inside a transaction, through the transaction's executor.
func TestMatView_refreshInATransaction(t *testing.T) {
	_, pool := open(t)
	tx, err := pool.Begin(t.Context())
	if err != nil {
		t.Fatalf("beginning: %v", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	if err := viewdemo.New(tx).UserTotals.Refresh(t.Context()); err != nil {
		t.Errorf("refreshing inside a transaction: %v", err)
	}
}

// recorder is a tracer that keeps what it was told.
type recorder struct {
	starts []observe.StartEvent
	ends   []observe.EndEvent
}

func (r *recorder) Start(ctx context.Context, e observe.StartEvent) context.Context {
	r.starts = append(r.starts, e)
	return ctx
}
func (r *recorder) End(ctx context.Context, e observe.EndEvent) { r.ends = append(r.ends, e) }

// A refresh is one traced operation on the existing tracing architecture, and
// it carries no bind values because REFRESH has none.
func TestMatView_refreshIsTracedOnce(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	if err := db.UserTotals.Refresh(t.Context()); err != nil {
		t.Fatalf("refreshing: %v", err)
	}
	if len(rec.starts) != 1 {
		t.Fatalf("a refresh produced %d operations, want exactly one: %+v", len(rec.starts), rec.starts)
	}
	e := rec.starts[0]
	if e.Op != observe.OpRefresh {
		t.Errorf("Op = %q, want %q", e.Op, observe.OpRefresh)
	}
	if !strings.Contains(e.SQL, "REFRESH MATERIALIZED VIEW") {
		t.Errorf("the event does not carry the statement: %q", e.SQL)
	}
	if e.Args != 0 {
		t.Errorf("the refresh event reports %d bind values; REFRESH takes none", e.Args)
	}
	if e.Raw {
		t.Error("the refresh is reported as caller-written SQL; the ORM built it")
	}
	if len(rec.ends) != 1 || rec.ends[0].Err != nil {
		t.Errorf("the end event is %+v", rec.ends)
	}

	// A failing refresh is still one operation, and still records the failure.
	if _, err := pool.Exec(t.Context(), `DROP MATERIALIZED VIEW user_totals`); err != nil {
		t.Fatal(err)
	}
	rec.starts, rec.ends = nil, nil
	if err := db.UserTotals.Refresh(t.Context()); err == nil {
		t.Fatal("refreshing a dropped view succeeded")
	}
	if len(rec.starts) != 1 {
		t.Errorf("a failed refresh produced %d operations", len(rec.starts))
	}
	if len(rec.ends) != 1 || rec.ends[0].Err == nil {
		t.Errorf("the failure was not recorded: %+v", rec.ends)
	}
}

// A refresh refused before it is sent produces no event at all: nothing ran.
func TestMatView_refusedRefreshEmitsNothing(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	if err := db.TotalsNoIndex.Refresh(t.Context(), orm.Concurrently()); err == nil {
		t.Fatal("the refresh was not refused")
	}
	if len(rec.starts) != 0 {
		t.Errorf("a refusal that never reached the server emitted %+v", rec.starts)
	}
}

// M16.5 G2 Part F: what the concurrent-refresh rule does and does not decide.
//
// The schema half is decidable without a round trip and is checked before
// anything is sent. The runtime half — whether the view holds data — belongs to
// the server, changes between one statement and the next, and is never cached
// here.

// F18: the eligibility rule applies to CONCURRENTLY and nothing else. A plain
// refresh works with no qualifying index at all.
func TestMatView_normalRefreshNeedsNoUniqueIndex(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	if err := db.TotalsNoIndex.Refresh(t.Context()); err != nil {
		t.Fatalf("a plain refresh was refused for want of an index it does not need: %v", err)
	}
	if len(rec.starts) != 1 {
		t.Fatalf("a plain refresh produced %d operations, want one", len(rec.starts))
	}
	if strings.Contains(rec.starts[0].SQL, "CONCURRENTLY") {
		t.Errorf("a plain refresh sent CONCURRENTLY: %s", rec.starts[0].SQL)
	}
}

// F19: CONCURRENTLY and WITH NO DATA cannot be combined, and the refusal costs
// no round trip — there are no rows to replace with.
func TestMatView_concurrentlyWithNoDataIsRefusedBeforeSQL(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	// Refused even where a qualifying index exists: this is PostgreSQL's rule
	// about the combination, not about the index.
	if err := db.UserTotals.Refresh(t.Context(), orm.Concurrently(), orm.WithNoData()); err == nil {
		t.Fatal("CONCURRENTLY with WITH NO DATA was accepted")
	}
	if len(rec.starts) != 0 {
		t.Errorf("a refusal that never reached the server emitted %+v", rec.starts)
	}
}

// F1: with a qualifying index the statement is sent, once, and says
// CONCURRENTLY.
func TestMatView_qualifyingIndexSendsOneConcurrentStatement(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	if err := db.UserTotals.Refresh(t.Context(), orm.Concurrently()); err != nil {
		t.Fatalf("refreshing concurrently with a qualifying index: %v", err)
	}
	if len(rec.starts) != 1 {
		t.Fatalf("one refresh produced %d operations", len(rec.starts))
	}
	if !strings.Contains(rec.starts[0].SQL, "CONCURRENTLY") {
		t.Errorf("the statement is not concurrent: %s", rec.starts[0].SQL)
	}
	if rec.starts[0].Args != 0 {
		t.Errorf("REFRESH carried %d arguments; it takes none", rec.starts[0].Args)
	}
}

// F16: population is the server's to know. With a qualifying index but no data,
// the schema check passes, the statement is sent, and PostgreSQL's own error
// comes back reachable.
func TestMatView_unpopulatedIsTheServersAnswer(t *testing.T) {
	_, pool := open(t)
	rec := &recorder{}
	db := viewdemo.New(orm.Traced(pool, rec))

	if err := db.UserTotals.Refresh(t.Context(), orm.WithNoData()); err != nil {
		t.Fatalf("emptying the view: %v", err)
	}
	rec.starts, rec.ends = nil, nil

	err := db.UserTotals.Refresh(t.Context(), orm.Concurrently())
	if err == nil {
		t.Fatal("a concurrent refresh of an unpopulated view succeeded")
	}
	// It was sent: nothing here decided the answer on its own.
	if len(rec.starts) != 1 {
		t.Errorf("the refresh was refused locally rather than by the server: %+v", rec.starts)
	}
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		t.Fatalf("PostgreSQL's error is not reachable: %v", err)
	}
	if pgErr.Code == "" {
		t.Error("the SQLSTATE was lost")
	}

	// And the view can be refreshed back into a state where it works again,
	// which proves nothing cached the population it just saw.
	if err := db.UserTotals.Refresh(t.Context()); err != nil {
		t.Fatalf("repopulating: %v", err)
	}
	if err := db.UserTotals.Refresh(t.Context(), orm.Concurrently()); err != nil {
		t.Errorf("after repopulating, a concurrent refresh was still refused: %v", err)
	}
}
